### ISSUE TITLE
Bybit Trades do not work for Linear Futures

### ISSUE THREAD

**Issue by pavs94** [bmoscon/cryptofeed#1010]
**Describe the bug**
When subscribing to BTCUSDT Perpetual Futures, the subscription fails as the websocket connection url is different on bybit  

**To Reproduce**
- Subscribe to BTC-USDT Pair of Bybit
https://www.bybit.com/trade/usdt/BTCUSDT
- Tried - BTCUSDT, BTC-USDT, BTC-USDT-PERP
- Code:
```
from datetime import datetime as dt

from cryptofeed import FeedHandler
from cryptofeed.backends.aggregate import Throttle
from cryptofeed.defines import TRADES
from cryptofeed.exchanges import Bybit


async def trade(t, receipt_timestamp):
    print(f"Book received at {t} ts: {receipt_timestamp}")


def main():
    f = FeedHandler()
    f.add_feed(Bybit(symbols=['BTC-USDT-PERP'], channels=[TRADES], callbacks={TRADES: trade}))

    f.run()


if __name__ == '__main__':
    main()
```

**Expected behavior**
- Get Trades for Bybit BTCUSDT. Subscribe to the correct websocket
https://bybit-exchange.github.io/docs/v5/ws/connect
- USDT Futures: wss://stream.bybit.com/v5/public/linear
- Inverse Futures: wss://stream.bybit.com/v5/public/inverse
- Upgrade Bybit functions with the upgraded Websockets

**Operating System:**
- macOS

**Cryptofeed Version**
- installed via pip - v2.4.0

**Comment by gawaboga** [comment]
Hi, I'm getting same errors:
2024-03-07 16:26:43,689 : ERROR : BYBIT.ws.1: Error from exchange {'success': False, 'ret_msg': 'error:handler not found,topic:instrument_info.100ms.BTCUSDT', 'conn_id': '26ffa4fb-e6aa-48fb-94b3-91f415ec765c', 'req_id': '', 'op': 'subscribe'}

how to solve? Thanks really appreciate, Sam
