### ISSUE TITLE
Error in kraken L2_book

### ISSUE THREAD

**Issue by zhangzining** [bmoscon/cryptofeed#102]
ERROR : KRAKEN: error handling message [0,{"as":[["7930.70000","0.81000000","1560235533.240656"],
......
["7934.90000","0.29300000","1560235487.901273"]],"bs":[["7927.80000","0.14200000","1560235500.265460"],
......
["7924.30000","0.10910000","1560235501.583426"]]},"book-10","XBT/USD"]

 ERROR : KRAKEN: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/home/zhang/PycharmProjects/cryptofeed/cryptofeed/feedhandler.py", line 167, in _connect
    await self._handler(websocket, feed.message_handler, feed.id)
  File "/home/zhang/PycharmProjects/cryptofeed/cryptofeed/feedhandler.py", line 185, in _handler
    await handler(message)
  File "/home/zhang/PycharmProjects/cryptofeed/cryptofeed/kraken/kraken.py", line 129, in message_handler
    await self._book(msg, self.channel_map[msg[0]][1])
  File "/home/zhang/PycharmProjects/cryptofeed/cryptofeed/kraken/kraken.py", line 112, in _book
    self.l2_book[pair][side][price] = size
KeyError: 'BTC-USD'

when try to use:
f.add_feed(Kraken(config={TRADES: ['BTC-USD'], L2_BOOK: ['BTC-USD']}, callbacks={TRADES: TradeCallback(trade), L2_BOOK: BookCallback(book)}))
or
f.add_feed(Kraken(channels=[L2_BOOK], pairs=['BTC-USD'], callbacks={L2_BOOK: BookCallback(self.book)}))

I don't know how to solve it

**Comment by bmoscon** [comment]
@zhangzining thanks for opening this. I'll test locally today and see if I can reproduce the issue (and if I can, I'll fix it)

**Comment by bmoscon** [comment]
@zhangzining can you give me more information about what `book` and `self.book` are? They are the functions/methods listed in your callbacks. I want to be sure they arent modifying the state of the cryptofeed data members.

**Comment by zhangzining** [comment]
@bmoscon I'm sure the callback method has no problem. I copy it from your `demo.py`. Has read your source code, I think the error take place in` kraken.py `at `_book` method.
    async def _book(self, msg, pair):
        # print(msg)
        delta = {BID: [], ASK: []}
        msg = msg[1:]
        if len(msg) == 1 and 'as' in msg[0]: # HERE
            # Snapshot
            self.l2_book[pair] = {BID: sd({
                Decimal(update[0]): Decimal(update[1]) for update in msg[0]['bs']
            }), ASK: sd({
                Decimal(update[0]): Decimal(update[1]) for update in msg[0]['as']
            })}
            await self.book_callback(pair, L2_BOOK, True, delta, time.time())
        else:
            for m in msg:

**Comment by bmoscon** [comment]
@zhangzining kraken's websocket API changed. I've fixed/tested the code. Its in master now, will release a new version on pypi this week.
