### ISSUE TITLE
Influx Data Type

### ISSUE THREAD

**Issue by rick-sanchez-c137** [bmoscon/cryptofeed#103]
I was having trouble on aggregating trades data using influx. It turned out that both price and amount are written as string, is it intended?  It would be really convenient if they are stored as float.

**Comment by rick-sanchez-c137** [comment]
I took out the two pairs of double quotes surrounded, and it works fine.

`
class TradeInflux(InfluxCallback):
    def __init__(self, *args, key='trades', **kwargs):
        super().__init__(*args, **kwargs)
        self.key = key

    async def __call__(self, *, feed: str, pair: str, side: str, amount: Decimal, price: Decimal, order_id=None, timestamp=None):
        amount = str(amount)
        price = str(price)

        if order_id is None:
            order_id = 'None'
        trade = f'{self.key}-{feed},pair={pair} side="{side}",id="{order_id}",amount={amount},price={price},timestamp={timestamp}'

        await self.write(trade)
`

**Comment by bmoscon** [comment]
@rick-sanchez-c137 what if the data type was configurable? Strings do not lose precision, floats can/do (which is why I initially opted for str)

**Comment by rick-sanchez-c137** [comment]
@bmoscon I kinda got your ideal there.
Yet, at least, for 'price' and 'amount', they should be default to numeric type?

Influx currently doesn't support type conversion well, for their speed sake. If you create a server-side continuous policy, say aggregating trades to OHLCV every 5 min, it will fall.

**Comment by bmoscon** [comment]
@rick-sanchez-c137 ok, I'll make the change

**Comment by bmoscon** [comment]
fixed. You can specify the type you want with numeric_type as the arg on the book callback:

```python
L3_BOOK: BookInflux('http://localhost:8086', 'example', numeric_type=float), BOOK_DELTA: BookDeltaInflux('http://localhost:8086', 'example', numeric_type=float)
```
