### ISSUE TITLE
ArcticDB support ?

### ISSUE THREAD

**Issue by DennyZen** [bmoscon/cryptofeed#1034]
Hey gang!
do you plan to add ArcticDB support?
Its very important to handle For me ..
I need to refactor my old code.
 My stack was -  cryptofeed + arctic. need renew arctic for something coz it support python 3.8 only
I am thinking switch to ArcticDB
but.. any another ideas maybe? about backend and DB
i was using arctic because its python and very good efficiency  for time-series

**Comment by bmoscon** [comment]
I'm not planning on it but anyone who wants to is free to open a PR
