### ISSUE TITLE
Quest backend does not work with Kraken trades

### ISSUE THREAD

**Issue by carloe** [bmoscon/cryptofeed#1038]
**Describe the bug**
Trying to persist trades from Kraken in QuestDB fails silently. 

From what I can gather, the issue is that the older (1.9) Kraken ws API does not return `trade_id`s for trades, but the exchange classes seem to use this`trade_id` as the `id` when creating `Trade` objects. The `Kraken` class does not set an id since it would be `None` anyway:

https://github.com/bmoscon/cryptofeed/blob/7e0c6119692102762a048f765a69f096f1597b73/cryptofeed/exchanges/kraken.py#L105

When quest backend tries to persist the trade it will pass `None` in the update. And it appears that QuestDB will just ignore the insert if the the `id` of a row is `None`. (quest doesn't seem to mind `None` values in any other columns).

https://github.com/bmoscon/cryptofeed/blob/7e0c6119692102762a048f765a69f096f1597b73/cryptofeed/backends/quest.py#L59

Removing `,id={data["id"]}i` from the code above fixes the issue for Kraken trades, but obviously creates issues for the other exchanges.

**To Reproduce**

1. Try inserting trades in quest like so:
```python
f.add_feed(
    Kraken(channels=[TRADES], symbols=["BTC-USD"], callbacks={
        TRADES: TradeQuest(host=settings.qst_host, port=settings.qst_line_port)
    }
)

f.add_feed(
    Coinbase(channels=[TRADES], symbols=["BTC-USDT"], callbacks={
        TRADES: TradeQuest(host=settings.qst_host, port=settings.qst_line_port)
    })
)
```
2. Observe how coinbase trades are inserted in quest while kraken trades are not inserted, and also do not produce any errors.  

**Expected behavior**
- Trades from both exchanges are persisted.

**Operating System:**
 - MacOS, Ubuntu

**Cryptofeed Version**
- Python: 3.11
- Cryptofeed: 2.4.0

**Comment by carloe** [comment]
@bmoscon I'd be happy to pitch in to fix this. But since I am new to this code-base I am not sure what the best approach would be aside from either adding conditional logic to the quest class (hacky), or upgrading to Kraken WS V2, which does include the `trade_id` (scope). 

Any suggestions?

**Comment by bmoscon** [comment]
thanks for the PR!
