### ISSUE TITLE
Mac Mini M4 support? brand new code checkout seems not working

### ISSUE THREAD

**Issue by qqmastercom** [bmoscon/cryptofeed#1065]
Hi all,

I'm a big fan of cryptofeed，and has been using on windows for several years already.
 
I bought mac mini m4 a couple of days ago, and installed anaconda with Python 3.12, and pip installed cryptofeed 2.4.0. Tried to run the basic demo.py, but got below problem, i'm not able to solve. 

Appreciate any help, many thanks!

Andy

Connected to pydev debugger (build 242.23726.103)
2024-11-14 00:27:09,615 : ERROR : COINBASE.ws.1: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/cryptofeed/connection_handler.py", line 59, in _create_connection
    async with self.conn.connect() as connection:
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/cryptofeed/connection.py", line 104, in connect
    await self._open()
  File "/opt/anaconda3/lib/python3.12/site-packages/cryptofeed/connection.py", line 318, in _open
    self.conn = await websockets.connect(self.address, **self.ws_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/websockets/asyncio/client.py", line 441, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/websockets/asyncio/client.py", line 367, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1857, in uvloop.loop.Loop.create_connection
TypeError: create_connection() got an unexpected keyword argument 'read_limit'

**Comment by qqmastercom** [comment]
hi it's solved. 

The issue is websokets package, it seems MacOS is not compatible with latest websokets version (14.1), i downgraded to
Name: websockets
Version: 10.2
then it's fine.

**Comment by qqmastercom** [comment]
solved

**Comment by bmoscon** [comment]
I am working on upgrading the package to support the new version of websockets!

**Comment by qqmastercom** [comment]
thanks, that will be great, I just check windows also have same issue, great if latest websockets can be supported

**Comment by nevmerzhitsky** [comment]
Still face this problem with deps:

```
# pipenv requirements
-i https://pypi.org/simple
aiodns==3.2.0
aiofile==3.9.0; python_version >= '3.8' and python_version < '4'
aiohttp==3.9.1; python_version >= '3.8'
aiosignal==1.3.1; python_version >= '3.7'
async-timeout==4.0.3; python_version >= '3.7'
attrs==24.2.0; python_version >= '3.7'
caio==0.9.17; python_version >= '3.7' and python_version < '4'
certifi==2024.8.30; python_version >= '3.6'
cffi==1.17.1; python_version >= '3.8'
charset-normalizer==3.4.0; python_full_version >= '3.7.0'
cryptofeed==2.4.0; python_version >= '3.8'
frozenlist==1.5.0; python_version >= '3.8'
idna==3.10; python_version >= '3.6'
multidict==6.1.0; python_version >= '3.8'
order-book==0.6.1
propcache==0.2.0; python_version >= '3.8'
pycares==4.5.0; python_version >= '3.9'
pycparser==2.22; python_version >= '3.8'
pyyaml==6.0.2; python_version >= '3.8'
requests==2.32.3; python_version >= '3.8'
typing-extensions==4.12.2; python_version >= '3.8'
urllib3==2.2.3; python_version >= '3.8'
uvloop==0.21.0; python_full_version >= '3.8.0'
websockets==14.1; python_version >= '3.9'
yapic.json==1.9.5; python_version >= '3.7'
yarl==1.18.0; python_version >= '3.9'
```

and works fine after `pip install websockets~=13.0`

**Comment by bmoscon** [comment]
I'm using an M4 and I don't have any issues. What version of python are you using?

**Comment by nevmerzhitsky** [comment]
> I'm using an M4 and I don't have any issues. What version of python are you using?

I use 3.10

**Comment by bmoscon** [comment]
I'm using 3.12 without issue. How are you installing the library? you have to use the version in github, not pypi

**Comment by nevmerzhitsky** [comment]
> you have to use the version in github, not pypi

It was 2.4.0 from pypi. With 2.4.1 there is no problem, thanks.
