### ISSUE TITLE
Support Binance aggTrade

### ISSUE THREAD

**Issue by dinhnv** [bmoscon/cryptofeed#107]
According to Binance Stream document, I think `aggTrade` would be useful rather than `trade`. 

Could it be better to replace `standards.TRADES['BINANCE']` to `aggTrade` instead of `trade`?

https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#aggregate-trade-streams

**Comment by bmoscon** [comment]
@dinhnv ok ill look into it - thanks for the tip

**Comment by bmoscon** [comment]
@dinhnv after looking into it a bit further, I'm not sure what the advantage is. If you get the raw trade data, like it currently provides, you can aggregate on your end if you so desire. If i change it to use aggregated trades, I dont think you can extrapolate back to the raw data.

**Comment by dinhnv** [comment]
It may be useful in case of looking at how big orders are destroyed. And in many cases, `aggTrade` will help us reduce the amount of data transferring over the stream. 
I just inform you to look into it, but if it isn't helpful clearly, I could close this issue.

**Comment by bmoscon** [comment]
@dinhnv ok, makes sense. I'll make the change

**Comment by xiandong79** [comment]
And the users can switch to `trade` in standards.py if needed.

**Comment by bmoscon** [comment]
fixed - on master.
