### ISSUE TITLE
Feature Request - reference database for symbols

### ISSUE THREAD

**Issue by AlgoTrader5** [bmoscon/cryptofeed#111]
the data would contain at least these items:
- symbol
- exchange
- minTick (min price increment)
- minSize (the min order size allowed by exchange)
- maxSize (the max order size allowed by exchange)

data could be represented in a dictionary like so:
reference_data = { 
    exchange1: {
        sym1: {
            minTick: float,
            minSize: float,            
            maxSize: float
        },

**Comment by AnnimouseCryptoUser** [comment]
Bump, a metadata table would like this would be very useful for the purposes of order execution (respecting exchange min tick size, min $ notional, etc.)

**Comment by bmoscon** [comment]
@AnnimouseCryptoUser its on my list of to-dos, just low priority. Want to get to it this month though

**Comment by gshpychka** [comment]
Greetings - any updates on the fate of this feature?

**Comment by bmoscon** [comment]
no one has implemented it yet - I may do something along these lines, but it would have all the data encompassed above

**Comment by bmoscon** [comment]
@AlgoTrader5 @gshpychka @AnnimouseCryptoUser 
Ok, I went ahead and added this in. Its a classmethod, so you can do something like:

```python
from cryptofeed.exchange.coinbase import Coinbase

print(Coinbase.info())
```

and you'll see supported pairs, data channels, and tick size. If there are other fields you want, please open a ticket for each piece of information (or if they are related, please group them together in one ticket). Also make sure that its widely supported - if only 1 or 2 exchanges support it, its unlikely I'd add it (but you never know, and if I don't you can open a PR).

I haven't gone through every single exchange to add this in yet, I'm going top down (based on function ordering in pairs.py) so I've done up to coinbase.

**Comment by gshpychka** [comment]
Thank you!
