### ISSUE TITLE
Ticker method using BTC-USD in Kraken REST giving UnsupportedTradingPair exception

### ISSUE THREAD

**Issue by AlgoTrader5** [bmoscon/cryptofeed#114]
File "D:\Python\Python36\lib\site-packages\cryptofeed\rest\kraken.py", line 112, in ticker
    sym = pair_std_to_exchange(symbol, self.ID+'REST')
  File "D:\Python\Python36\lib\site-packages\cryptofeed\standards.py", line 55, in pair_std_to_exchange
    raise UnsupportedTradingPair(f'{pair} is not supported on {exchange}')
cryptofeed.exceptions.UnsupportedTradingPair: BTC-USD is not supported on KRAKENREST

**Comment by bmoscon** [comment]
I think its working as intended. Can you provide the code where you actually call it?

```
In [1]: from cryptofeed.rest import Rest

In [2]: r = Rest()

In [3]: r.kraken.ticker('BTC-USD')
Out[3]:
{'pair': 'BTC-USD',
 'feed': 'KRAKEN',
 'bid': Decimal('12171.10000'),
 'ask': Decimal('12175.50000')}

In [4]: r['kraken'].ticker('BTC-USD')
Out[4]:
{'pair': 'BTC-USD',
 'feed': 'KRAKEN',
 'bid': Decimal('12143.80000'),
 'ask': Decimal('12144.60000')}
```

**Comment by bmoscon** [comment]
spoke with @AlgoTrader5, this is not an issue
