### ISSUE TITLE
Coinbene publishes repeated trades

### ISSUE THREAD

**Issue by glgnohk** [bmoscon/cryptofeed#118]
Coinbene uses REST for market data. To get trades, it's API allows you to request the last N trades, up to 2,000. (See  https://github.com/Coinbene/API-Documents/wiki/1.1.2-Get-Trades-%5BMarket%5D ). Thus, a way to get trades is to repeatedly query the last trades and publish only non-repeated trades. The current code does this, but there's a bug in the logic, in this function:
https://github.com/bmoscon/cryptofeed/blob/5016b0cdba5ae69d7f86e403f9ada59f6446a79a/cryptofeed/coinbene/coinbene.py#L28

Let's say you get trades with ids: a,b,c. You'll publish these and store a,b,c in the last_trade_update dict. If a,b,c repeats again next poll, you won't publish, but the last_trade_update will get cleared out since the update dict is never updated. If a,b,c comes up again, it will be republished.  

You may have to check on timestamps instead, or keep a list of all tradeIDs. Several APIs in other exchanges allow you to get all trades after a given timestamp, so perhaps timestamp checking is the way to go?

**Comment by bmoscon** [comment]
@glgnohk thanks for the ticket, will get it fixed before next release!

**Comment by bmoscon** [comment]
should be fixed now, thanks for raising @glgnohk
