### ISSUE TITLE
Slow response compared to BitMEX webinterface

### ISSUE THREAD

**Issue by p0nt** [bmoscon/cryptofeed#119]
Hi,

So I am trying to figure out why this speed issue is coming up but I am unable to find it.

I run a simple script which is retrieving INSTRUMENT data from BitMEX as you can find below.

This idea is to compare the price from their webinterface to the retrieved price from the instruments socket, but it seems the instruments socket is very very late compared to their own webinterface.

I have recorded a small video with on the left part of the orderbook from bitmex, on the right the script shown above printing the askPrice whenever it changes.

https://youtu.be/o75MzlGtgRU

I wonder if this problem is caused by cryptofeed somewhere, or maybe instruments are not updated soon enough and I should check something else? If so, which one do I need.

Also I was wondering if cryptofeed allowed private streams, such as order or position as documented here:
https://www.bitmex.com/app/wsAPI

```#!/usr/bin/python3.7

from cryptofeed.callback import InstrumentCallback
from cryptofeed import FeedHandler
from cryptofeed.exchanges import Bitmex
from cryptofeed.defines import INSTRUMENT

async def instrument(**kwargs):

      if 'askPrice' in kwargs:
        print(kwargs['askPrice'])

def main():

    f = FeedHandler()
    f.add_feed(Bitmex(channels=[INSTRUMENT], pairs=['XBTUSD'], callbacks={INSTRUMENT: InstrumentCallback(instrument)}))
    f.run()

if __name__ == '__main__':

  main()```

**Comment by glgnohk** [comment]
It's quite common that instrument updates are delayed or not realtime. Use book or trades if you want realtime info.

**Comment by p0nt** [comment]
thanks, will look into it.

Also I was wondering if cryptofeed allowed private streams, such as order or position as documented here:
https://www.bitmex.com/app/wsAPI

**Comment by glgnohk** [comment]
Don't think so. you can see the messages processed here: https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/callback.py

**Comment by bmoscon** [comment]
@p0nt no private websocket data. As a US citizen I can't open an account on bitmex, so even if i wanted to add support for it I'd have no way to test it.

**Comment by bmoscon** [comment]
since there isnt really anything for me to act upon here - closing.
