### ISSUE TITLE
module 'asyncio' has no attribute 'run' (In python3.6)

### ISSUE THREAD

**Issue by malone6** [bmoscon/cryptofeed#122]
In setup.py, python version can be 3.6/3.7,but it raised exception when i run examples/demo_tcp.py used python=3.6.5.
```
File "demo_tcp.py", line 54, in <module>
    asyncio.run(main())
AttributeError: module 'asyncio' has no attribute 'run'
```
Actually, asyncio.run is a Python 3.7 addition

**Comment by bmoscon** [comment]
I believe the library itself is compatible with 3.6 even if the example code is not. If this is not the case, let me know

**Comment by bmoscon** [comment]
i looked and I was also using create_task, (3.7+) so definitely does not support 3.6. I've updated the readme and setup.py
