### ISSUE TITLE
process is no longer working after reconnect  11 retries

### ISSUE THREAD

**Issue by rendonghai** [bmoscon/cryptofeed#124]
In some rare cases, the feedhandler._connect function runs to retry 11 times.At this point, the feedhandler.run function is still running, but the entire process is no longer working.
You can reproduce the bug by following these steps:
1.Put breakpoint in the demo. Py file at the FeedHandler. Run line
2. Run to the feedhandler.run line
3.Disconnect the Internet
4. Keep running
Recommended add an exception after the line error (" % s: failed to reconnect after % d retries - the exiting ", feed. Id, retries), so the whole process can stop running.
![image](https://user-images.githubusercontent.com/30308433/61936566-97171f00-afbf-11e9-819e-ffc1a0af3969.png)

**Comment by bmoscon** [comment]
good catch. I've always set the number of retries to be very very high, so I've never had this happen. Thanks for raising the issue! I've fixed it on master

**Comment by xiandong79** [comment]
@rendonghai I fave a case where cryptostore and cryptofeed shouls never stop retry.

https://github.com/bmoscon/cryptostore/issues/30

in 2019-08-01，bitfinex.com is down for an upgrade.

all API said:

{
code: 503,
error: "temporarily_unavailable",
error_description: "Sorry, the service is temporarily unavailable. See https://www.bitfinex.com/ for more info."
}
In bitfinex.com:
“Please monitor bitfinex.statuspage.io and twitter.com/bitfinex for updates.”

However, after bitfinex.com restarted to offer the market data, Cryptostpre or Cryptofeed did not start to colllect the market data.

**Comment by xiandong79** [comment]
or with `code: 503`,  the Cryptostpre or Cryptofeed should not stop retry.
