### ISSUE TITLE
Test failed in cryptofeed/examples/demo_book_delta.py for Gemini

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#133]
I notice that @bmoscon update the logic of **Gemini**. Great idea!!!

However, it does not rull well in `cryptofeed/examples/demo_book_delta.py`

```python
def main():
    f = FeedHandler()
    f.add_feed(Gemini(book_interval=100, pairs=['BTC-USD'], callbacks=DeltaBook("Gemini").L2))
    f.run()
```

**Comment by bmoscon** [comment]
thanks for raising - this has been fixed. I re-tested with single pairs and with multiple pairs

**Comment by xiandong79** [comment]
thanks!!!
