### ISSUE TITLE
Increase Kraken L2 default depth to max depth (1000 instead of 10)?

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptofeed#134]
Is there a reason to use the minimum depth (10) for Kraken L2 books?  I'd say the max is better (1000) as default, but best would be to make it customizable.  I'm using it with cryptostore, so for that use-case it would be ideal to have a setting in the config file for the kraken L2 book depth (maybe best to open another issue there?).  Here is where it's set in cryptofeed: https://github.com/bmoscon/cryptofeed/blob/de7b2750f8d6d0fa85b06f4843595940ab622d8e/cryptofeed/kraken/kraken.py#L24

and here's the Kraken API docs on valid depth levels (10, 25, 100, 500, 1000): https://www.kraken.com/features/websocket-api#message-subscribe

**Comment by nateGeorge** [comment]
Now I see that it should be able to be changed in the cryptostore config file as `book_depth`.  However, this doesn't seem to be working.  I'll open an issue in cryptostore for that.

**Comment by bmoscon** [comment]
good catch, i set it to 10 once upon a time ago during some testing and never changed it back. fixed on master
