### ISSUE TITLE
Better rate handling for Kraken

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptofeed#136]
Looks like Kraken's REST API limits are about 1 call per 2s: https://support.kraken.com/hc/en-us/articles/206548367-What-are-the-REST-API-rate-limits-

I think the [sleep time in the historical data](https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/rest/kraken.py#L175) could be improved, or at least shortened.  Right now it's at 20s, but we could probably take it down to 5s.  We could also start it at 2s, and increase it by 1s each time it hits the rate limit in a row, something like:

```python
def _historical_trades(self, symbol, start_date, end_date, retry, retry_wait, freq='6H'):
    
    sleep_time = 2


    ...

    while start_date < end_date:
            r = helper(start_date)

        ...

        data = r.json()
        if 'error' in data and data['error']:
            if data['error'] == ['EAPI:Rate limit exceeded']:
                time.sleep(sleep_time)
                sleep_time += 1
                continue
            else:
                raise Exception(f"Error processing URL {r.url}: {data['error']}")

        sleep_time = 2
        yield_data
```

**Comment by bmoscon** [comment]
fixed - sorry it took so long - good catch :D
