### ISSUE TITLE
Improved Binance L2 book

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptofeed#137]
It looks like the recommended way to handle Binance L2 books is to first get a snapshot from the REST API, then update it with the websocket: https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#how-to-manage-a-local-order-book-correctly

Currently it looks like cryptofeed is only using the websocket.

**Comment by xiandong79** [comment]
concerned、

**Comment by bmoscon** [comment]
fixed on master. the previous implementation was just the top 20 of the book (no snapshot needed). changed to provide the full depth (at least as full as binance produces) with deltas
