### ISSUE TITLE
full channel que

### ISSUE THREAD

**Issue by rombin** [bmoscon/cryptofeed#14]
gdax help page for full channel via web-socket recommends to
1. subscribe to channel
2. que messages
3. take a REST snapshot
4. discard queued messages with id lower then the REST snapshot

just wondering if you do the discarding??

thank you

**Comment by bmoscon** [comment]
yes - see: https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/gdax/gdax.py#L187

The sequence number of the REST messages is tracked and any message that is earlier than the snapshot is discarded.

**Comment by rombin** [comment]
great, thank you
