### ISSUE TITLE
[upgrade] Is it safe and agile to save all exchange pairs in one dict.

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#140]
currently, variable **_exchange_to_standard** save different exchange pairs in one big dict.  
Is it more safe and agile to save each exchange pairs in one dict, and pack them in the big dict of **_exchange_to_standard**.

```
_exchange_to_standard = {
          'exchange_id_1': {
                       ADA/CAD: ADA-CAD,
                       ADA/ETH: ADA-ETH
}
          'exchange_id_2': {
                      aeeth: AE-ETH,
                      dbcbtc: DBC-BTC,
}
}
```

I notice that **_std_trading_pairs** has **_std_trading_pairs[pair][exchange]**

**Comment by bmoscon** [comment]
advantage is that you can translate a pair without needing to supply an exchange. you dont need to know which exchange supplied it to be able to do the translation, so not sure why you'd need the exchange.
