### ISSUE TITLE
cryptofeed should be an async client to work with Python/asyncio code

### ISSUE THREAD

**Issue by dinhnv** [bmoscon/cryptofeed#141]
When working with async/await code, I got an exception:

```
Traceback (most recent call last):
  File "lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 120, in run
    loop.run_forever()
  File "lib/python3.7/asyncio/base_events.py", line 526, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

I think that would be better if cryptofeed exposed an `async` `run` function to integrate with. It is similar to other [aio-libs](https://github.com/aio-libs/aiopg)

Usage example:

```
async def main():
    f = FeedHandler()
    f.add_feed(Coinbase(pairs=['BTC-USD'], channels=[TRADES], callbacks={TRADES: 
    TradeCallback(trade)})
    await f.run()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.run_forever()
```

**Comment by bmoscon** [comment]
I added an option to bypass running the loop internally in cryptofeed. You can call run with the `start_loop` kwarg set to `False`. An example is also included here: https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_existing_loop.py#L47
