### ISSUE TITLE
Feature request: Order book deltas for GEMINI

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#142]
I test the GEMINI with the cryptofeed and the cryptostore today.

However, 
1. as the cryptostore saves a new full snapshot whenever a new update comes.
2. the **update frequency of GEMINI** (message from websocket) is much higher than other exchanges.

So, an **Order book deltas** for GEMINI feature is needed.

The program crashed today as the Redis died as of out of memory.

**Comment by bmoscon** [comment]
just noticed there is a v2 of the gemini WS api. it also supports multiple pairs per connection, so looks like i can backout the recent changes i made. it also supports deltas - will work to get this new version supported asap

**Comment by bmoscon** [comment]
v2 support added - with deltas. the previous version supported deltas too, FYI
