### ISSUE TITLE
[upgrade] the prefix for msg in backends/zmq.py is not clear

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#145]
In backends/redis.py, cryptofeed has `{self.key}-{feed}-{pair}` as the redis KEY. However, in backends/zmq.py, 

1. `f'trades {json.dumps(trade)}' ` is used which is hard for the user to select/filter partial messages.
2. a blank between `trades` and `{json.dumps(trade)}` is hard for the user to split this string as many blanks are hidden in the json block.

what about `f'trades.{feed}.{pair}|{json.dumps(trade)}')` or some other standard format used in the cryptofeed?

**Comment by bmoscon** [comment]
This is due to how ZQM does subscriptions. The first part (trades) is the topic. The data has to be formatted this way for ZMQ. For more info on ZMQ see https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pubsub.html

**Comment by bmoscon** [comment]
I updated the example to make it more clear how to retrieve the dictionary

https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_zmq.py#L29

**Comment by xiandong79** [comment]
1. Thanks for the update in demo_zmq.py#L29.
2. I have read the link (https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pubsub.html).

I still hold the opinion that **f'trades.{feed}.{pair}'** is a more appropriate way to define a **"topic"** in zmq instead of **f'trades'**, as quant traders may only the market data from one exchange while I subscribe 10 exchanges in feedhandler.
