### ISSUE TITLE
[feature request] add func huobi_dm_pairs or get_acitve_pairs in huobi_dm.py and example.py

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#147]
For BITMEX, we have `get_acitve_pairs`, we can also have a similar func for HUIBI_DM

**Comment by glgnohk** [comment]
You don't need this function for Huobi_DM to deal with different expiries. See comment in the code:

https://github.com/bmoscon/cryptofeed/blob/89ede4800e00f6fcba03e9e3e26e8fe7181a23c6/cryptofeed/exchange/huobi_dm.py#L2

But, yeah, we could add to get the universe of pairs that is uses.

**Comment by xiandong79** [comment]
@glgnohk agree with you. I will `list(huobi_dm_pairs().keys)` to get all the active pairs, so that I can subscribe them all at once.

It would be better to have a static method like what have done in [bitmex.py - def get_active_symbols()](https://github.com/bmoscon/cryptofeed/blob/89ede4800e00f6fcba03e9e3e26e8fe7181a23c6/cryptofeed/exchange/bitmex.py#L57) to get all active pairs.

**Comment by glgnohk** [comment]
> It would be better to have a static method like what have done in bitmex.py - def get_active_symbols() to get all active pairs.

I am fine to add this.

I'l probably also change the one in OKEX, since it returns just futures, not swaps, just to make the calls all consistent.

**Comment by glgnohk** [comment]
> .It would be better to have a static method like what have done in bitmex.py - def get_active_symbols() to get all active pairs.

The question though is, does it return BTC_CW, etc., so returns a list of contracts to subscribe to, or BTC190927, so returns a list of symbols you see when the data is published?

Maybe somewhat related to https://github.com/bmoscon/cryptostore/issues/41

**Comment by bmoscon** [comment]
@glgnohk I'd say that you should keep the mapping you have, BTC_CW -> the actual symbol, but also allow subscribing by the real symbol, as well as provide a function to obtain all active symbols (the real symbol)

**Comment by bmoscon** [comment]
@xiandong79 - this is done - I added in a static method to all exchange classes called `info()` that returns information about what exchanges support (trading pairs, supported data channels, tick size, etc)
