### ISSUE TITLE
Different timestamp format for OKEX feed for different countries 

### ISSUE THREAD

**Issue by proskurin** [bmoscon/cryptofeed#159]
Hi, I have found that based on country where server is located OKEX BTC-USD-SWAP data in delivered in different formats:
1) USA - in floats
2) Singapore, Ukraine - in strings
Furthermore, it looks like number of records is also different based on country where user/server is located (I was writing data from U.S server and volumes were high, however, moving to Singapore massively decreased number of records)

**Comment by bmoscon** [comment]
if you can provide data examples for the timestamp formatting differences I can fix it. I know that they have different exchanges for different countries (not sure how many have their own) so 2 doesn't surprise me

**Comment by bmoscon** [comment]
Needs more info to adequately investigate. The timestamp normalization code should convert regardless of string or float.
