### ISSUE TITLE
Add Deribit Funding from TICKER

### ISSUE THREAD

**Issue by cticket** [bmoscon/cryptofeed#162]
Derbit has the funding rate in their Ticker channel.   It would be good to extract both the current and 8 hour funding.

{
  "jsonrpc": "2.0",
  "id": 8106,
  "result": {
    "best_ask_amount": 3010
    "best_ask_price": 3562.75,
    "best_bid_amount": 135710,
    "best_bid_price": 3562.5,
    **"current_funding": 0,
    "funding_8h": 0.00018344,**
    "index_price": 3563.53,
    "instrument_name": "BTC-PERPETUAL",
    "last_price": 3562.25,
    "mark_price": 3562.62,
    "max_price": 3598.21,
    "min_price": 3526.96,
    "open_interest": 23126.924145440054,
    "settlement_price": 3573.77,
    "state": "open",
    "stats": {
      "volume": 85934.31950267,
      "low": 3492,
      "high": 3660.25
    },
    "timestamp": 1550153198202
  }

**Comment by bmoscon** [comment]
Thanks for raising this - definitely something good to add

**Comment by bmoscon** [comment]
fixed
