### ISSUE TITLE
Add a Configuration Switch for Crypto Pairs

### ISSUE THREAD

**Issue by pottertech** [bmoscon/cryptofeed#163]
I use CCXT along with Cryptofeed.  CCXT uses '/' between crypto pairs while Cryptofeed uses '-'.  Could you please make this something adjustable so that I can line up the pairs in my DB and avoid all the millions of updates/calls to replace the '-' with '/'?

**Comment by bmoscon** [comment]
Definitely doable

**Comment by bmoscon** [comment]
I added some code to do this. Its only bee LIGHTLY tested, so give it a try and please report any errors / issues here. You'll have to use the code on master, i wont release this to pypi until its been more thoroughly tested. See: https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_pair_separator.py

Going to close this, but re-open if there are issues with it

**Comment by legendagain** [comment]
Hello! Sorry for reviving an old thread. What is the recommended way to change the default separator from "-" to "/" in today's context?

Thanks in advance!!

**Comment by bmoscon** [comment]
import this class:

https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/symbols.py#L13


and change the class variable, `symbol_sep` to whatever value you want.
