### ISSUE TITLE
Open Interest info

### ISSUE THREAD

**Issue by proskurin** [bmoscon/cryptofeed#184]
OKEx API has open interest channel availabe. Can I use cryptofeed to get that?

**Comment by bmoscon** [comment]
yes but its not currently implemented, so it would need to be added

**Comment by bmoscon** [comment]
@proskurin I had a look at their websocket docs again - I'm not seeing this. Where are you seeing information about this channel? I looked in the other channels (ticker, etc) and do not see open interest in any of them

**Comment by proskurin** [comment]
@bmoscon, it is here https://www.okex.com/docs/en/#ws_swap-ticker in **response examples**

**Comment by bmoscon** [comment]
added in latest release.
