### ISSUE TITLE
add the ability to stop the feedhandler eventloop.

### ISSUE THREAD

**Issue by sattusse** [bmoscon/cryptofeed#189]
As it's described in the topic, i think it would be a nice feature to bed added (and quite basic).
Just a basic stop function pretty much.

**Comment by bmoscon** [comment]
all you'd need to do anywhere in the code is

```
loop = asyncio.get_running_loop()
loop.stop()
```

I don't think a function or method is needed to do this, plus messing with the eventloop should only be done in very special circumstances
