### ISSUE TITLE
Inconsistent Kraken Pairs 

### ISSUE THREAD

**Issue by Jufik** [bmoscon/cryptofeed#197]
Looking at data from [pair endpoint](https://api.kraken.com/0/public/AssetPairs) and [this doc' ](https://support.kraken.com/hc/en-us/articles/360001185506-How-to-interpret-asset-codes)

For instance, looking at "XBT" available pairs, `cryptofeed.pairs.kraken_pairs` should return: 

- BTC-USDC (XBTUSDC)
- BTC-USDT (XBTUSDT)
- BTC-USD (XXBTZUSD)

Now, I do not really get what ".d" (eg XXBTZUSD.d) is for, I could help with relevant explanations

**Comment by bmoscon** [comment]
https://blog.kraken.com/post/259/introducing-the-kraken-dark-pool/

the .d pairs could just as easily be ignored, which would probably be easier to make sense of since the darkpool orders are hidden from the rest of the market.

**Comment by bmoscon** [comment]
i've committed a fix for this, so closing
