### ISSUE TITLE
dropped messages

### ISSUE THREAD

**Issue by rjbks** [bmoscon/cryptofeed#20]
What about dropped messages?  GDAX mentions:

> While a websocket connection is over TCP, the websocket servers receive market data in a manner which can result in dropped messages. Your feed consumer should either be designed to expect and handle sequence gaps and out-of-order messages, or use channels that guarantee delivery of messages.

Certain other exchanges make similar warnings about out of order/dropped messages, although I cannot currently recall which ones exactly.

The `message_handler` currently only checks if `msg_seq < last_seen_seq`. Unless I am missing something, it would seem this can result in an inaccurate order book if `msg_seq > last_seen_seq + 1`. The simple solution here is to call `_book_snapshot` upon detecting this. 

So in message_handler:

                last_seen_seq = self.seq_no[msg['product_id']]
                msg_seq = msg['sequence']
                if msg_seq < last_seen_seq:
                    # out of order message, ignore
                    return
                elif msg_seq > (last_seen_seq + 1):
                    LOG.warning(
                        'Missing messages for {} (Last seq: {}, received seq: {}). Requesting new snapshot'.format(
                            msg['product_id'],
                            last_seen_seq,
                            msg_seq
                        )
                    )
                    await self._book_snapshot()  # rebuild book after missing msg detected
                    return

This may also have to be considered in the case of dropped connections which result in missed messages, as referenced in #16 .

**Comment by bmoscon** [comment]
fixed - thanks for opening the issue!

**Comment by rjbks** [comment]
Thanks for the quick response
