### ISSUE TITLE
Add funding for Huobi

### ISSUE THREAD

**Issue by AnnimouseCryptoUser** [bmoscon/cryptofeed#200]
The addition of capturing FTX, Huobi, and Okex funding rates would be great and functional in cryptostore

**Comment by bmoscon** [comment]
okcoin/okex already have funding data, FTX doesn't support funding data via websocket. Huboi looks like it does support funding data on its derivates exchange, but it looks like it requires a new websocket endpoint for this data type.

**Comment by Quenos** [comment]
You're right that funding is not supported via websocket for FTX, but in your intro you write that REST is used when ws is not available ;)

**Comment by bmoscon** [comment]
Sure anything can be supported - feel free to open a PR

**Comment by bmoscon** [comment]
FTX funding now supported!

**Comment by bmoscon** [comment]
Need to add support for Huobi, then can close this

**Comment by bmoscon** [comment]
done
