### ISSUE TITLE
Add receive timestamp

### ISSUE THREAD

**Issue by quazzuk** [bmoscon/cryptofeed#208]
Hi

Would it be possible to add a config option so that all ticks are timestamped on arrival or perhaps there is an alternative method for joining different feeds (posthoc) in order of arrival?

Thanks
A

**Comment by bmoscon** [comment]
@quazzuk so to be clear - you want the exchange timestamp and the receipt timestamp from cryptofeed? This data is already recorded, just not always reported.

**Comment by quazzuk** [comment]
@bmoscon - correct. I would like to be able to reassemble a feed for a given pair, across different exchanges, in order of arrival at my machine.

**Comment by xiandong79** [comment]
Yes,

the interval between "exchange timestamp" (if we have) and "receive  timestamp on local machine"
is valuable for design stratgies.

**Comment by xiandong79** [comment]
both for cryptofeed and cryptostore

**Comment by bmoscon** [comment]
I'm in the process of implementing this. Its not hard to add - I was already saving the timestamp but every single callback, backend, example and exchange piece of code needs to change, so probably like 80% of the files are changing. It wont be a lot of changes per file, but a lot of re-testing. I've done 2 of the exchanges so far, you can follow the progress on the timestamps branch, or just wait for it to be merged

**Comment by joelrich** [comment]
In case there is no server timestamp for a certain channel (e.g. for tickers or order books), it would be helpful if you could store the last server timestamp from any other channel of the same connection in a separate field. But maybe this is also overkill.

**Comment by bmoscon** [comment]
PR open - pleae review! https://github.com/bmoscon/cryptofeed/pull/216

**Comment by bmoscon** [comment]
merged
