### ISSUE TITLE
L3 messages feed and storage

### ISSUE THREAD

**Issue by rjbks** [bmoscon/cryptofeed#21]
If I was looking to store L3 book data (let's assume with Arctic), wouldn't it be more efficient to create and store a stream of standardized delta messages as opposed to the entire book?

I only ask because the book callback takes `feed`, `pair` and `book` as the inputs. Using that callback for book updates would not provide any information about the updates themselves. I guess a user can just define a custom callback for this, but I figured it would make more sense to just have the BookCallback do this if it was meant to be called for book updates as mentioned in the docs. Many exchanges provide multiple updates per second which would result in the entire book being passed around as opposed to just the changed items.

Also, if that change does make sense, then as pointed out in my other recently opened issue regarding dropped messages (#20), we would have to generate the missing messages by diffing our current order book with a fresh snapshot.

**Comment by rjbks** [comment]
Is this a direction you would like to pursue or would it be outside of the scope of this project? If so, we could discuss what you'd like to see and I could make a PR with whatever changes we come up with.

**Comment by bmoscon** [comment]
Yes, its something I'd add.  I'm happy to accept a PR, and I'm happy to do it myself. Should only take an hour or so to write up, but I don't think I'd get to it until next weekend. If you want to do it before then, I like PRs :)

**Comment by bmoscon** [comment]
@rjbks was going to do this sometime this week/weekend - unless you tell me you've already started on something for a PR

**Comment by rjbks** [comment]
Yes, I am just putting together some tests. I'll have it done by tomorrow.

**Comment by bmoscon** [comment]
👍 no rush - I just wanted to check with you before i duplicated something you were taking care of

**Comment by rjbks** [comment]
I will probably need the weekend. Sorry for the holdup
