### ISSUE TITLE
Feed Request - Upbit (Korean Exchange)

### ISSUE THREAD

**Issue by heartcored98** [bmoscon/cryptofeed#214]
Hi, I am really enjoying the cryptofeed library. 

However, I hope cryptofeed could support Upbit Exchange which is one of the largest exchange in the South Korea.

Here is the API doc [link](https://docs.upbit.com/docs/upbit-quotation-websocket). 

However, I am afraid documentation is only written in Korean. So I might implement Upbid feed myself as soon as possible.

**Comment by bmoscon** [comment]
I'll definitely take a PR. Google translate seemed to translate the document just fine, so I could do it eventually. There is some documentation about adding a feed:

https://github.com/bmoscon/cryptofeed/blob/master/docs/exchange.md

its a little bit out of date, but not too much

**Comment by bmoscon** [comment]
this was merged, so closing
