### ISSUE TITLE
support funding for OKEX

### ISSUE THREAD

**Issue by edwardsun** [bmoscon/cryptofeed#219]
Hi,

Thanks a lot for this nice tool.
I was trying to get funding information from OKEX but it seems the current feed does not support this functionality. 
![image](https://user-images.githubusercontent.com/359830/76694746-c9da6880-66b1-11ea-8f4d-97a1331924a8.png)

Would be great to have it.
Thanks!

**Comment by bmoscon** [comment]
merged

**Comment by edwardsun** [comment]
Hi,
I pulled the latest version but still encounter this issue.

![image](https://user-images.githubusercontent.com/359830/76702690-32214e00-66a2-11ea-971d-e7642c9ea9d4.png)

**Comment by vdbelt** [comment]
There is no release tagged yet. Did you install the latest version directly from github?

**Comment by edwardsun** [comment]
> There is no release tagged yet. Did you install the latest version directly from github?

Hi,
I just pip3 install cryptofeed. As you mentioned, I guess new changes are not in effect yet.
Sorry about the confusion.
Look forward to the update.

Thanks.

**Comment by cheekybastard** [comment]
@edwardsun 

You can use pip to install cryptofeed direct from github, then it will have the latest commits/changes:

`pip install --no-cache-dir https://github.com/bmoscon/cryptofeed/zipball/master`
