### ISSUE TITLE
demo.py not working

### ISSUE THREAD

**Issue by edwardsun** [bmoscon/cryptofeed#222]
Showing lost of error messages like this:

TypeError: trade() missing 1 required positional argument: 'receipt_timestamp'

TypeError: book() missing 1 required positional argument: 'receipt_timestamp'

etc.

**Comment by cheekybastard** [comment]
You likely have the latest pypi package, which doesn't have the latest github commits.

pip install --no-cache-dir https://github.com/bmoscon/cryptofeed/zipball/master

**Comment by edwardsun** [comment]
Thanks! Solved.
