### ISSUE TITLE
[Feature request] support to subscribe to authenticated channels

### ISSUE THREAD

**Issue by caizhiwei** [bmoscon/cryptofeed#225]
Most advanced  exchange provide subscription to authenticated channels, such as [huobi dm](https://docs.bitfinex.com/reference#ws-auth-trades )and and [bitfinex](https://docs.huobigroup.com/docs/dm/v1/en/#subscribe-order-data-sub). I think it's useful for most trader, especially the subscription to private trade update. If you think this should not be a part of this project, is it possible to leave a common interface for user to send subscriptions data and handle receiving data themselves?

**Comment by bmoscon** [comment]
@caizhiwei I'm fine having it as part of it, but as a US resident I can't get an account on the majority of exchanges you'd want support on, so someone else will have to develop and test this (and then open a PR). There are a few I can look into starting with, but it wouldn't be any of those you listed.

**Comment by caizhiwei** [comment]
Hi, bmoscon. It would be great with your help. I can also help develop these interfaces for some exchanges, but I think maybe it's better and easier after you design and implement one exchange as example.

**Comment by PyPatel** [comment]
I have been trying this on different exchanges using **Websockets** but I am facing this issue. I feel working on authentication for websockets is tougher than with websocket (also author of Websockets does not support use of package for cryptocurrencies for environmental reasons)

https://github.com/aaugustin/websockets/issues/775 

If @bmoscon or any one else can help me with this, I can port whole OMS on top of cryptofeed.

**Comment by bmoscon** [comment]
I've started seriously working on this, hope to have a few exchanges implemented by end of the year

**Comment by zfsamzfsam** [comment]
ftx-recorder
	https://github.com/evanatyourservice/ftx-recorder
	record trades, orders, and account activity from FTX Exchange to influxdb (for viewing in a grafana dashboard)

**Comment by bmoscon** [comment]
This is supported now - currently Gemini supports authenticated data channels. The base support is now available, so other exchanges can be added. I cannot get accounts for most the exchanges due to the fact I'm a US citizen, so support for many popular exchanges will need to be added by others
