### ISSUE TITLE
Change json library to yapic for performance

### ISSUE THREAD

**Issue by vincentmele** [bmoscon/cryptofeed#231]
I have to say, thank you for making this easy. I dumped raw json data using examples/demo_raw_data.py, and then used it in the test below. The results show yapic is about 1.3x to 2.0x the speed of the standard library for parsing l2_book, ticker, and trades data from 100 MB files from Binance and Deribit feeds.

Based on these results, I am going to proceed with integrating yapic for further stability testing.

```
binance results
file lines: 211316
yapic: 13.38 seconds
json: 23.62 seconds
yapic lps: 47390.76 lines per second
json lps: 26838.02 lines per seond
json/yapic: 1.77x

deribit results
file lines: 310000
yapic: 18.85 seconds
json: 37.63 seconds
yapic lps: 49332.11 lines per second
json lps: 24717.06 lines per seond
json/yapic: 2.00x

```

```
import joblib
import timeit

iterations = 3
files =  { 'binance' : 'BINANCE12f2ac65-b5c5-404d-b8b4-8f22c04da3a4.0',
           'deribit' : 'DERIBIT252a6e79-7a32-4038-a64a-b1f7b29d6837.3' }

def load_file(filepath):
  output = []
  with open(filepath) as fp:
    line = fp.readline()
    while line:
      output.append(line.split(' ')[1])
      line = fp.readline()
  joblib.dump(output, 'json.pkl')
  return len(output)

for k, f in files.items():
  length = load_file(f)
  yapic_time = timeit.timeit('[json.loads(msg,parse_float=Decimal) for msg in txt]',setup="from yapic import json; import joblib; from decimal import Decimal; txt = joblib.load('json.pkl')", number=iterations)
  yapic_lps = length * iterations / yapic_time

  json_time = timeit.timeit('[json.loads(msg,parse_float=Decimal) for msg in txt]',setup="import json; import joblib; from decimal import Decimal; txt = joblib.load('json.pkl')", number=iterations)
  json_lps = length * iterations / json_time

  ratio = json_time / yapic_time

  print(f'{k} results')
  print(f'file lines: {length}')
  print(f'yapic: {yapic_time:.2f} seconds')
  print(f'json: {json_time:.2f} seconds')
  print(f'yapic lps: {yapic_lps:.2f} lines per second')
  print(f'json lps: {json_lps:.2f} lines per seond')
  print(f'json/yapic: {ratio:.2f}x')

```

_Originally posted by @vincentmele in https://github.com/bmoscon/cryptofeed/pull/230#issuecomment-610076287_

**Comment by vincentmele** [comment]
Changes made here: https://github.com/vincentmele/cryptofeed/commit/5a26aa67a28cf1a9406cb087d0d932f3f23b45ea

example/demo.py runs successfully without exceptions. For the exchanges that required zlib decompression, it was required to explictly decode the bytestrings to strings before passing them to json.loads().

**Comment by bmoscon** [comment]
@vincentmele looks good. Feel free to open a PR. It looks like it will soon support native bytestring decoding so you wont need to explicitly do this:

https://github.com/zozzz/yapic.json/issues/2

**Comment by bmoscon** [comment]
merged
