### ISSUE TITLE
[Feature request] Grouping for Orderbooks

### ISSUE THREAD

**Issue by pavs94** [bmoscon/cryptofeed#243]
Request to add feature to group orderbooks similar to the exchanges like Bitmex, Binance, etc.

**Comment by bmoscon** [comment]
@pavs94 going to need more information than that. "grouping for orderbooks" doesnt mean anything to me, so please elaborate.

**Comment by pavs94** [comment]
![image](https://user-images.githubusercontent.com/10599184/81500697-86872980-92f1-11ea-9cf4-e617990d7980.png)
![Screenshot 2020-05-10 at 7 08 00 PM](https://user-images.githubusercontent.com/10599184/81500708-97379f80-92f1-11ea-853a-716f1fe57753.png)

Please check attached screenshots from bitmex and binance futures. The grouping features in not available on the websocket or APIs of Bitmex by default, as far as I know. Working with orderbookL2 of Bitmex especially grouping the prices is tricky to handle. Hence, I feel this feature will be useful to many.

**Comment by cheekybastard** [comment]
@pavs94 You can use pandas library for summary stats like that,  with cryptofeed CustomAggregate.

https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_custom_agg.py

Rough 1st draft example pandas code on 1,000 rows of test data takes about 30ms on an old i7 cpu. Using pandas cut (segments values into bins) inside groupby aggregations. Maybe casting decimal/float to int when constructing the bin/label lists is an issue for the groupby, all data might not be included in the aggregation because of conversion rounding up/down. Don't have time to check at the moment.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html

https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html
 
```
import pandas as pd
pd.set_option('display.max_rows', None)

test_data = [{"timestamp": 1584847218.598885, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6256.8, "ask": 6257.2},
{"timestamp": 1584847218.5992637, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6266.8, "ask": 6267.2},
{"timestamp": 1584847218.5995693, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6276.8, "ask": 6277.2},
{"timestamp": 1584847218.5999515, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6286.8, "ask": 6287.2},
{"timestamp": 1584847218.6002553, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6296.8, "ask": 6297.2},
{"timestamp": 1584847218.6005516, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6230.8, "ask": 6230.2},
{"timestamp": 1584847218.598885, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6256.8, "ask": 6257.2},
{"timestamp": 1584847218.5992637, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6266.8, "ask": 6267.2},
{"timestamp": 1584847218.5995693, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6276.8, "ask": 6277.2},
{"timestamp": 1584847218.5999515, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6286.8, "ask": 6287.2},
{"timestamp": 1584847218.6002553, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6296.8, "ask": 6297.2},
{"timestamp": 1584847218.6005516, "exchange": "BITFINEX", "pair": "BTC-USD", "bid": 6230.8, "ask": 6230.2},]

def groups(data, group_spread):
    df = pd.DataFrame(data)
    bid_min, bid_max, ask_min, ask_max = int(df['bid'].min()), int(df['bid'].max()), int(df['ask'].min()), int(df['ask'].max())
    bid_bins, ask_bins = [-1], [-1]
    bid_bins += list(range(bid_min, bid_max, group_spread))
    bid_labels = list(map(str, bid_bins[1:]))
    ask_bins += list(range(ask_min, ask_max, group_spread))
    ask_labels = list(map(str, ask_bins[1:]))
    bid = df.groupby(pd.cut(df['bid'], bins=bid_bins, labels=bid_labels)).agg(count=('bid', 'count'), sum=('bid', 'sum'))
    ask = df.groupby(pd.cut(df['ask'], bins=ask_bins, labels=ask_labels)).agg(count=('ask', 'count'), sum=('ask', 'sum'))
    print('### Bid ###')
    print(bid[bid['count'] > 0])
    print('### Ask ###')
    print(ask[ask['count'] > 0])

groups(test_data, 5)
```

**Comment by bmoscon** [comment]
If someone wants to put in some custom aggregation callback, I'll take the PR, but this functionality seems better suited to something done during analysis or in a front end tool, like the example shows.
