### ISSUE TITLE
How to get Kibana to recognize timestamp? - demo_elastic.py 

### ISSUE THREAD

**Issue by brizzbane** [bmoscon/cryptofeed#245]
Using the demo in the examples, Kibana does not recognize the time field as a timestamp.  Do I need to change how it is indexed?  Or do I need to create mappings before starting the demo_elastic.py?

Any help or direction would be much appreciated!

(This is an amazing project btw!)

Thank you!

**Comment by bmoscon** [comment]
I've never used kibana, so I couldn't say. I'm also not a big elasticsearch user either, so its definitely possible that the timestamp field needs to be tweaked. If you let me know what kibana expects and what you're seeing in elastic, I can take a look. Also - what version of elastic are you using? 7.X ?

**Comment by brizzbane** [comment]
Yea...using latest version of Elasticsearch.  Kibana just sees it as a number.  I'm not sure why it doesn't recognize as timestamp.  I'm not super familiar with Elasticsearch...I've used it years ago, and really liked the Kibana interface to explore and represent the data..

I thought you might know right off the bat what the issue was :\.

I do know from past experience--the actual python datetime module would be recognized (at least using this: https://github.com/elastic/elasticsearch-dsl-py).

Here:

https://github.com/elastic/elasticsearch-dsl-py/blob/e881fc1506dcce6a1f07eea2c5d8a9956b3b925a/elasticsearch_dsl/field.py

They define a "Date" class.  Would you be able to tell (easily) from that what Kibana is expecting?

**Comment by brizzbane** [comment]
Yea...I tried creating a template in Kibana before index started receiving data, but once script starts running, it gives an error saying:

> aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://localhost:9200/trades/trades')
> 2020-06-07 20:58:47,783 : ERROR : POST to http://localhost:9200/trades/trades failed: 400 - {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [trades] as the final mapping would have more than 1 type: [_doc, trades]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [trades] as the final mapping would have more than 1 type: [_doc, trades]"},"status":400}
> 

don't know enough to know where to go next..

**Comment by brizzbane** [comment]
May have made some progress!  I got 'book' to work using index template.  So maybe that is what needs to be done to have timestamps recognized as timestamps?  I don't know..  It seems to be working though.

**Comment by bmoscon** [comment]
@brizzbane i'm going to create a branch with a change to return the timestamps in timestamp format. Can you test that branch out with kibana?

**Comment by brizzbane** [comment]
Sure

**Comment by bmoscon** [comment]
I'll ping you here when I have the branch ready. Crypotfeed is just a library - you have to write the code to use it in an application. Cryptostore is an application that uses cryptofeed. Its a data collection application. You supply a config indicating what you want to store and where, and it does the rest

**Comment by bmoscon** [comment]
@brizzbane ok, the branch is named "datetime". The elastic search documentation indicates that elastic will natively store timestamps in ms since epoch, cryptofeed was returning sec since epoch, so I think this might fix it. let me know

**Comment by brizzbane** [comment]
Deleted all indexes and index patterns that I had in Elasticsearch, and Kibana.  did git checkout datetime, and ran demo_elastic.py.

When going to create index pattern for Kibana, it still said:

> The indices which match this index pattern don't contain any time fields.

Tried it for all indexes created by the demo_elastic.py: book, funding, trades

Proceeding with creating the index pattern timestamp, and receipt_timestamp show up as 'number'.

Let me know if there is anymore info that I can provide that may be helpful :\.  Thank you .. !

**Comment by bmoscon** [comment]
ok, let me try sending the timestamps as a string and see if that does the trick or not

**Comment by bmoscon** [comment]
@brizzbane - ok - branch updated. Let me know if this does the trick!

**Comment by brizzbane** [comment]
I actually tried string before creating this ticket... but I'll give it another go.

**Comment by brizzbane** [comment]
Seems to be working!

The timestamps though, I'm wondering why they are what they are.  Right now it is showing 14:09.  Local time is 6:10.  UTC would be 22:00?

Thanks for fixing this.  I was kind of surprised that ended up working.

**Comment by bmoscon** [comment]
Seems like it didnt work. What was the data type? Something realtime like trades or book should have a correct/current timestamp. Other things like funding may be weird times as they come from the exchanges. Was the receipt timestamp incorrect as well? Only thing i can think of is that its not recognizing the timestamp as utc and applying some timezone to it. I'm going to try one tweak to see if it fixes it

**Comment by bmoscon** [comment]
I updated the branch @brizzbane

**Comment by brizzbane** [comment]
You said 'Seems like it didn't work'..  ..What do you mean?

It is indexing the correct time.  What is weird is in Kibana I can set to 'UTC'--and it does show the correct indexing time, but then 'last 15 minutes' doesn't work. ...So I think Kibana not showing correct times is a Kibana issue.  I'll debug and try and figure it out.

What changes did you make?  Sorry if you misunderstood what I said--but it DOES seem to be working, in that Kibana recognizes the time fields as time.

**Comment by brizzbane** [comment]
Ugh.  Really frustrating.. have no idea why Kibana wouldn't just have a setting to not mess w/time of documents indexed.

**Comment by brizzbane** [comment]
Wondering if maybe this is what is going on?  From https://discuss.elastic.co/t/kibana-show-wrong-time-compared-to-the-time-value-indexed-in-elasticsearch/43992/3:

> Are the dates you're storing in UTC or some other time zone? Elasticsearch automatically converts dates into UTC, so if your dates are in a different timezone and you're not specifying that timezone alongside the date data, Elasticsearch is going to assume the date you're giving it is UTC. When reading that date, Kibana will assume the date is UTC and do the timezone conversion to GMT+8 which would explain why it's showing the original time + 8 hours

**Comment by brizzbane** [comment]
@bmoscon 
Think I found a solution.  I've tested, and it seems to be working.  I'm not sure what would be the 'best' coding practices to implement, but let me know what you think?

from:
https://www.artificialworlds.net/blog/2017/06/09/python-printing-utc-dates-in-iso8601-format-with-time-zone/

```
from datetime import timezone
data['timestamp'] = f"{dt.fromtimestamp(data['timestamp'], tz=timezone.utc).isoformat()}Z"
```

This has Kibana working correctly, and previous post that I made suggesting that this might be the problem, seems to be right.

**Comment by bmoscon** [comment]
@brizzbane that was the last change I made, did you re-test with that change, because I already made it:

https://github.com/bmoscon/cryptofeed/commit/b06af688802fbccb2cb93ecdf66c92295f0ee2be

**Comment by brizzbane** [comment]
Yea I re-tested... it does not include timezone though--which is why I had issues with it being a few hours off.

I don't see tz=tzinfo in the changes?...

**Comment by bmoscon** [comment]
ah I see - I added that to the branch, please try again. Also, does the timestamp come out correct in elastic? Does it recognize the field as a timestamp or does it think its a string? @brizzbane

**Comment by brizzbane** [comment]
Yep it is working.  Timestamp (and receipt_timestamp) are both of type 'date'.

Thank you for figuring this out!

**Comment by bmoscon** [comment]
merged to master, closing this. thanks for the help!
