### ISSUE TITLE
Can you add additional liquidation feed?

### ISSUE THREAD

**Issue by brizzbane** [bmoscon/cryptofeed#252]
Looking at standards.py, it looks like Bitmex is the only liquidation feed?

```
    LIQUIDATIONS: {
        BITMEX: 'liquidation'
    }
```

There is another project that I've been watching (that is also pretty awesome IMHO), [SignificantTrades](https://github.com/Tucsky/SignificantTrades)..  I'm particularly interested in Binance (in this case Binance Futures) at this time, because that is where I have funds.  So...I guess that is why I am aware of this.

The project here:
> line 82 of:
> https://github.com/Tucsky/SignificantTrades/blob/master/src/exchanges/binance-futures.js

The stream is 'forceOrder'.  Documentation here:

> https://binance-docs.github.io/apidocs/futures/en/#liquidation-order-streams

Looking at the docs, it looks like they also have a feed for all liquidations regardless of the pair.  I kind of would be curious to collect and look at this and see what is going on..  Don't know if it would 'fit in' w/how things are setup now though?

**Comment by bmoscon** [comment]
yes, it would be pretty easy to add, but currently liquidations are not supported on the backends, so it would have to be added there (thats the large task). I can do it in the next week or so

**Comment by bmoscon** [comment]
Need to:
- Add Liquidations to Binance
- Add backend for liquidations

**Comment by bmoscon** [comment]
@brizzbane currently working on this. should have some of the backends working by tomorrow. will focus on redis and kafka first, then do the rest as i have time. Is there a specific backend that you want to use, or did you just want the liquidation feed (the feed is there, just not a backend).

**Comment by brizzbane** [comment]
I'm familiar with Elasticsearch, so like using that (mainly because of Kibana).

Thank you!

**Comment by bmoscon** [comment]
@brizzbane ok, its been added to elasticsearch. The backend callback is LiquidationsElastic. Let me know how it works for you. You can close this or respond back if there are issues.

**Comment by brizzbane** [comment]
I'll close--and re-open if there are any problems.

Thanks so much!
