### ISSUE TITLE
Understanding content of order and trade

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#254]
Hello,
I have rather general questions, but I think others can have the same, so I write this in a ticket instead of using slack.
Order and trade structures are defined in 
https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/defines.py

Order has most notably these fields:
```python
    {
        order_id: str,
        side: str,                      # bids or ask
        order_type: str,           # limit/market/etc,
        price: Decimal,
        total: Decimal,
        executed: Decimal,
        pending: Decimal,
        order_status: str             #FILLED/PARTIAL/CANCELLED/OPEN
    }
```
Please, can you confirm 'pending' is only for limit orders?

Also, assuming there is one market order, bigger than the 1st available limit order in the order book.
In the order structure, there is a field for a single price.

How is it then materialized in this order structure? Will there be as many orders as the market order needs to be sliced to get fully filled?

Also, trade has following structure:
```python
{
    'price': Decimal,
    'amount': Decimal,
    'timestamp': float,
    'side': str
    'fee_currency': str,
    'fee_amount': Decimal,
    'trade_id': str,
    'order_id': str
    }
```

So for one market order, does it create as many `trade`s and `order`s as required to get it filled ?

On the opposite, for a limit order, only one `order` is created and no `trade`?

Am I right in this understanding?

Thanks a lot for your reply.
Have a good day,
Bests,

**Comment by bmoscon** [comment]
those are exchange specific, so its going to depend on the exchange

**Comment by yohplala** [comment]
ok, let's take Binance as example?
May I find an example somewhere of how a market order would be translated into `order` and `trade`?
Thanks for your help!

**Comment by bmoscon** [comment]
Docs are here https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#account-endpoints

As a us citizen I can't trade on the exchange so I have no way of testing it out myself to verify

**Comment by yohplala** [comment]
Thanks a lot for your help Bryan, I appreciate.
I could see that for a market order, the 'fill' is split in different price levels. Thanks!

```python
  "type": "MARKET",
  "side": "SELL",
  "fills": [
    {
      "price": "4000.00000000",
      "qty": "1.00000000",
      "commission": "4.00000000",
      "commissionAsset": "USDT"
    },
    {
      "price": "3999.00000000",
      "qty": "5.00000000",
      "commission": "19.99500000",
      "commissionAsset": "USDT"
    },
}
