### ISSUE TITLE
HuobiSwap fails to initialize

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#257]
Latest code. Error:
```
    fh.add_feed(exchange, max_depth=max_depth, book_interval=book_interval, config=channel_pairs, callbacks=callbacks, cross_check=True)
  File "src/cryptofeed/cryptofeed/feedhandler.py", line 107, in add_feed
    self.feeds.append(_EXCHANGES[feed](**kwargs))
  File "src/cryptofeed/cryptofeed/exchange/huobi_swap.py", line 15, in __init__
    Feed.__init__(self, 'wss://api.hbdm.com/swap-ws', pairs=pairs, channels=channels, callbacks=callbacks, config=config, **kwargs)
  File "src/cryptofeed/cryptofeed/feed.py", line 35, in __init__
    load_exchange_pair_mapping(self.id)
  File "src/cryptofeed/cryptofeed/standards.py", line 34, in load_exchange_pair_mapping
    mapping = gen_pairs(exchange)
  File "src/cryptofeed/cryptofeed/pairs.py", line 24, in gen_pairs
    return _exchange_function_map[exchange]()
KeyError: 'HUOBI_SWAP'
```

Reason is that `HUOBI_SWAP` is missing in `_exchange_function_map`. Also, at least in my opinion, it's wrong to include the swap symbols in `huobi_dm_pairs`. They should be separated since there are two separate exchange classes.

@caizhiwei, will you take care of this?

**Comment by bmoscon** [comment]
@joelrich I'll take a look at this

**Comment by olibre** [comment]
Hi @bmoscon 
I am currently improving / fixing the HUOBI_SWAP code of Cryptofeed and I will send you soon a Pull Request :smile:

**Comment by olibre** [comment]
This is my *work in progress* code being tested...

**Comment by olibre** [comment]
From my side, I think the Pull Request #262 is OK to be merged despite HUOBI_SWAP is not currently publishing market data...

**Comment by olibre** [comment]
I only forgot to add `channels=[TRADES, L2_BOOK]` in `Feedhandler.add_feed()` to test `HUOBI_SWAP`.
On my side, I have validated the code change of pull request #262.

**Comment by bmoscon** [comment]
thanks for fixing this @olibre
