### ISSUE TITLE
FTX funding Key Error

### ISSUE THREAD

**Issue by briancp37** [bmoscon/cryptofeed#261]
Running the example code below, I get a Key error.
async def funding(**kwargs):
    print(f"Funding Update for {kwargs['feed']}")
    print(kwargs)

def main():
    f = FeedHandler()
    f.add_feed(FTX(pairs=['BTC-PERP', 'THETA-PERP'], channels=[FUNDING], callbacks={FUNDING: FundingCallback(funding)}))
    f.run()

if __name__ == '__main__':
    main()

ERROR BELOW
`File "/cryptofeed/standards.py", line 290, in feed_to_exchange
ret = _feed_to_exchange_map[feed][exchange]
KeyError: 'FTX'`

**Comment by bmoscon** [comment]
Thanks for submitting this issue, I'll take a look at this soon

**Comment by bmoscon** [comment]
I'm guessing you're using an older version of the software. Using the latest version from github, I have no issues with the above:


Funding Update for FTX
{'feed': 'FTX', 'pair': 'BTC-PERP', 'rate': Decimal('0.000009'), 'timestamp': 1596240000.0}
Funding Update for FTX
{'feed': 'FTX', 'pair': 'THETA-PERP', 'rate': Decimal('0.000059'), 'timestamp': 1596240000.0}

**Comment by bmoscon** [comment]
I'm going to close this - make sure you are on the latest version from github. If the issue persists, please re-open
