### ISSUE TITLE
timestamp for bitmex trade data

### ISSUE THREAD

**Issue by halida** [bmoscon/cryptofeed#27]
Hi, it looks like the trade data for bitmex contains timestamp:

https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/bitmex/bitmex.py#L65

Can you explain why it's not send to the callback? Thanks.

**Comment by bmoscon** [comment]
no reason, just havent done the work yet. I can do it sometime this month, or you can submit a PR if you are so inclined.

**Comment by bmoscon** [comment]
fixed
