### ISSUE TITLE
Bitfinex Channel limit

### ISSUE THREAD

**Issue by bmoscon** [bmoscon/cryptofeed#279]
Bitfinex allows only 25 channels per connection - this means if you want to subscribe to 26 symbols for trade data -> you get an error. If you want 15 symbols for trades and book data -> error. The only solution is to create multiple websocket connections and to split the data requests among them. No functionality exists to do this currently, so will need a new solution to handle this

**Comment by yohplala** [comment]
Hi Bryant,
Binance has the same kind of limitation, between 230 & 235 streams (a stream: pair + channel).
Might be worth to see if such a feature can be 'generic'.
Bests,
Pierre

**Comment by bmoscon** [comment]
fixed now that each exchange can create more than 1 connection :D
