### ISSUE TITLE
Coinbase L3 feed with many pairs encounters errors on connection due to hitting REST API rate limit for orderbook snapshots

### ISSUE THREAD

**Issue by zanoo** [bmoscon/cryptofeed#293]
**Describe the bug**
When starting a Coinbase L3_BOOK feed for several pairs (somewhere greater than 10 pairs; seems to be vary between 12-20 in my testing), the full book snapshot REST API requests generated by Cryptofeed to initialize the L3 book trigger a rate limit. This occurs because the requests in `_book_snapshot()` in coinbase.py are made without regard for the REST API rate limit.

**To Reproduce**
Run this code:
```
from cryptofeed import FeedHandler
from cryptofeed.callback import BookCallback
from cryptofeed.defines import L3_BOOK
from cryptofeed.exchanges import Coinbase
from cryptofeed.util.async_file import AsyncFileCallback

PAIRS = ["BTC-USD","ETH-USD","LINK-USD","XRP-USD","BTC-EUR","LTC-USD","ETH-EUR","ETH-BTC","LINK-ETH","BCH-USD","BTC-GBP","ETH-GBP","LINK-EUR","BTC-USDC","ETH-USDC","LTC-BTC","LINK-GBP","LTC-EUR","XRP-BTC","XRP-EUR","BCH-BTC","BCH-EUR","ETH-DAI","XRP-GBP","LTC-GBP","BCH-GBP"]

async def l3book(feed: str, pair: str, delta: dict, timestamp: float, receipt_timestamp: float):
    print(f"==L3BOOK== Pair: {pair}; Timestamp {timestamp}")

def main():
    f = FeedHandler(raw_message_capture=AsyncFileCallback('./'), handler_enabled=True, log_messages_on_error=True)
    f.add_feed(Coinbase(pairs=PAIRS, channels=[L3_BOOK], callbacks={ L3_BOOK: BookCallback(l3book) }))
    f.run()
```
Get the following traceback:
```
==L3BOOK== Pair: BTC-USD; Timestamp: 1598904207.7325823                                                                                           
==L3BOOK== Pair: ETH-USD; Timestamp: 1598904207.7325823
==L3BOOK== Pair: LINK-USD; Timestamp: 1598904207.7325823
==L3BOOK== Pair: XRP-USD; Timestamp: 1598904207.7325823
==L3BOOK== Pair: BTC-EUR; Timestamp: 1598904207.7325823
==L3BOOK== Pair: LTC-USD; Timestamp: 1598904207.7325823
==L3BOOK== Pair: ETH-EUR; Timestamp: 1598904207.7325823
==L3BOOK== Pair: ETH-BTC; Timestamp: 1598904207.7325823
==L3BOOK== Pair: BCH-USD; Timestamp: 1598904207.7325823
==L3BOOK== Pair: LINK-ETH; Timestamp: 1598904207.7325823
==L3BOOK== Pair: BTC-GBP; Timestamp: 1598904207.7325823
==L3BOOK== Pair: ETH-GBP; Timestamp: 1598904207.7325823
==L3BOOK== Pair: LINK-EUR; Timestamp: 1598904207.7325823
==L3BOOK== Pair: BTC-USDC; Timestamp: 1598904207.7325823
==L3BOOK== Pair: ETH-USDC; Timestamp: 1598904207.7325823
==L3BOOK== Pair: LTC-BTC; Timestamp: 1598904207.7325823
2020-08-31 20:03:29,308 : ERROR : COINBASE: encountered an exception, reconnecting
Traceback (most recent call last):
  File "../../cryptofeed/feedhandler.py", line 229, in _connect
    await feed.subscribe(websocket)
  File "../../cryptofeed/exchange/coinbase.py", line 419, in subscribe
    await self._book_snapshot(self.pairs or self.book_pairs)
  File "../../cryptofeed/exchange/coinbase.py", line 186, in _book_snapshot
    self.seq_no[npair] = orders['sequence']
KeyError: 'sequence'
```
Upon debugging, I found that this KeyError occurs because the message received and put into the `orders` object is actually a rate limit error message, i.e. `{'message': 'Public rate limit exceeded'}`. Note that despite `log_message_on_error` being set to True, this message is not stored in the log, as it occurs during `subscribe()`, and therefore does not encounter the message logging code in feedhandler.py's  `_handler()`, which logs messages.

**Expected behavior**
Three things should be done here:

1. Handle (rate limit and other) error messages in the `_book_snapshot()` function. That is, retry the request for the current pair if an error is encountered. Log messages on errors in `_book_snapshot()`.
2. Time order book snapshot requests to the REST API so that they don't occur frequently enough to cause Cryptofeed to hit Coinbase's rate limit.
3. Review the possibility of this scenario occurring for other exchanges, and make sure the expected message logging on errors is in place for them. I'll make a separate issue for this later on--it only affects users capturing large numbers of pairs, so it's probably less important than other current issues.

**Operating System:**
 Ubuntu Server 20.04

**Cryptofeed Version**
1.6.0

**Fix**
The fix is pretty easy, I think, and only needs to change `_book_snapshot()`. First, we can modify the request loop to retry a pair on errors. For avoiding hitting the rate limit, we can throttle the requests. The rate limit is currently 3 requests per second, or 6 per second in bursts, according to [the API docs section on rate limits](https://docs.pro.coinbase.com/#rate-limits). So, the code should be modified to wait some amount of time whenever some number of requests have been made, e.g. asynchronously sleep 1 second every 5 requests. Of course, this solution isn't optimal, and better solutions are easy to imagine (e.g. using a Coinbase Rest object to perform these requests instead, and coding up a new RateLimiter or Throttler class for use in the Rest object), but this will fix the bug in the meantime.

I'll make a PR fixing this sometime this week.

**Comment by bmoscon** [comment]
@zanoo thanks for filing this - should be easy to fix - i know what their limits are, just need to put in some sleeps

**Comment by zanoo** [comment]
Sorry, I got rather busy this week (and will be for the next few months). I might have time to fix it this weekend, but I'm not completely sure.

**Comment by bmoscon** [comment]
fixed

**Comment by zanoo** [comment]
Thanks!
