### ISSUE TITLE
Custom Mongo Callback feature

### ISSUE THREAD

**Issue by abvashis** [bmoscon/cryptofeed#296]
Hello,
Thanks a lot for the great efforts you put on this amazing project. It's proving very helpful to us.
However, my requirement is to extend the feature to use private websocket streams as well, i.e. I need to call streams which requires authentication. Once we started fetching the data, we need to save it in MongoDB.

For existing websocket streams mongo callback is working fine. But for my case, let's say for userstream in Binance, I want to implement a new Mongo callback as UserStreamCallback, which seems to be failing for me. 
I get no errors in the code, data from userstream is getting printed in console, but seems like mongo callback is not getting wired up somewhere in the project.
Can you please help?

Let me know if you need more information on this.

Thanks,

**Comment by bmoscon** [comment]
Unless I'm mistaken, you're asking for help on an issue that is not something I can reproduce because its part of changes you made on your own codebase. I don't have access to your code, so how can I fix / debug it?

**Comment by abvashis** [comment]
Thanks for the quick response, do you think it would be helpful if I share code on a public repo?

**Comment by bmoscon** [comment]
@abvashis that or you can email it to me, my email address it on my github profile

**Comment by abvashis** [comment]
Sure, will do that.
