### ISSUE TITLE
Unused `ts` variable `ftx.py`?

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#301]
Hi,
Reading the code to get familiar, I spot in rest/ftx.py [the definition of this variable `ts`](https://github.com/bmoscon/cryptofeed/blob/7d11a862d74070d954ce2a687753157166a7d77f/cryptofeed/rest/ftx.py#L204) that does not appear to be used afterwards in method `_funding_normalization`.

Please, what am I missing?

Thanks for your help.
Have a good day,
Bests,

**Comment by bmoscon** [comment]
Yep, looks like its an un-used variable. I didn't write this, must have just missed it when it got merged in. Feel free to open a PR to remove it, or I'll do it later

**Comment by bmoscon** [comment]
removed.
