### ISSUE TITLE
Useless import in `feedhandler.py`

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#306]
Hi,
Except I am missing something, it seems the `Blockchain` import is redundant with the one immediately below:
https://github.com/bmoscon/cryptofeed/blob/09053add0bcc0d906bddb755d1554902cb6f6674/cryptofeed/feedhandler.py#L27

Line below, `Blockchain` is already imported in `exchanges`:
https://github.com/bmoscon/cryptofeed/blob/09053add0bcc0d906bddb755d1554902cb6f6674/cryptofeed/feedhandler.py#L28

Bests

**Comment by bmoscon** [comment]
yep looks redundant, you can remove it

**Comment by yohplala** [comment]
ok, still deep diving for Coingecko implementation.
I will solve this probably in the process.
Thanks Bryant,

**Comment by bmoscon** [comment]
fixed
