### ISSUE TITLE
Group Bid + Ask volume at Depth X

### ISSUE THREAD

**Issue by nivilo** [bmoscon/cryptofeed#310]
I would like to group the bid and asks with depth X and store it in a database.

Currently it does not support grouping the bid and asks or i might be missing something. I would be great to implement that functionality. 

Thank you and keep up the great work!

**Comment by bmoscon** [comment]
I dont know what you mean by this - do you mean you only want the bid/ask at depth N and none of the bid/asks at depths 0 -> N and N+1 -> end ?

**Comment by nivilo** [comment]
So basically i would like all bids and asks volume up to depth x

**Comment by bmoscon** [comment]
this isnt supported by default, but its something doable with this backend - https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/backends/aggregate.py

Have a look at OHLCV, basically you can wrap any other callback type (like book) and process the data in your own custom aggregator
