### ISSUE TITLE
Bybit Ticker Channel

### ISSUE THREAD

**Issue by singhpav09** [bmoscon/cryptofeed#311]
Bybit does not have a ticker Channel, I feel it could be easily added. 

**Describe the solution you'd like**
https://bybit-exchange.github.io/docs/inverse/#t-websocketinstrumentinfo
The ticker channel can be added from here. It also includes the Open Interest data.

**Comment by bmoscon** [comment]
@singhpav09 - I had a look at it - it looks like it has best bid/ask for a 24 hour period, not most recent.

**Comment by bmoscon** [comment]
since the data does not appear to be available via that channel, closing. If there is another way to provide the true ticker data, please reopen and provide that information.
