### ISSUE TITLE
bitFlyer exchange, a top20 exchange

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptofeed#313]
bitFlyer exchange is a top20 exchange
Reference:
https://coinmarketcap.com/rankings/exchanges/

Documentation:
https://bf-lightning-api.readme.io/docs/endpoint-json-rpc

**Comment by bmoscon** [comment]
looks like a good one to add - thanks for including a link to the docs!

**Comment by bmoscon** [comment]
support added!
