### ISSUE TITLE
Use of asyncio semaphore to limit the number of concurrent tasks and/or requests

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#317]
**Is your feature request related to a problem? Please describe.**
When querying a lot of exchanges, I ran into the error message:
`aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.coingecko.com:443 ssl:default [Temporary failure in name resolution]`

After googling this problem, it appears linked to software limits on the server.
This software limits (number of max open files, number of max connections) can be raised by adequate configuration of the OS, but they can also be solved by use of `asyncio` `semaphore` that limits the max number of concurrent tasks and/or requests before hitting OS limits.

**Describe the solution you'd like**
It is only a ticket to suggest the idea, I have no experience of `semaphore` but different blog articles introduce it.
[This one](https://medium.com/@cgarciae/making-an-infinite-number-of-requests-with-python-aiohttp-pypeln-3a552b97dc95) presents a use case to limit the number of concurrent tasks, while [this previous one](https://www.artificialworlds.net/blog/2017/06/12/making-100-million-requests-with-python-aiohttp/) the number of concurrent requests.
Using `semaphore` appears more a 'best practise' when using `aiohttp` to makre more robust/stable websocket and REST connections.

**Comment by bmoscon** [comment]
I'm not sure this is something we'd want to add. Its far better to increase the os limits if needed than to potentially block data for some period of time. This could mask real issues with a setup/configuration

**Comment by yohplala** [comment]
Hi @bmoscon ,
Ok,
On my side, I feel this feature is leagues above my skills. I was just proposing as it seems the way to go when willing to handle more connections while hardware still has ability to handle it.
OS limits is not necessarily aligned with hardware limits given considered use case.
Anyhow, what I did to solve my trouble is to adjust server profiles I was using to make the most of the hardware, and split the number of crypto keys (pair/exchange/channel) over several servers to scale.
Thanks for your answer.
I guess we can close this ticket.
Have a good evening,
Bests,
Pierre
