### ISSUE TITLE
Support of Kucoin?

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#320]
**Feature request.**
Addition of Kucoin exchange (authorized exchange in Texas, so I have heard :))
- websocket for data retrieval: trade, order books, tickers...

**Comment by bmoscon** [comment]
seems reasonable - docs are here: https://docs.kucoin.com/#public-channels

**Comment by werner-ventures** [comment]
I am working on this, though I have little experience. Any support/reinforcements would be appreciated.

**Comment by bmoscon** [comment]
@werner-ventures  there are docs for this, though slightly outdated: https://github.com/bmoscon/cryptofeed/blob/master/docs/exchange.md

**Comment by bmoscon** [comment]
added. currently only supports ticker and trades, but I'll add in support for L2/L3 orderbooks and candles before the end of the week
