### ISSUE TITLE
Optionally taking into account rate limit of rest feeds in retry strategy implemented in FeedHandler.

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#323]
**Rationale**

Because the 'retry' logic is implemented in `Feedhandler` class, the rate limit management for a rest feed should be managed as well directly in `Feedhandler` class as well, and not individually by each rest feed as it is currently the case.

**Implementation**

In `RestFeed` class
- add a class parameter `rest_sleep` similarly to the `id` class parameter in `Feed`

In `FeedHandler` class
- in `_rest_connect` (that deals with a rest feed), add a `sleep`command just after [the call to `message_handler`](https://github.com/bmoscon/cryptofeed/blob/b9d1195759bc3e3ae9d1a806169a0c7dba4c2216/cryptofeed/feedhandler.py#L218)
- in `_rest_connect`, change `delay` base value from currently '1' to that of `rest_sleep` so that the implemented exponential Backoff logic (multiplying by 2 the delay) makes sense

What do you think?

**Comment by bmoscon** [comment]
the retry there should only be for exceptions. I don't see any advantage from moving it out of the exchanges and into the feedhandler class. the rate limits are per exchange, and should be done individually in each exchange, if needed.

**Comment by yohplala** [comment]
Hi @bmoscon 
I fully agree, I don't ask to change the rate limit definition and the way it is used within the child feed class.

But giving you an example with Coingecko:
- support recommands to wait 1.2 s between 2 requests, and my own test show me we are totally safe with 1.8s
- the retry logic use 1s

So the 1st retry is doing the opposite as the target requested: instead of waiting some time before the retry, we hasten a new request.

What I would do:
- in child exchange class:
```python
    # Declare sleep time between 2 requests.
    self.sleep_time = 1.8
```

- in FeedHandler class, replace [line 211](https://github.com/bmoscon/cryptofeed/blob/4d87c4d8ca07b43272e3eb719cc8b381c06caad4/cryptofeed/feedhandler.py#L211):
```python
   delay = 1
```
with 
```python
   delay = feed.sleep_time
```

**Comment by yohplala** [comment]
Implemented in both Coingecko and Whale Alert branches.
They both have sleep time above 1s (Coingecko: 1,8s - Whale Alert: 6s with free plan)
Current delay defaulting to 1s is worsening the situation.
In the proposed implementation, it is now defined [line 216](https://github.com/yohplala/cryptofeed/blob/161560a7db20b56d3c59a27dd5f4aafbbe4ad43e/cryptofeed/feedhandler.py#L216) as:
```python
delay = 2*feed.sleep_time if feed.sleep_time else 1
```
