### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CryptoFood** [bmoscon/cryptofeed#324]
Hello,

I'm trying to install and work with cryptofeed.
But it seems i do something wrong.

I used this command to install :
**python3 -m pip install --user --upgrade cryptofeed**

Results : 

`Requirement already up-to-date: cryptofeed in /root/.local/lib/python3.5/site-packages (1.4.1)
Requirement already satisfied, skipping upgrade: aiodns in /root/.local/lib/python3.5/site-packages (from cryptofeed) (2.0.0)
Requirement already satisfied, skipping upgrade: cchardet in /root/.local/lib/python3.5/site-packages (from cryptofeed) (2.1.7)
Requirement already satisfied, skipping upgrade: sortedcontainers>=1.5.9 in /root/.local/lib/python3.5/site-packages (from cryptofeed) (2.3.0)
Requirement already satisfied, skipping upgrade: yapic.json>=1.4.3 in /root/.local/lib/python3.5/site-packages (from cryptofeed) (1.5.4)
Requirement already satisfied, skipping upgrade: aiofile in /root/.local/lib/python3.5/site-packages (from cryptofeed) (3.1.1)
Requirement already satisfied, skipping upgrade: requests>=2.18.4 in /root/.local/lib/python3.5/site-packages (from cryptofeed) (2.24.0)
Requirement already satisfied, skipping upgrade: websockets>=7.0 in /root/.local/lib/python3.5/site-packages (from cryptofeed) (7.0)
Requirement already satisfied, skipping upgrade: pandas in /root/.local/lib/python3.5/site-packages (from cryptofeed) (0.25.3)
Requirement already satisfied, skipping upgrade: pyyaml in /root/.local/lib/python3.5/site-packages (from cryptofeed) (5.3.1)
Requirement already satisfied, skipping upgrade: aiohttp in /root/.local/lib/python3.5/site-packages (from cryptofeed) (3.6.3)
Requirement already satisfied, skipping upgrade: pycares>=3.0.0 in /root/.local/lib/python3.5/site-packages (from aiodns->cryptofeed) (3.1.1)
Requirement already satisfied, skipping upgrade: typing; python_version < "3.7" in /root/.local/lib/python3.5/site-packages (from aiodns->cryptofeed) (3.7.4.3)
Requirement already satisfied, skipping upgrade: caio~=0.6.0 in /root/.local/lib/python3.5/site-packages (from aiofile->cryptofeed) (0.6.3)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /root/.local/lib/python3.5/site-packages (from requests>=2.18.4->cryptofeed) (2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /root/.local/lib/python3.5/site-packages (from requests>=2.18.4->cryptofeed) (2020.11.8)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /root/.local/lib/python3.5/site-packages (from requests>=2.18.4->cryptofeed) (1.25.11)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /root/.local/lib/python3.5/site-packages (from requests>=2.18.4->cryptofeed) (3.0.4)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in /root/.local/lib/python3.5/site-packages (from pandas->cryptofeed) (1.18.5)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /root/.local/lib/python3.5/site-packages (from pandas->cryptofeed) (2020.4)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /root/.local/lib/python3.5/site-packages (from pandas->cryptofeed) (2.8.1)
Requirement already satisfied, skipping upgrade: idna-ssl>=1.0; python_version < "3.7" in /root/.local/lib/python3.5/site-packages (from aiohttp->cryptofeed) (1.1.0)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /root/.local/lib/python3.5/site-packages (from aiohttp->cryptofeed) (20.3.0)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in /root/.local/lib/python3.5/site-packages (from aiohttp->cryptofeed) (4.7.6)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in /root/.local/lib/python3.5/site-packages (from aiohttp->cryptofeed) (3.0.1)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.5; python_version < "3.7" in /root/.local/lib/python3.5/site-packages (from aiohttp->cryptofeed) (3.7.4.3)
Requirement already satisfied, skipping upgrade: yarl<1.6.0,>=1.0 in /root/.local/lib/python3.5/site-packages (from aiohttp->cryptofeed) (1.5.1)
Requirement already satisfied, skipping upgrade: cffi>=1.5.0 in /root/.local/lib/python3.5/site-packages (from pycares>=3.0.0->aiodns->cryptofeed) (1.14.3)
Requirement already satisfied, skipping upgrade: six>=1.5 in /root/.local/lib/python3.5/site-packages (from python-dateutil>=2.6.1->pandas->cryptofeed) (1.15.0)
Requirement already satisfied, skipping upgrade: pycparser in /root/.local/lib/python3.5/site-packages (from cffi>=1.5.0->pycares>=3.0.0->aiodns->cryptofeed) (2.20)`

Then, I tried the first example , and i have this error : 
```
Traceback (most recent call last):
  File "lk.py", line 1, in <module>
    from cryptofeed import FeedHandler
  File "/root/.local/lib/python3.5/site-packages/cryptofeed/__init__.py", line 7, in <module>
    from cryptofeed.feedhandler import FeedHandler
  File "/root/.local/lib/python3.5/site-packages/cryptofeed/feedhandler.py", line 18, in <module>
    from cryptofeed.exchange.blockchain import Blockchain
  File "/root/.local/lib/python3.5/site-packages/cryptofeed/exchange/blockchain.py", line 73
    LOG.info(f"Subscribed to {msg['symbol']}")
                                            ^
SyntaxError: invalid syntax
```

What I did wrong ? I have just copy/paste.

Thank you to help me to understand,
Regards

**Comment by bmoscon** [comment]
You are using python 3.5. 3.7+ is required

**Comment by CryptoFood** [comment]
Right.
But now :
`ModuleNotFoundError: No module named '_bz2'`

Even after : sudo apt-get install libbz2-dev

Thank you.

**Comment by bmoscon** [comment]
I'm not sure what that error is, its not related to this project, its a python issue. I'd recommend using a virtual environment or something else to manage your python versions. The SO post has other solutions (other than installing the lib):

https://stackoverflow.com/questions/12806122/missing-python-bz2-module

it also mentions you should "rebuild" python after installing that dependency. I'm guessing you are using an old version of ubuntu, try upgrading to a newer version if the other things dont resolve the issue
