### ISSUE TITLE
Bybit Liquidations

### ISSUE THREAD

**Issue by jzay** [bmoscon/cryptofeed#334]
Hi, Are Bybit liquidations supported already?

I tried to bring them up but couldn't.

**Comment by bmoscon** [comment]
no, only these feeds currently support liquidations:

BITMEX, BINANCE_FUTURES, FTX, DERIBIT

the `info()` method on an exchange class will give you information about what data channels it supports

**Comment by jzay** [comment]
Thank You

**Comment by jzay** [comment]
1.

**Comment by bmoscon** [comment]
@jzay - the exchange does support it - just need to add it to the code, I'm going to re-open this, I can add support in the coming days

https://bybit-exchange.github.io/docs/inverse/#t-query_liqrecords

**Comment by clhirondel** [comment]
Hello,

Is it possible to add ByBit liquidations ?

**Comment by bmoscon** [comment]
@clhirondel - yes, I'll add that too

**Comment by clhirondel** [comment]
Thank you @bmoscon

**Comment by bmoscon** [comment]
Bybit liquidations added
