### ISSUE TITLE
HUOBI_SWAP error

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#342]
**Describe the bug**
I get following error message from HUOBI_SWAP.
```bash
2020-12-02 21:46:59,329 : ERROR : HUOBI_SWAP: encountered an exception, reconnecting
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed-1.6.2-py3.8.egg/cryptofeed/feedhandler.py", line 258, in _connect
    await self._handler(websocket, feed.message_handler, feed.uuid)
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed-1.6.2-py3.8.egg/cryptofeed/feedhandler.py", line 287, in _handler
    await handler(message, self.last_msg[feed_id])
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed-1.6.2-py3.8.egg/cryptofeed/exchange/huobi_dm.py", line 130, in message_handler
    await self._book(msg, timestamp)
  File "/usr/local/lib/python3.8/dist-packages/cryptofeed-1.6.2-py3.8.egg/cryptofeed/exchange/huobi_dm.py", line 79, in _book
    for price, amount in data['bids']
KeyError: 'bids'
```

**To Reproduce**
Everything was working ok since several days, so I suspect there has been a change with HUOBI_SWAP API or with HUOBI_SWAP server maybe?

**Expected behavior**
The error message is pretty clear.
IMHO, 2 things could be improved:
- having an error because of a missing key should be stopped 'earlier'. Before trying to use the key. Before running this part of the code, maybe a check that a response has been received from HUOBI_SWAP?
- I get several tens of such messages per minutes. `feedhandler.log` is filling. Could there be a backhoff strategy in such a case, like there is for the rest feed maybe?

Well, I feel, such an error should not cause a 'ERROR : HUOBI_SWAP: encountered an exception, reconnecting'.

**Cryptofeed Version**
1.6.2

**Comment by yohplala** [comment]
Here is the configuration for HUOBI_SWAP.
```yaml
    HUOBI_SWAP:
        channel_timeouts:
            trades: 90
            l2_book: 90
        retries: -1
        trades: [AAVE-USD,ADA-USD,AKRO-USD,ALGO-USD,ANKR-USD,BAT-USD,BTC-USD,LUNA-USD,MKR-USD,NEAR-USD,NEO-USD,THETA-USD,UNI-USD]
        l2_book:
            symbols: [AAVE-USD,ADA-USD,AKRO-USD,ALGO-USD,ANKR-USD,BAT-USD,BTC-USD,LUNA-USD,MKR-USD,NEAR-USD,NEO-USD,THETA-USD,UNI-USD]
            book_delta: true
            book_interval: 100000
```

**Comment by bmoscon** [comment]
see https://huobiglobal.zendesk.com/hc/en-us/articles/900003742046-Announcement-on-the-Delisting-of-Some-Assets-for-Huobi-Coin-margined-Swaps


some of their trading pairs are being delisted, so are no longer valid.

**Comment by bmoscon** [comment]
i put in some code to have it ignore empty book updates

**Comment by yohplala** [comment]
Bryant, do you think there could be a warning message indicating that a pair is not in the response and probably delisted?
I believe having detailed warning to set user on a track are great added value.
