### ISSUE TITLE
Bybit trade data isn't precise

### ISSUE THREAD

**Issue by warproxxx** [bmoscon/cryptofeed#345]
**Describe the bug**
All other exchange get precise timestamp of when the trade took place like 1607058533.066 (which includes millisecond). But the bybit trade data dosen't include millisecond 1607058532.0

**To Reproduce**
```
from cryptofeed.feedhandler import FeedHandler
from cryptofeed.defines import TRADES
from cryptofeed.exchanges import BinanceFutures, Bybit

async def trade(feed, pair, order_id, timestamp, receipt_timestamp, side, amount, price):
    print("{} {} {}".format(feed, pair, timestamp))


f = FeedHandler(retries=1000000000)
f.add_feed(Bybit(pairs=['BTC-USD'],channels=[TRADES], callbacks={TRADES: trade}), timeout=-1)
f.add_feed(BinanceFutures(pairs=['BTC-USDT'],channels=[TRADES], callbacks={TRADES: trade}), timeout=-1)
f.run()
```

**Expected behavior**
O/P
BINANCE_FUTURES BTC-USDT 1607059067.177
BYBIT BTC-USD 1607059067.0

BINANCE_FUTURES and all other gets precise timestamp. Bybit get .0

**Screenshots**

**Operating System:**
Ubuntu 20.04

**Cryptofeed Version**
v1.6.1

**Comment by warproxxx** [comment]
As bybit API provides millisecond data, there must be error in processing somewhere. I think i will able to find the fix in a couple of hours

**Comment by warproxxx** [comment]
Sent a pull request for fixing this in #346

**Comment by warproxxx** [comment]
The fix messes OI and L2_BOOK. @bmoscon to fix the trade issue, we have to send the trade_time_ms which is an int. But OI only has datetime value. I can fix this by creating an optional parameter in timestamp_normalize for bybit which indicates which is it or check if we sent a int or datetime, but it might make a clean function timestamp_normalize look a little messy. Do you have a better idea?

**Comment by warproxxx** [comment]
Sent a fix commit to not break OI. Its kinda hacky but i think its the best fix

**Comment by bmoscon** [comment]
merged - thanks!
