### ISSUE TITLE
Having more complete order book for Bybit

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#350]
**Is your feature request related to a problem?**
2 depths of order book are possible for Bybit, the 25 1st levels or the 200 1st levels.
The 25 1st levels are provided in real time.
The 200 1st levels are provided every 100ms.
Currently, `l2_25`is queried by cryptofeed as a default.
I would like to querry `l2_200`.

**Describe the solution you'd like**
Could a parameter be made available for the user to chose which depth is requested?
Maybe not a parameter to leave an 'open' choice, but something like `book_subscription=fast`or `book_subscription=complete`.
The idea is that the parameter is depending the need of the user, either having the 'most complete' data possible, or having new data the 'fastest possible'.
(I am thinking that such a situation may arise for other exchanges as well, with different levels of depth).

**Additional context**
I am not doing HFT, so an update of the book every sec. or even every 10 sec. is fine for me. I have thus no trouble with an interval of 100ms.
Also, I don't think that any HFT developer would use python as coding language, so not really sure the 100ms interval for `l2_200`is a big deal for cryptofeed users.
This said, leaving the choise to the user is probably what should be done.

**Comment by bmoscon** [comment]
implemented in master.
