### ISSUE TITLE
Unable to add LiquidationsArctic to script

### ISSUE THREAD

**Issue by interzonez** [bmoscon/cryptofeed#355]
I'm simply adding LiquidationsArctic to demo_open_interest.py 

Adding just as the others:

`def main():
    f = FeedHandler()
    f.add_feed(Bitmex(pairs=['XBTUSD'], channels=[TRADES, OPEN_INTEREST, TICKER], callbacks={
               OPEN_INTEREST: OpenInterestArctic('cryptofeed-test2'), TRADES: TradeArctic('cryptofeed-test2'), TICKER: TickerArctic('cryptofeed-test2'), LIQUIDATIONS: LiquidationsArctic('cryptofeed-test2')}))
    f.run()`

But am getting the following runtime error:

`Traceback (most recent call last):
  File "demo_open_interest.py", line 7, in <module>
    from cryptofeed.backends.arctic import OpenInterestArctic, TradeArctic, TickerArctic, LiquidationsArctic
ImportError: cannot import name 'LiquidationsArctic'`

`No name 'LiquidationsArctic' in module 'cryptofeed.backends.arctic' pylint(no-name-in-module)`

Can't see what disallows me to add LiquidationsArctic ???

**Comment by bmoscon** [comment]
can you confirm what version of cryptofeed you are using, and what version of Python? I added that import to the same file and had no issues.

**Comment by interzonez** [comment]
I was using Python 3.6 Anaconda - switched to 3.8 working now.

**Comment by bmoscon** [comment]
ok great
