### ISSUE TITLE
Support Crypto.com exchange

### ISSUE THREAD

**Issue by AlgoTrader5** [bmoscon/cryptofeed#357]
**Is your feature request related to a problem? Please describe.**
Crypto.com is a relevant exchange in the cryptocurrency space

**Describe the solution you'd like**
L2 Book, Ticker, Trades

**Describe alternatives you've considered**
n/a

**Additional context**
API docs look pretty solid. Supports REST and Websocket
https://exchange-docs.crypto.com/

**Comment by bmoscon** [comment]
I'm working on this now - thanks for the suggestion and sorry for the delay @AlgoTrader5

**Comment by bmoscon** [comment]
done
