### ISSUE TITLE
Store timestamps as date from unix

### ISSUE THREAD

**Issue by interzonez** [bmoscon/cryptofeed#359]
How can I have the timestamp as date instead of unix format when feed is sent to MongoDB?

Can this be done in the python script or need to updateMany (having trouble with this) in Mongo Shell e.g. 

Thanks.

**Comment by bmoscon** [comment]
you'd need to modify the code for the mongo backend to convert the unix timestamps to something else. im not sure its something you want to do from python or mongo shell after the fact, unless you have a small amount of data.
