### ISSUE TITLE
Bitfinex: failing pair normalization strategy

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#360]
**Describe the bug**
`BCHN` & `BCHABC` are not distinguished by Cryptofeed/Bitfinex.
`LINK` is not recognized by Cryptofeed/Bitfinex.

Current code in `pairs.py` assumes only 3 letters allow identifying a coin.
```python
        normalized = pair[1:-3] + PAIR_SEP + pair[-3:]
```

-  Which does not allow distinguishing `BCHN` and `BCHABC`.
  "tBCHABC:USD"
  "tBCHN:USD"
  (to be noticed within the normalization effort: Binance, Kraken, Huobi, OKEX, FTX... keep `BCH` for `BCHN`: I would propose to do the same within cryptofeed)

- Which also do not allow to find `LINK.
  "tLINK:USD"
  "tLINK:UST"

**To Reproduce**
Trying to query following coins do not work.
```yaml
    BITFINEX:
        trades: ['BCH-USDT', 'LINK-USD']
```

PS: link to retrieve Bitfinex pairs:
https://api.bitfinex.com/v2/tickers?symbols=ALL

**Comment by bmoscon** [comment]
fixed
