### ISSUE TITLE
Bitmex: implement pair normalization

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#361]
**Feature request**
Implement pair normalization for Bitmex as well.
Possibly, make both possible: legacy pair naming and pair normalization? (for those willing to keep legacy pair naming)

**Additional context**
I am using a script to generate config file, at least the part concerning exchanges.
I basically list:
- base coins
- quote coins
- exchanges
- channels
The script checks then every possible configuration and generates the corresponding config files.
Without normalization (only considering perpetual contracts, not futures), this strategy fails with Bitmex.

**Comment by bmoscon** [comment]
each exchange has a generate pairs method, even bitmex - why doesnt your strategy work?

**Comment by yohplala** [comment]
Hi @bmoscon ,
Sorry, the ticket is possibly not very clear.
Pair normalization is not implemented for Bitmex. For instance, to query `BTC-USD` to Bitmex, you need to write `XBTUSD` in the config file.
In this sense, my strategy fails because it only generate pairs in the form `base_coin-quote-coin`.
Bests

**Comment by bmoscon** [comment]
ok, makes sense. its probably time to bring bitmex into the normalized pair fold :)

**Comment by yohplala** [comment]
Hit @bmoscon, hi @olibre 
I am sorry, i just checked PR #363, and from what I could not find in this PR, I just confirm it does not implement it.

```python
 from cryptofeed.exchanges import Bitmex
Bitmex.info()['pairs']
```

Results
```bash
['LINKUSDTZ20',
 'XTZUSDTZ20',
 'BNBUSDTZ20',
 'ADAUSDTZ20',
 'EOSUSDTZ20',
 'YFIUSDTZ20',
 'DOTUSDTZ20',
 'XRPZ20',
 'BCHZ20',
 'ADAZ20',
 'EOSZ20',
 'TRXZ20',
 'LINKUSDTH21',
 'XTZUSDTH21',
 'BNBUSDTH21',
 'ADAUSDTH21',
 'EOSUSDTH21',
 'YFIUSDTH21',
 'DOTUSDTH21',
 'XRPH21',
 'BCHH21',
 'ADAH21',
 'EOSH21',
 'TRXH21',
 'XRPUSD',
 'LINKUSDT',
 'BCHUSD',
 'XBTUSD',
 'XBTZ20',
 'XBTH21',
 'XBTM21',
 'ETHUSD',
 'ETHZ20',
 'ETHUSDZ20',
 'ETHH21',
 'ETHUSDH21',
 'LTCUSD',
 'LTCZ20',
 'LTCH21']
```

Normalized paris should read (proposing to use `_` to further split contract end for futures, similar to Binance)
```bash
['LINK-USDT_Z20',
 'XTZ-USDT_Z20',
 'BNB-USDT_Z20',
 'ADA-USDT_Z20',
 'EOS-USDT_Z20',
 'YFI-USDT_Z20',
 'DOT-USDT_Z20',
 'XRP_Z20',
 'BCH_Z20',
 'ADA_Z20',
 'EOS_Z20',
 'TRX_Z20',
 'LINK-USDT_H21',
 'XTZ-USDT_H21',
 'BNB-USDT_H21',
 'ADA-USDT_H21',
 'EOS-USDT_H21',
 'YFI-USDT_H21',
 'DOT-USDT_H21',
 'XRP_H21',
 'BCH_H21',
 'ADA_H21',
 'EOS_H21',
 'TRX_H21',
 'XRP-USD',
 'LINK-USDT',
 'BCH-USD',
 'BTC-USD',    # notice here BTC instead of XBT
 'BTC_Z20',       # same
 'BTC_H21',       # same
 'BTC_M21',       # same
 'ETH-USD',
 'ETH_Z20',
 'ETH-USD_Z20',
 'ETH_H21',
 'ETH-USD_H21',
 'LTC-USD',
 'LTC_Z20',
 'LTC_H21']
```

**Comment by yohplala** [comment]
@bmoscon 
could you re-open this ticket please?

**Comment by bmoscon** [comment]
yes, i closed the wrong one

**Comment by bmoscon** [comment]
The other PR was misnamed I believe, it fixed the bitfinex issue, not the bitmex issue

**Comment by yohplala** [comment]
> The other PR was misnamed I believe, it fixed the bitfinex issue, not the bitmex issue

Hmm, I had a look: there have been some new lines for BitmAx when before there was nearly none.
So yes, I think it is misnaming, but Bitmax instead of Bitmex :+1: 

Thanks Bryant

**Comment by olibre** [comment]
Sorry guys. The bug is in my brain: confused the names Bit[m]ex and Bit[fin]ex. :open_mouth:

**Comment by bmoscon** [comment]
done
