### ISSUE TITLE
Adjust `delay` depending `feed.sleep_time`?

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#369]
**Describe the bug**
Before exchange connection refactoring, `sleep_time` attribute has been used for `rest_feed`(Coingecko & Whale_Alert) to initialize `delay`:
[code extract from commit](https://github.com/bmoscon/cryptofeed/commit/89701073c917a18224500e04f158fc247e70cc8d#diff-9fad70d8501bc6736b79d842f38708a0cb13c76fd0dbcbc8793883cfb9eff685L235)

This need arises because sleep time for rest connection can/is larger than 1s.

In current new `feedhandler.py`implementation, this seems to have disappeared.
[line 220](https://github.com/bmoscon/cryptofeed/blob/4b326f9d0fa26222f1ceafa750db2a7501be76dd/cryptofeed/feedhandler.py#L220)
[line 228](https://github.com/bmoscon/cryptofeed/blob/4b326f9d0fa26222f1ceafa750db2a7501be76dd/cryptofeed/feedhandler.py#L228)
Please, can it be re-implemented?

**Comment by bmoscon** [comment]
sleep time is passed in and used as the sleep for https connections in the asyncconnection object. If there are connection issues it will fallback to the connect handler in feedhandler and retry the connection. Why won't that work here?

**Comment by bmoscon** [comment]
I think this will fix the issue for coingecko:

https://github.com/bmoscon/cryptofeed/commit/b00fe8922e95331919c32d7af2137f3bf17d9cf6


Let me know what you think.

**Comment by yohplala** [comment]
> I think this will fix the issue for coingecko:
> 
> [b00fe89](https://github.com/bmoscon/cryptofeed/commit/b00fe8922e95331919c32d7af2137f3bf17d9cf6)
> 
> Let me know what you think.

I just had a look and it appears good to me Bryant, thanks!
