### ISSUE TITLE
Binance futures ticker API changed

### ISSUE THREAD

**Issue by qinghuangchan** [bmoscon/cryptofeed#374]
**Describe the bug**

it seems like Binance Futures has slightly changed their API..

previously, as documented in binance_futures.py, it seems like the ticker stream message has an empty message type field, and the code relied on that to process ticker info
```
        if msg_type is None:
            # For the BinanceFutures API it appears
            # the ticker stream (<symbol>@bookTicker) is
            # the only payload without an "e" key describing the event type
            await self._ticker(msg, timestamp)
```

However, it seems like from the 2020-12-08 onwards, binance changed their api to publish e: bookTicker

`2020-12-08 11:16:09,671 : WARNING : BINANCE_FUTURES: Unexpected message received: {'e': 'bookTicker', 'u': 116043596979, 's': 'BTCUSDT', 'b': '19172.24', 'B': '1.283', 'a': '19172.25', 'A': '3.944', 'T': 1607397342959, 'E': 1607397369624}
`

**Comment by bmoscon** [comment]
fixed - thanks!
