### ISSUE TITLE
Add Huobi USDT/Linear Swaps 

### ISSUE THREAD

**Issue by strcat32** [bmoscon/cryptofeed#386]
if i am not mistaken only coin margined Swaps for Huobi are implemented.

https://huobiapi.github.io/docs/usdt_swap/v1/en/#swap-api-access-guide

The API Url is also slightly different:
https://api.hbdm.com/linear-swap-api/v1/swap_contract_info

Or am i missing something?

**Comment by bmoscon** [comment]
I'm not sure what you are asking for here

**Comment by strcat32** [comment]
Huobi has coin margined swap futures (BTC-USD, etc.) and Tether margined futures (BTC-USDT).
Cryptofeeds only supports coin margined future as far as i can see?!

https://futures.huobi.com/en-us/swap/exchange/#symbol=BTC (supported)
vs
https://futures.huobi.com/en-us/linear_swap/exchange/#contract_code=BTC-USDT (not supported)

**Comment by zhenpingfeng** [comment]
Huobi terminated their derivatives business, this feature request can now be closed.

**Comment by strcat32** [comment]
> Huobi terminated their derivatives business, this feature request can now be closed.

As i understand it they only closed their derivatives for customers from Mainland China. 
I can still access both coin margined and USDT margined future instruments (from the links above).

**Comment by bmoscon** [comment]
yes that is correct - they have only reduced the number of countries that can access it

**Comment by minglan01** [comment]
Hey just wondering is there any update for this request?

**Comment by bmoscon** [comment]
I haven't done anything on this and I haven't seen any PRs on it, so I'm going to say no. I do like PRs though so if you are so inclined feel free to add support for this

**Comment by minglan01** [comment]
Nice! I'll try to add it.

**Comment by bmoscon** [comment]
added, thanks @minglan01
