### ISSUE TITLE
No module named 'cryptofeed.symbols' when executing demo.py

### ISSUE THREAD

**Issue by jeans-all** [bmoscon/cryptofeed#395]
Hi, I am new to this project and follow up on the demo. 

After installing cryptofeed on Windows by 'pip install cryptofeed[all]', I literally copied demo.py into my local machine and executed it, but it failed with an error as follows:

Traceback (most recent call last):
  File "C:\Users\donta\Desktop\Arbitrage\demo.py", line 8, in <module>
    from cryptofeed.symbols import binance_symbols
ModuleNotFoundError: No module named 'cryptofeed.symbols'

Can you shed some lights on this issue?

**Comment by bmoscon** [comment]
the version on github and the version in pypi are different, so if you want to use the examples from github directly you need to be using the latest version in master, or wait until a release
