### ISSUE TITLE
GDAX trades channel and trade ids

### ISSUE THREAD

**Issue by MarechJ** [bmoscon/cryptofeed#4]
Hi,

I think the GDAX trades channel should be emulated from the 'ticker' one as it contains price, side and size for the last trade, which is pretty much what Bitfinex gives in their trades channels. It's not convenient to also have to add the oderbook. What I offer would be "aggregated trades" similar to what binance does. The current functionality could be separated as a "granular trades" (binance has that too).

Side note and less important: I think it's a shame to exclude ids from msgs (trade id for example), many implementations might need it (we do). Have a look at what the ccxt lib does, IMO it's a good level of abstraction and standardization but they also leave the raw message in the event for clients that need to specialize.

**Comment by bmoscon** [comment]
both sound doable, will get to it soon - thanks for submitting an issue

**Comment by chellowlolo** [comment]
For what’s its worth I agree completely with this suggestion.

**Comment by MarechJ** [comment]
I'de be interesting to standardize the names of the channels, for examples if I start a feed on GDAX for 'trades' it listens to 'ticker' or 'match' behind the scene. I'll see if I have time for a PR.

**Comment by bmoscon** [comment]
I've already done something like that for some feeds, but it will be consistent across all of them soon.

**Comment by bmoscon** [comment]
I believe this is fixed now (I just added trade ids for gemini and gdax)
