### ISSUE TITLE
How to Make Sure WS Data is Up to Date

### ISSUE THREAD

**Issue by Jay54520** [bmoscon/cryptofeed#407]
Definition of up to date: latency between local order book and remote is within `x` ms

My solution: Check the latency by `current_timestamp - receipt_timestamp` 

But `receipt_timestamp` may not be updated if the server didn't send due to various reasons such as order book doesn't change or cryptofeed has some errors. If using REST won't have this problem. Is there a better way to handle this problem?

**Comment by bmoscon** [comment]
some exchanges just don't provide a timestamp on the book data at all. I'm not sure why you wouldnt have the problem with rest - you don't know the delay between the data there either, or if the book data they provide via rest is real time, plus due to rate limits, you can probably only poll the book a few times a second, when lots of exchanges have books that update much more frequently than that (so you arent actually getting all the data via REST)

**Comment by Jay54520** [comment]
The lantency of REST is fixed while ws of cryptofeed can be much longer after retrying max retires when entering error.  And there is a cached local order book of ws while REST doesn't have.

**Comment by bmoscon** [comment]
i disagree, the latency of both should vary wildly - there is the internal latency on the exchange side - after the book is updated it takes some time for the update to be ready to send via websocket or other real time messaging systems, and the same goes for rest - the data returned by polling systems lives somewhere and has to be populated. that latency is probably pretty constant, and may only vary during large load on their systems or spikes in orders. The latency from when those messages are sent to the user is going to be different every time based on all the factors that affect all internet traffic.

I'm still not sure what the issue or question is - if the exchange has issues in providing the data to us via websocket i dont think there is much that can be done to ensure the data is up to date. The data can be discarded when an error occurs, which is what happens, the book is reset and a snapshot is sent when the reconnection occurs.

**Comment by yohplala** [comment]
Hi @Jay54520 
Sorry for maybe a dumb question, but why don't you check `timestamp`in the 1st place vs `current_time`?
Why `receipt_timestamp`?
Would I want to check I have 'recent' data, then I need to checl `timetamp` which is the timestamp of the data on the exchange's side.

**Comment by Jay54520** [comment]
> Hi @Jay54520
> Sorry for maybe a dumb question, but why don't you check `timestamp`in the 1st place vs `current_time`?
> Why `receipt_timestamp`?
> Would I want to check I have 'recent' data, then I need to checl `timetamp` which is the timestamp of the data on the exchange's side.

In my server, the `timestamp` from exchange is greater than the `receipt_timestamp` from local, this means my server's time is smaller. Use `receipt_timestamp` can avoid the not synced time but also can check whether the data is fresh, you just need to reduce the latency of network.

**Comment by yohplala** [comment]
> In my server, the `timestamp` from exchange is greater than the `receipt_timestamp` from local, this means my server's time is smaller. Use `receipt_timestamp` can avoid the not synced time but also can check whether the data is fresh, you just need to reduce the latency of network.

Thanks for taking the time to explain. I understand.
the trouble then is that you have no shared reference time with the exchange, and it is the exchange time that will tell you if the data is 'fresh' or not.
Tricky topic.

**Comment by bmoscon** [comment]
I dont think there is anything else I can answer on this topic, so closing the ticket, since its a question and there is nothing left to do here
