### ISSUE TITLE
demo_postgres.py error

### ISSUE THREAD

**Issue by sebabuso** [bmoscon/cryptofeed#411]
Hi. I am testing demo_postgres.py and it does not create the corresponding tables in the DB. Is there a file.sql to create the empty tables?

The error:
File "asyncpg/protocol/protocol.pyx", line 316, in query
asyncpg.exceptions.UndefinedTableError: relation "trades" does not exist

**Comment by bmoscon** [comment]
no, the tables can be configured in many ways with many different configurations, indexing, etc so I don't provide anything.

**Comment by bmoscon** [comment]
@sebabuso there is now an example postgres SQL file to create the tables for the demo

**Comment by sebabuso** [comment]
Thanks @bmoscon !!!. I already have cryptofeed working with postgres SQL and InfluxDB.
Another question, is there idea in the cryptofeed roadmap to get historical data?

**Comment by bmoscon** [comment]
its already supported, its in rest/

**Comment by sebabuso** [comment]
Thanks again!!! I'm going to test it !!
