### ISSUE TITLE
Support Order Channel in FTX/FTX.US 

### ISSUE THREAD

**Issue by Jay54520** [bmoscon/cryptofeed#412]
**Is your feature request related to a problem? Please describe.**
There is already trade channel but order channel is better in this scene. I use market order so the order will be executed immediately but sometimes with many trades. I only need one signal to know whether the order is filled but trade channel may send many signals.

**Describe the solution you'd like**
Support order channel: https://docs.ftx.com/#orders-2

**Comment by bmoscon** [comment]
thats an authenticated channel. Support exists for those now, but it is a lot more work than just adding a public channel. I'll add this to the list

**Comment by bmoscon** [comment]
fixed!
