### ISSUE TITLE
Deribit Liquidations channel not working

### ISSUE THREAD

**Issue by mfw78** [bmoscon/cryptofeed#416]
**Describe the bug**
When subscribed to `TRADES` channel, with `LIQUIDATIONS` callback comprised of a class which inherits `KafkaCallback` and `BackendLiquidationsCallback`, no liquidation messages are passed to the Kafka topic.

**Expected behavior**
Liquidation messages passed to the applicable topic.

**Operating System:**
- Kubernetes 1.20.1 - Flatcar Container Linux by Kinvolk 2705.1.0 (Oklo).
- Containers deployed based on python:slim.

**Cryptofeed Version**
- Git commit `6275d95` checked out from repo. `pip install .` in git repository for installation in `virtualenv`.

**Comment by bmoscon** [comment]
Can you provide the `add_feed` method calls with all the params, callbacks, etc?

**Comment by mfw78** [comment]
Find the source code that I'm working with [here](https://github.com/bmoscon/cryptofeed/files/5974963/main.txt). This is the complete implementation, with the only external dependencies being git commit `6275d95`.

**Comment by bmoscon** [comment]
I've reviewed the deribit docs, and the code, it looks correct, how long did you wait while testing? liquidations dont happen that frequently

**Comment by mfw78** [comment]
@bmoscon My bad. It seems the consumer that I wrote to test the topic was incorrectly configured. On closer inspection the liquidations were indeed being logged.
