### ISSUE TITLE
Put multiple symbol in same line export

### ISSUE THREAD

**Issue by 0trade** [bmoscon/cryptofeed#417]
Hello Mr Moscon,

The simple example is:

```
async def book(feed, symbol, book, timestamp, receipt_timestamp):
        print(f'Timestamp: {timestamp} Feed: {feed} Pair: {symbol} Book Bid Size is {len(book[BID])} Ask Size is {len(book[ASK])}')

f = FeedHandler()
f.add_feed(Upbit(symbols=['BTC-USDT', 'ETH-USDT'], channels=[L2_BOOK], callbacks={L2_BOOK: BookCallback(book)}))
f.run()
```

The export this:
`Timestamp: 1613284390.284 Feed: UPBIT Pair: BTC-USDT Book Bid Size is 15 Ask Size is 15`
`Timestamp: 1613284390.284 Feed: UPBIT Pair: ETH-USDT Book Bid Size is 15 Ask Size is 15`

Is there any chance put two symbol in one line, like is:
`Timestamp: 1613284390 Feed: UPBIT Pair: BTC-USDT Book Bid Size is 15 Ask Size is 15, Pair: ETH-USDT Book Bid Size is 15 Ask Size is 15`

**Comment by bmoscon** [comment]
probably not for a few reasons
1. None of the callbacks assume lists of data
2. Most exchanges send updates one at a time, or one at a time per symbol, so to return data like that would require waiting, which would add unnecessary latency
3. to get that working would require a lot of work, for little, if any, gain

**Comment by 0trade** [comment]
Noted, thank your response, sir.
