### ISSUE TITLE
Dynamically adding feeds

### ISSUE THREAD

**Issue by thisiscam** [bmoscon/cryptofeed#418]
**Is your feature request related to a problem? Please describe.**
I'm running cryptofeed in a separate thread, and I would like to dynamically subscribe to feeds from the main thread.
Is this already supported?

**Describe the solution you'd like**
Potentially, the `add_feed` function should be callable from another thread? 
Currently I get an error saying `No feeds specified`here https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/feedhandler.py#L210

**Comment by bmoscon** [comment]
its not currently supported, and calling add_feed later (after run) won't work. Run is what does the actual work of creating the tasks.

**Comment by thisiscam** [comment]
I'm temptive to implement this, but would be good to hear from you if there is a fundamental reason why we cannot support this?
For example, does all the exchanges support dynamically subscription (I'd expect them to)?

Also, does it make sense to make feedhandler to fully support asyncio? Like, making the `run` and `subscribe` functions async -- this will allow better integration with existing asyncio programs.

**Comment by bmoscon** [comment]
I didnt say it cant be supported, I said it wont work now. 

I'm not sure what your second question means. Cryptofeed only works with asyncio, there isnt anything here that would prevent integration, so im not sure how we can better integrate.

**Comment by thisiscam** [comment]
> I didnt say it cant be supported, I said it wont work now.
Thanks for confirming! I was just trying to understand the possible outcomes before getting my hands on the code.

> I'm not sure what your second question means. 
Sorry I wasn't clear. 
My imagined use case is the following:
Some existing code uses `asyncio` for its own processing. 
For example, it might have an async task that is run every few seconds -- like making a decision for if to open a buy order or not.
It would naturally like to use `cryptofeed` to listen for ohlcv updates. Since it already uses asyncio, one desirable method would be to launch feedhandler.run in another background task, in the same event loop as the one that makes decisions.

**Comment by mfw78** [comment]
Not to encourage too much feature creep, I'd add my support for requesting dynamic channel subscriptions. Preferably this would be great if something along the lines of a simple API that allowed feeds to be added programmatically by a cryptofeed manager. A bonus would be metric reporting so it could be monitored on a clustered scale.

**Comment by bmoscon** [comment]
@thisiscam it can already do that. There are kwarg options that indicate the caller wants to manage the loop lifetime themselves, so all run will do in that case is add the tasks, but it will not start the loop.

**Comment by Dynamikey** [comment]
I did something similar to what you're asking for in this PR https://github.com/Dynamikey/cryptofeed/pull/5/files. Main thing is that "connection" object in feed is stored for later use. I also have a separate async task to poll for new instruments to subscribe to. Perhaps @bmoscon  has a better suggestion as to how this should be done?

**Comment by bmoscon** [comment]
Added a new method, `add_feed_running` that allows the creation of new feeds on an already running instance of a feedhandler. See https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_loop.py for an example

**Comment by Vniex** [comment]
Besides, how to dynamic close a running feed?

**Comment by bmoscon** [comment]
@Vniex - not currently possible. You can stop the event loop or kill the task to disconnect, but none of the exchanges have the unsubscribe functionality implemented
