### ISSUE TITLE
Bitstamp L3 book

### ISSUE THREAD

**Issue by bachirelkhadir** [bmoscon/cryptofeed#423]
First all, thank you to the author for the fantastic work  you put in!

I am not sure if I encountered a bug or if I am simply doing something wrong. I am trying to get level 3 orderbook data from Bitstamp. Here is the code I am using.

```
from cryptofeed import FeedHandler
from cryptofeed.defines import L2_BOOK, L3_BOOK, BOOK_DELTA, TRADES, TICKER, BID, ASK
from cryptofeed.exchanges import Bitstamp


async def book(feed, symbol, book, timestamp, receipt_timestamp):
    print(f'Timestamp: {timestamp} Feed: {feed} Pair: {symbol} Book Bid Size is {len(book[BID])} Ask Size is {len(book[ASK])}')

f = FeedHandler()
bitstamp = Bitstamp(channels=[L3_BOOK,  BOOK_DELTA],
                    symbols=["BTC-USD"],
                    callbacks={
                        L3_BOOK: book,
                        BOOK_DELTA: book,
                    })
f.add_feed(bitstamp)
f.run()
```

This code fails and throws the following error:
`2021-02-23 17:18:47,532 : ERROR : Error: UnsupportedDataFeed('book_delta is not currently supported on BITSTAMP')`

Fair enough, it seems that book deltas are not supported yet. I have tried to remove BOOK_DELTA from the list of channels (and callbacks):
```
bitstamp = Bitstamp(channels=[L3_BOOK,],
                    symbols=["BTC-USD"],
                    callbacks={
                        L3_BOOK: book,
                    })
```
But now, the orderbook `book` that my callback receives is completely empty (i.e, `book == {}`). Is this normal behavior or am I doing something wrong?

**Comment by bmoscon** [comment]
You dont subscribe to the delta as a channel, you just provide a callback for it. So it would look something like this:

```python
f = FeedHandler()
bitstamp = Bitstamp(channels=[L2_BOOK],
                    symbols=["BTC-USD"],
                    callbacks={
                        L3_BOOK: book,
                        BOOK_DELTA: book,
                    })
f.add_feed(bitstamp)
```

But bitstamp doesnt support deltas on L3 books. They can be calculated, but this isnt supported for L3 books (maybe it will be in the future).
