### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by mfw78** [bmoscon/cryptofeed#426]
**Describe the bug**
Extended use of cryptofeed with Deribit exchange / Kafka backend results in memory leak, potentially in websocket connection, resulting in intermittent stream and no warning of connection timeout / buffer issues.

**To Reproduce**

* Configure a Kafka cluster
* Deploy [main.py](https://github.com/bmoscon/cryptofeed/files/6040121/main.txt)
 attached to Kubernetes cluster

From the screenshots below, it can be seen that normal data stream consumption should be at the rate of about 250kBps - 300kBps depending upon market volatility. The pipeline being used to consume cryptofeed data is:

cryptofeed ---> proxy kafka topic --> deduplicated by a faust app --> main kafka topic for consumption by other components.

When analysing the performance profile for the pipeline, the timestamp from the exchange was noted to be drifting from the current time, notably the exchange messages were advancing forward in their frame of reference, but not in real-time, suggesting an issue with the processing of the stream from the websocket. The `receipt_timestamp` published by cryptofeed to the Kafka topic was within 5ms of real-time, so that further suggests that this is more upstream in cryptofeed's processing of the websocket.

Notably, in the memory consumption screenshot below, at the peaks of 2021-02-25 00:36Z, 2021-02-24 11:48Z etc, these timestamps coincide with the last exchange timestamp emitted by cryptofeed to kafka, then the timestamp suddenly jumps forward and catches back up in sync.

The moment it catches back up in sync is at the trough of the memory usage, l imagine this would be when the buffer has been exhausted that was built up. The stack traces can be seen here, notably the most recent stack trace was the first time I've received and error 1000 code from the API.

Refer to stack traces here [log.txt](https://github.com/bmoscon/cryptofeed/files/6040162/log.txt)

I suspect that there's simply too much information coming down the socket and it needs to be horizontally scaled if it's to be deployed in Python.

**Expected behavior**
Exception to be raised when buffer fills to point that the websocket is no longer consuming from the socket.

**Screenshots**

![image](https://user-images.githubusercontent.com/53399572/109092822-2ee66d00-770f-11eb-9842-b6a81e660439.png)
![image](https://user-images.githubusercontent.com/53399572/109092849-3c9bf280-770f-11eb-822b-563c0267d937.png)
![image](https://user-images.githubusercontent.com/53399572/109092869-47568780-770f-11eb-815b-4bf6aa795030.png)
![image](https://user-images.githubusercontent.com/53399572/109092897-50475900-770f-11eb-9cc7-24cf3428a879.png)

**Operating System:**
 - Flatcar Linux Beta 2705.1.1 (docker 19.03.14, kernel 5.9.16, systemd 246)
 - Kubernetes v1.20.1
 - CNI Cilium v1.9.1

**Cryptofeed Version**
- Git commit e14d67768a5cdb7e27a42fefbd93014fab5d1c60

**Comment by mfw78** [comment]
Further to this I attempted to reduce the scale and simplify the setup to try to better isolate the issue. I implemented the following:

1. Replace Kafka with InfluxDB to simplify writing to the store.
2. Instead of searching for all futures instruments, I instead have simplified this by family ('BTC' in instrumentName, 'ETH' in instrumentName, etc). I therefore focused just on BTC and reduced the number of websocket channel subscriptions by 50%.

Doing the above yielded the same results, ie. significant lag between the exchange and cryptofeed (likely more from the websocket buffer to cryptofeed's handling).

I then thought I'd dial it back even further to see if I could get to a stable solution. On removing `L2_BOOK` and `BOOK_DELTA` subscriptions, the lag reduced to sub 15ms, instead of exponentially growing lag as indicated beforehand.

I understand there's a C implementation of the order book coming soon? :smile:

**Comment by mfw78** [comment]
Actually, this is really starting to confuse me. I just deployed the `HEAD` commit to the container with the InfluxDB code, and without the L2_BOOK / BOOK_DELTA subscriptions. Maybe in the previous comment, I hadn't let the processes run for long enough as the issue has started to recur. The following shows the last commit lines in the InfluxDB:

```
1614256130422766719 2.0      ETH-48618141 1618.95 1614256129.9059758 buy  ETH-PERPETUAL 1614253845.166
1614256133854312865 2187.0   ETH-48618133 1618.65 1614256133.8522093 buy  ETH-PERPETUAL 1614253843.64
1614256134742414898 41.0     ETH-48618142 1619.1  1614256134.7404556 buy  ETH-PERPETUAL 1614253845.286
1614256134993701780 6.0      ETH-48618143 1619.1  1614256134.7404556 buy  ETH-PERPETUAL 1614253845.286
```

The formatting for the columns in the measurement are as per cryptofeed's standard. No classes have been overridden. You will see in the last one that the exchange time versus the current time is out of sync by upwards of 38 mins. Any idea where to start to hunt this down? Ideally I'd like something that comes as close as possible to representing reality.

**Comment by bmoscon** [comment]
that doesnt surprise me (the last message). You have a single task reading, parsing, and writing. Assume the exchange sends you 1 message a second. If the read takes 0.1 seconds, the parse takes 0.1 seconds and the write to influx takes 1 second, you'll be adding 0.2 seconds per message. Trade data is very low volume (relatively) and the reading and parsing add negligible overhead, so the very likely culprit here is the influx write. When a task is blocked (like on a write) only other tasks can occur (i.e. if you have other feeds configured). A solution here could be to have all backends be their own independent tasks that read from a queue and write messages. I'll look into adding that to the roadmap for the next release. It will help, but there will always be scenarios where nothing will suffice (hardware too slow, misconfigurations, etc).

**Comment by bmoscon** [comment]
in regards to the other messages, definitely seems like a case of getting more data than it can process. the aforementioned solution will help here, as will the code changes coming to use a new orderbook. There is non memory leak though (at least not in cryptofeed). So far I only have python code, so thats not really possible. The websockets code is partially in C, so there could be one there, but it seems much more likely that queued messages are slowly building up. Eventually it will block until sufficient messages are drained. This can lead to a disconnect like you are seeing

**Comment by zhenpingfeng** [comment]
@mfw78 Have you used a low disk io cloud server? Most cloud vendors limit the frequency of hard disk read and write operations. I have tried the influxdb's backend on some resources-limited cloud servers, when the server performance is not enough, the influxdb backend does cause a very large latency. You can try to upgrade the hard drive of the server to high throughput one.

**Comment by zhenpingfeng** [comment]
You can check the disk IO. Most cloud service vendors will restrict disk read and write operations. If you are using a cloud server, it may be due to insufficient disk IO to cause data accumulation in memory.

**Comment by mfw78** [comment]
Thanks for the prompt feedback @bmoscon and @zhenpingfeng. I elected to instead migrate away from using Kafka and instead use cryptostore with ZMQ pass-through to an xpub-xsub consolidator.

The whole point I was trying to achieve was a consistent data feed, with the ability to deploy rolling updates to cryptofeed / cryptostore as well as being able to suffer a node outage without interruption to the feed.

Ultimately I settled on:

1. Deployment on Kubernetes with a replica count of 2 and a min availability of 25%. Pod antiaffinity configured to not deploy more than one cryptostore pod to a node. Embedded redis as a side container for cryptostore, though it's important to declare this container first with K8S pod lifecycle, otherwise the cryptostore container fails to start due to no redis connection as it's in the process of starting. Redis side container used on the local pod to eliminate inter-node network delay with redis writes.
2. Configure a readinessProbe on the cryptostore pod using simple grep command for 'Complete' that occurs after the first successful write to the storage.
3. Deployed a simple XPUB-XSUB aggregator node.js app to each node.
4. Modified cryptostore `collector.py` to allow to configure the ZMQ host / port via environment variable.
5. InfluxDB storage used for cryptostore.
6. Replicated proxy XPUB-XSUB aggregator node.js apps that connect to each node specific xpub-xsub aggregator.

As for handling the duplication issue, InfluxDB with cryptostore will automatically deduplicate (though override the receipt_timestamp, though this isn't that big a deal). Other consumers for the data feed (alpha strategies, portfolio etc) simply drop messages if the time is not greater than the previous message received, or in the case of subscribing to trades ZMQ topics, if the trade ID is not greater than the previous.

Taking this approach eliminated large complex components (Kafka) and significantly reduced CPU / Memory usage.

**Comment by bmoscon** [comment]
I'm going to close this - I've made a few changes to documentation and to the way the backends work (using a separate async task to handle backend writes). This should reduce the latency on the read side significantly. If there are more questions about this please re-open or create a new issue
