### ISSUE TITLE
Support for fetching candles?

### ISSUE THREAD

**Issue by peerchemist** [bmoscon/cryptofeed#427]
Does this library support subscribing to a new candle feed. Binance calles them "klines'.

**Comment by bmoscon** [comment]
no, it doesnt. You're the first person in over 3 years to ask about them so I'm not sure if its a data channel that is of widespread use or not. It can certainly be added

**Comment by bmoscon** [comment]
@peerchemist this has been added. Candles are now supported in Binance!

**Comment by peerchemist** [comment]
Thank you! I'll test shortly and report back.

**Comment by brizzbane** [comment]
Came here looking for answers of where "Candles" went in the demo.py (it can't be imported, so I assume it was removed).

This is total newb question, but candles are what show OHLC right?  and ticker is ..second by second..ticks?

I would like to have a feed for both ticker, and OHLC data on a minute basis.  Is candles what I'm wanting?

**Comment by bmoscon** [comment]
@brizzbane there is a candle example here:

https://github.com/bmoscon/cryptofeed/blob/e03d472cf2c10d39e991b21b4c937df882f9f15e/examples/demo.py#L107

candles show open, close, high, low, volume, trades and other information for a time interval. A ticker is usually an indication of price by side (bid/ask) that is updated whenever one of those changes.

**Comment by brizzbane** [comment]
Thank you!

Is this https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#individual-symbol-ticker-streams

Data apart of the current program? ("e": "24hrTicker",)

**Comment by brizzbane** [comment]
Nevermind about above.

I want to say though, the reason I had issues with  CandleCallback not being found is because it doesn't seem to be in the latest version installed by pip.  I had to do pip install git+https://github.com/bmoscon/cryptofeed

**Comment by bmoscon** [comment]
yep. if you see changes in the changelog under a version that doesnt have a date associated with it, those are unreleased changes
