### ISSUE TITLE
Support Dydx Websocket

### ISSUE THREAD

**Issue by Jay54520** [bmoscon/cryptofeed#429]
Doc: https://docs.dydx.exchange/#v3-websocket-api

[Dydx](https://trade.dydx.exchange/margin/ETH-DAI) is a decentralized exchange which has 10M volume per according to [coingekco](https://www.coingecko.com/en/exchanges/dydx).

**Comment by bmoscon** [comment]
done

**Comment by mchangun** [comment]
Can we add support to the private websocket channels too?

https://docs.dydx.exchange/#accounts-channel
