### ISSUE TITLE
real-time data retrieval from Binance

### ISSUE THREAD

**Issue by jeans-all** [bmoscon/cryptofeed#430]
Hi,

I recently tried to retrieve real-time ticker data from Binance, but it found that cryptofeed only gets data with update delay (like 100 or 1000ms).

So I wonder if you can include following two websocket stream as in an option for Binance channel? 

Individual Symbol Book Ticker Streams
All Book Tickers Stream

Those two are the only tickers that provide real-time data.

https://binance-docs.github.io/apidocs/spot/en/#all-market-tickers-stream

Thanks in advance, 
Jeansall

**Comment by bmoscon** [comment]
fixed. I changed ticker to use bookTicker
