### ISSUE TITLE
GateioV4 api support

### ISSUE THREAD

**Issue by walter211** [bmoscon/cryptofeed#438]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support GateIo V4 API Version

**Describe alternatives you've considered**
cause V3 already supported, so nothing else

**Additional context**
None

**Comment by walter211** [comment]
FYI

https://github.com/gateio/gateapi-python

**Comment by bmoscon** [comment]
@walter211 thanks for the request. I'm currently implementing this - done with trades and tickers, need to add support for their new orderbook stream and candles and then will merge it (by end of week). Thanks for the request!

**Comment by bmoscon** [comment]
done
