### ISSUE TITLE
Huobi, Binance, Okex. Not to get funding rate from different swaps

### ISSUE THREAD

**Issue by bandito1** [bmoscon/cryptofeed#440]
**Describe the bug**
Hello,
When I subscrime to the funding channel, I get only one of Coin or USD based swap's funding rate is rhapsodic.
Binance I get the USDT based funding rate, Okex I get coin based funding ratre, Huobi_swap get USDT based again.
When I checked the symbol list in debug, not found separated swap/future like BTC-USD (coin based) BTC-USDT (USD based).
Can you include to get the USD or Coin based funding rates separate?

thanks,
Bandito
**Operating System:**
 - Win10

**Cryptofeed Version**
- 1.7.0

**Comment by bmoscon** [comment]
I'm not positive I understand what the issue is. Can you try explaining it a different way?

**Comment by bmoscon** [comment]
no response, bug unclear, closing
