### ISSUE TITLE
Binance Websocket Question

### ISSUE THREAD

**Issue by hertzC** [bmoscon/cryptofeed#441]
Hi,

First of all, I am new to this library but this is an amazingly useful library to get into the crypto world.  Thanks for the great project!

I have a dummy question when testing some of the example in the demo.py.

I tried to get the ticker BTC-USDT from both Binance and BinanceFutures, but I only got the response from the Binance_Futures and no response from the Binance. Do you guys run into the same issue or am I missing anything here?

Thanks!

```python

async def ticker(feed, symbol, bid, ask, timestamp, receipt_timestamp):
      print(f'Timestamp: {timestamp} Feed: {feed} Pair: {symbol} Bid: {bid} Ask: {ask}')
     
f = FeedHandler()
f.add_feed(Binance(symbols=['BTC-USDT'], channels=[TICKER], callbacks={TICKER: ticker}))
f.add_feed(BinanceFutures(symbols=['BTC-USDT'], channels=[TICKER], callbacks={TICKER: ticker}))
f.run() 
```

**Comment by bmoscon** [comment]
I get a response from both when I run that exact same code:

```
Timestamp: 1616017485.374 Feed: BINANCE_FUTURES Symbol: BTC-USDT Bid: 58419.33 Ask: 58419.34
Timestamp: 1616017485.474 Feed: BINANCE_FUTURES Symbol: BTC-USDT Bid: 58419.33 Ask: 58419.34
Timestamp: 1616017485.494385 Feed: BINANCE Symbol: BTC-USDT Bid: 58367.83000000 Ask: 58371.81000000
Timestamp: 1616017485.5016682 Feed: BINANCE Symbol: BTC-USDT Bid: 58367.83000000 Ask: 58371.29000000
Timestamp: 1616017485.5144 Feed: BINANCE Symbol: BTC-USDT Bid: 58367.83000000 Ask: 58371.29000000
```

Can you try it again? Is there a reason Binance would be blocking or rate limiting you?

**Comment by bmoscon** [comment]
It works for me, even with a subscription to all symbols. I'm not sure what version you are using, please update your code and try again.
