### ISSUE TITLE
"This event loop is already running"

### ISSUE THREAD

**Issue by nickthorpie** [bmoscon/cryptofeed#446]
**Describe the bug**
Regardless of what I try, I keep running to an exception raised from asyncio that says "This event loop is already running. 

** Steps to reproduce the behavior**

Here's the code I'm running, super bare bones:
`from cryptofeed import FeedHandler
from cryptofeed.defines import VOLUME
from cryptofeed.exchanges import Poloniex

async def volume(**kwargs): print(f"Volume: {kwargs}")

fh = FeedHandler()
fh.add_feed(Poloniex(symbols=['BTC-ETH'], channels=[VOLUME],callbacks={VOLUME:volume}))
fh.run()`

Here's our traceback:

`RuntimeError                              Traceback (most recent call last)
<ipython-input-40-1f14e8b42f49> in <module>
----> 1 fh.run()

~/opt/anaconda3/envs/condaNT374/lib/python3.7/site-packages/cryptofeed/feedhandler.py in run(self, start_loop, install_signal_handlers)
    268             LOG.exception('FH: Unhandled %r - shutting down', why)
    269         finally:
--> 270             self.stop(loop=loop)
    271             self.close(loop=loop)
    272 

~/opt/anaconda3/envs/condaNT374/lib/python3.7/site-packages/cryptofeed/feedhandler.py in stop(self, loop)
    293 
    294         LOG.info('FH: wait %s backend tasks until termination', len(shutdown_tasks))
--> 295         loop.run_until_complete(asyncio.gather(*shutdown_tasks))
    296 
    297     def close(self, loop=None):

~/opt/anaconda3/envs/condaNT374/lib/python3.7/asyncio/base_events.py in run_until_complete(self, future)
    564         future.add_done_callback(_run_until_complete_cb)
    565         try:
--> 566             self.run_forever()
    567         except:
    568             if new_task and future.done() and not future.cancelled():

~/opt/anaconda3/envs/condaNT374/lib/python3.7/asyncio/base_events.py in run_forever(self)
    519         self._check_closed()
    520         if self.is_running():
--> 521             raise RuntimeError('This event loop is already running')
    522         if events._get_running_loop() is not None:
    523             raise RuntimeError(

RuntimeError: This event loop is already running`

This also happens when I run .close(), .stop(), etc.

**Operating System:**
 - macOS, conda 4.9.2, in a Conda environment running python 3.7.4

**Cryptofeed Version**
- 1.7.0 installed using:
   - conda install git pip
   - pip install git+git://github.com/bmoscon/cryptofeed@master

**Comment by bmoscon** [comment]
ipython/jupyter notebooks use asyncio, so you cant run from those.

**Comment by TnzGit** [comment]
> 

I ran into the same issue outside jupyter notebook. The root of this issue is nested asyncio. The solution is to use [nest-asyncio](https://pypi.org/project/nest-asyncio/).

`import nest_asyncio
nest_asyncio.apply()`
