### ISSUE TITLE
Hitting Rate Limit on BitMEX

### ISSUE THREAD

**Issue by quazzuk** [bmoscon/cryptofeed#447]
**Describe the bug**
Subscribing to multiple channels (in my case 6: l2_book, funding, open_interest, liquidations, ticker and trades causes the following message:

server rejected WebSocket connection: HTTP 429
2021-03-19 09:15:06,081 : WARNING : BITMEX-294cef: Rate Limited - waiting 60 seconds to reconnect

And then repeated failed retries.

**To Reproduce**
I used cryptostore to configure the feed to subscribe to all available BitMEX channels

**Fix**
I think the issue is caused by the [lines](https://github.com/bmoscon/cryptofeed/blob/5d756df666e551834e3e8c0facac540df8a72239/cryptofeed/feedhandler.py#L256) in `run` and `add_feed_running` where `create_task` is used call `self._connect` in a loop across each subscription. This in turn causes the requests to be fired out in quick succession with the latter ones being rejected as 429. 

I've worked around this on my local branch by creating a delay decorator and wrapping the self._connect with delay and setting the delay time based on the loop counter. Not sure whether this is the best solution or whether there is a more appropriate rate throttling mechanism to reuse. 

Thoughts?
Andy

**Comment by bmoscon** [comment]
Are you subscribing to a large number of symbols?

**Comment by quazzuk** [comment]
yes, all available symbols via a wildcard mechanism I've added support for locally. I'm also doing the same on other exchanges and running into similar problems, especially bitfinex which also limits the number of connections per minute. I was just wondering whether there is some library code to manage communication with the exchange, respecting the various exchange specific rate throttling and connection limits? Perhaps an exchange/connection queue mechanism?

Apart from this though, I'm able to collect trades and quotes/ticker on all symbols across around 15 exchanges which is super useful. I really appreciate that you open sourced the project and I will look to contribute any changes that might be more generally useful, as PRs.

Thanks!

**Comment by dirtyValera** [comment]
@quazzuk Do to you think you can't send PR with the fix? I think I'm having a similar problem. 

What other exchanges do you hit rate limits on?

**Comment by quazzuk** [comment]
@dirtyValera - it was more of a hack/workaround than a fix as I don't think it solves the problem completely, just spaces out some of the subscriptions. Essentially I added the following function to `cryptofeed/feedhandler.py`

```
def delay(delay, f):
    @functools.wraps(f)
    async def wrapper(*args, **kwargs):
        await asyncio.sleep(delay)
        return await f(*args, **kwargs)

    return wrapper
```

and then modified `run` as follows

```
 for feed, timeout in self.feeds:
            for i, (conn, sub, handler) in enumerate(feed.connect()):
                conn.set_raw_data_callback(self.raw_message_capture)
                loop.create_task(delay(1 + i, self._connect)(conn, sub, handler))
                self.timeout[conn.uuid] = timeout
                feed.start(loop)
```

**Comment by bmoscon** [comment]
fixed. I added a `delay_start` to the exchange feeds that you can use to stagger these if needed
