### ISSUE TITLE
Binance - Authenticated Websocket

### ISSUE THREAD

**Issue by ghazaryanartashes** [bmoscon/cryptofeed#448]
Hi,
Thanks for the great lib. I am new to cryptofeed and wanted to understand if it is possible to get only PERSONAL TRADES via WebSocket on Binance.

Thanks in advance.

**Comment by bmoscon** [comment]
this is currently not supported. Will be supported at some point. I do welcome PRs!

**Comment by Dynamikey** [comment]
@bmoscon I commented on a separate PR but I have this in my forked repo. I can raise a PR to merge the change in.

**Comment by bmoscon** [comment]
@Dynamikey go for it!

**Comment by Dynamikey** [comment]
This is done now! https://github.com/bmoscon/cryptofeed/pull/601
