### ISSUE TITLE
Example for storing orderbook in Postgress

### ISSUE THREAD

**Issue by elyase** [bmoscon/cryptofeed#449]
I was looking at the examples and it is not clear how to create the table to save the orderbook in postgress. Could you provide some hints?

**Comment by bmoscon** [comment]
an example for this doesnt exist, but I can add one at some point

**Comment by idclevxx** [comment]
Might I suggest the example assumes the user already has a table (and password details etc), which will be the norm in 99 percent of the cases as these tables are frequently heavily customized with unique constraints, data retention policies and so on. Creating a table in postgresql isn't harder than googling it.

**Comment by idclevxx** [comment]
> I was looking at the examples and it is not clear how to create the table to save the orderbook in postgress. Could you provide some hints?

Check out [this](https://www.postgresqltutorial.com/postgresql-create-table/) site for anything postgres related.

**Comment by bmoscon** [comment]
done
