### ISSUE TITLE
Cannot subscribe correct symbol from bybit

### ISSUE THREAD

**Issue by leonwang893** [bmoscon/cryptofeed#459]
**Describe the bug**
I am trying to subscribe BTCUSD's trade data however it return me BTCUSD0625's data

**Expected behavior**
It should return me BTCUSD's data.

**Screenshots**
![image](https://user-images.githubusercontent.com/15900133/113336178-f1ee4580-9360-11eb-920c-47f8f4eb9990.png)

**Operating System:**
 - win10
 - python 3.7

**Cryptofeed Version**
- 1.7.0

**Comment by bmoscon** [comment]
please use the version in master, this has been fixed but not released yet

**Comment by leonwang893** [comment]
> please use the version in master, this has been fixed but not released yet

Fixed, Thanks for you help!
