### ISSUE TITLE
rest feed api not clear

### ISSUE THREAD

**Issue by bmoscon** [bmoscon/cryptofeed#46]
rest feeds started with a common interface but recent contributions from others have muddied the waters. need to clean up the calls and make them standard across exchanges

**Comment by bmoscon** [comment]
- [ ] coinbase
- [ ] kraken
- [ ] bitmex
- [ ] bitfinex
- [ ] gemini
- [ ] poloniex

**Comment by evanatyourservice** [comment]
If I wrote one for Binance would you like me to use bitfinex as a template? I don't want to write something and not have it be usable. I at least can see the normalization between bitmex and bitfinex.

**Comment by bmoscon** [comment]
yes. bitmex and bitfinex are pretty good for public data. i have the interface defined in https://github.com/bmoscon/cryptofeed/blob/rest-work/cryptofeed/rest/api.py but the non public part is open to change

**Comment by bmoscon** [comment]
@evanatyourservice any progress on this? Anything I can help with? :D
