### ISSUE TITLE
Poor performance during `loop.create_task(self._connect)`

### ISSUE THREAD

**Issue by tristan-murfitt-elw** [bmoscon/cryptofeed#461]
I'm experiencing frequent and significant blocking of the event loop, with task times taking anywhere from `0.1` to `15` seconds.

Running 20 symbols from 3 exchanges `{'binance': 11, 'kraken': 3, 'coinbase': 6}` and subscribing to `TICKER, TRADES, CANDLES, L2_BOOK, BOOK_DELTA, OPEN_INTEREST, LIQUIDATIONS` (if available).

All warnings appear to stem from:
- `feedhandler.py:257` - which does the `loop.create_task(self._connect(conn, sub, handler))` in `FeedHandler.run()` 
- `feedhandler.py:351` - which does `await self._handler(connection, handler)` in `_connect()`

```
WARNING:Executing <Task pending coro=<FeedHandler._connect() running at /cryptofeed/feedhandler.py:351> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff020dbc490>()] created at /python3.7/asyncio/tasks.py:460> created at /cryptofeed/feedhandler.py:257> took 0.353 seconds
WARNING:Executing <Task pending coro=<FeedHandler._connect() running at /cryptofeed/feedhandler.py:351> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff020ed14d0>()] created at /python3.7/asyncio/queues.py:118> created at /cryptofeed/feedhandler.py:257> took 0.238 seconds
WARNING:Executing <Task pending coro=<FeedHandler._connect() running at /cryptofeed/feedhandler.py:351> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff020f5f110>()] created at /python3.7/asyncio/queues.py:118> created at /cryptofeed/feedhandler.py:257> took 11.062 seconds
```

This is far more noticeable when I (intentionally) trigger some connection issues, such as failed SSL **only on 1 of the 3 exchanges (Kraken)**. I _think_ this means the blocking task comes from failure to connect to feeds. Is there a way this can be debugged further?
```
2021-04-02 17:21:32,852 : WARNING : KRAKEN-0817e1: encountered connection issue [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091) - reconnecting...
Traceback (most recent call last):
  File "/python3.7/site-packages/cryptofeed/feedhandler.py", line 344, in _connect
    async with conn.connect() as connection:
  File "/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/python3.7/site-packages/cryptofeed/connection.py", line 66, in connect
    self.conn = await websockets.connect(self.address, **self.kwargs)
  File "/python3.7/site-packages/websockets/client.py", line 535, in __await_impl__
    transport, protocol = await self._create_connection()
  File "uvloop/loop.pyx", line 2062, in create_connection
  File "uvloop/loop.pyx", line 2057, in uvloop.loop.Loop.create_connection
  File "uvloop/sslproto.pyx", line 517, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 499, in uvloop.loop.SSLProtocol._do_handshake
  File "/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)

ERROR:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff759040210>
source_traceback: Object created at (most recent call last):
  File "/python3.7/site-packages/cryptofeed/feedhandler.py", line 344, in _connect
    async with conn.connect() as connection:
  File "/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/python3.7/site-packages/cryptofeed/connection.py", line 61, in connect
    self.session = aiohttp.ClientSession()
```

Environment:
- PYTHONASYNCIODEBUG = 1
- Python 3.7.10
- cryptofeed 1.8.2
- asyncio 3.4.3
- Mac OS 10.15
- 500mbps internet (so unlikely to be the cause)

**Comment by bmoscon** [comment]
There isnt anything specific in cryptofeed for the websocket connecting, it uses the websockets library, which is quite performant. Depending on how you have your stuff configured, a failure on a connection will definitely block things. See: https://github.com/bmoscon/cryptofeed/blob/master/docs/performance.md

**Comment by bmoscon** [comment]
@tristan-murfitt-elw if you have other questions or concerns, please let me know

**Comment by tristan-murfitt-elw** [comment]
@bmoscon thank you

**Comment by slidenerd** [comment]
Stupid question given the title, how do you determine how much data you can load safely and what would be the signs you are overdoing it? For example, if you load the order book of every symbol from every exchange, obviously a t3.micro instance on AWS wont be sufficient for it, so what happens? CPU usage goes to 100%, if not how do you determine the limits?
