### ISSUE TITLE
Can't call self.get_instruments() from the constructor of Derebit Feed

### ISSUE THREAD

**Issue by sydx** [bmoscon/cryptofeed#462]
I'm trying to run the following script:

<pre>
import decimal

import cryptofeed
import cryptofeed.defines
import cryptofeed.exchanges

fh = cryptofeed.FeedHandler()

async def ticker(feed, symbol, bid, ask, timestamp, receipt_timestamp):
    mid = decimal.Decimal.from_float(.5) * (bid + ask)
    print(f'Timestamp: {timestamp} Feed: {feed} Symbol: {symbol} Mid: {mid}')

print(cryptofeed.exchanges.Deribit.info()['symbols'])

fh.add_feed(cryptofeed.exchanges.Deribit(symbols=['BTC-25JUN21-50000-C'], channels=[cryptofeed.defines.TICKER], callbacks={cryptofeed.defines.TICKER: ticker}))

fh.run()
</pre>

Unfortunately, the result is

<pre>
Traceback (most recent call last):
  File "crypto_options.py", line 15, in <module>
    fh.add_feed(cryptofeed.exchanges.Deribit(symbols=['BTC-25JUN21-50000-C'], channels=[cryptofeed.defines.TICKER], callbacks={cryptofeed.defines.TICKER: ticker}))
  File "C:\Programs\Win64\Anaconda\V2020.07_3.8\lib\site-packages\cryptofeed\exchange\deribit.py", line 24, in __init__
    instruments = self.get_instruments()
AttributeError: 'Deribit' object has no attribute 'get_instruments'
</pre>

This is fixed by commenting out the lines in the constructor in `cryptofeed\exchange\deribit.py` as follows:

<pre>
    def __init__(self, **kwargs):
        super().__init__('wss://www.deribit.com/ws/api/v2', **kwargs)

        # TODO: the same verification (below) is done in Bitmex => share this code in a common function in super class Feed
        """
        instruments = self.get_instruments()
        pairs = None
        if self.subscription:
            subscribing_instruments = list(self.subscription.values())
            pairs = [pair for inner in subscribing_instruments for pair in inner]

        for pair in set(self.symbols or pairs):
            if pair not in instruments:
                raise ValueError(f"{pair} is not active on {self.id}")
        """
        self.__reset()
</pre>

It appears that it is impossible to call `self.get_instruments()` from this constructor.

Hope this helps,

Paul

**Comment by bmoscon** [comment]
get_instruments no longer exists, use the info method instead.

**Comment by sydx** [comment]
I don't call get_instruments from my code. It is called from the constructor of the Deribit exchange, which means that I can't call that constructor. The call to get_instruments is found here: 

https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/exchange/deribit.py

**Comment by bmoscon** [comment]
fixed in master

**Comment by sydx** [comment]
Thank you very much!
