### ISSUE TITLE
Milliseconds of BitMex timestamps are interpreted as microseconds

### ISSUE THREAD

**Issue by agijsberts** [bmoscon/cryptofeed#466]
**Describe the bug**
The timestamp format of BitMex (and other exchanges) include milliseconds as fractional after the dot. However, these are interprete as microseconds, causing an error of up to 900ms. For instance, the raw json for a trade
```json
{"timestamp":"2021-04-07T20:23:44.305Z","symbol":"XBTUSD","side":"Buy","size":235,"price":55863.5,"tickDirection":"ZeroPlusTick","trdMatchID":"244baabf-b364-38a0-937e-16a398db679e","grossValue":420650,"homeNotional":0.0042065,"foreignNotional":235}
```
becomes after processing
```json
{"feed": "BITMEX", "symbol": "BTC-USD", "timestamp": 1617827024.000305, "receipt_timestamp": 1617827032.5444775, "side": "buy", "amount": 235.0, "price": 55863.5, "id": "244baabf-b364-38a0-937e-16a398db679e", "order_type": None}
```

**To Reproduce**
The bug appears to originate in the parsing behavior of `yapic.json`:
```python
>>> from yapic import json
>>> json.loads('{"timestamp":"2021-04-07T20:23:44.305Z"}')
{'timestamp': datetime.datetime(2021, 4, 7, 20, 23, 44, 305, tzinfo=datetime.timezone.utc)}
```
The interpretation of the fractional is perhaps somewhat arguable (implied leading or trailing zeros), but if preferable I can take this issue also upstream.

**Operating System:**
Linux

**Cryptofeed Version**
Install from source, commit https://github.com/bmoscon/cryptofeed/commit/41b07e76ae773d50eb537cfbaf157b7d7137bcfa

**Comment by bmoscon** [comment]
this appears to be an issue with yapic.json. If you want to raise the issue there, that would be great. If not I can raise the issue. Its easily shown to be incorrect:

```python
 from datetime import datetime as dt

print(dt(2021, 4, 7, 20, 23, 44, 305).isoformat())


output: '2021-04-07T20:23:44.000305'
```

**Comment by agijsberts** [comment]
No problem, I'll raise the error there and (hopefully) get it fixed upstream.

**Comment by bmoscon** [comment]
the maintainer has been very responsive to me in the past, so 🤞

**Comment by agijsberts** [comment]
All done! The issue is fixed upstream (https://github.com/zozzz/yapic.json/pull/12).
