### ISSUE TITLE
Binance connection fails for multiple symbols/channels

### ISSUE THREAD

**Issue by tristan-murfitt-elw** [bmoscon/cryptofeed#467]
**Describe the bug**
When connecting to Binance with multiple symbols **or** multiple channels, the connection string is incorrect and fails in an infinite loop.

**To Reproduce**
```
add_feed(
  Binance(symbols=['LTC-BTC', 'BNB-ETH'], channels=['ticker'])
)
```
Exception is caught (and not handled) in `feedhandler._connect`. Logging the `conn.address` reveals there is a problem with the WS connection string:
```py
print(e)  # InvalidStatusCode('server rejected WebSocket connection: HTTP 400')
print(conn.address)  # wss://stream.binance.com:9443/stream?streams=ltcbtc@bookTicker/bnbeth@ltcbtc@bookTicker/
```
Note the above has `bnbeth@ltcbtc`.

If we add a second channel the string becomes more malformed:
```
wss://stream.binance.com:9443/stream?streams=ltcbtc@depth@100ms/bnbeth@ltcbtc@depth@100ms//ltcbtc@bookTicker/bnbeth@ltcbtc@bookTicker/
```
Note the above has `//` which is incorrect.

Finally, this exception handler (`except InvalidStatusCode as e:`) never increments the retries counter so it continues to fail infinitely.

**Expected behavior**
- Construct the correct WS connection string when there are multiple tickers or multiple channels.
- Increment the retries flag to prevent infinite loop

**Operating System:**
MacOS

**Cryptofeed Version**
master branch

**Comment by tristan-murfitt-elw** [comment]
It's also worth noting:

There is no warning log for this under the new `FeedHandler(exception_ignore=None)` (default) args, so it's hard to spot when a connection is failing for this reason.

The default for `self.exceptions` is `None` so the below fails silently:
```py
            except InvalidStatusCode as e:
                print(conn.address)  # mangled conn address
                if self.exceptions:
                    for ex in self.exceptions:
                        if isinstance(e, ex):
                            LOG.warning("%s: encountered exception %s, which is on the ignore list. Raising", conn.uuid, str(e))
                            raise
                if e.status_code == 429:
                    LOG.warning("%s: Rate Limited - waiting %d seconds to reconnect", conn.uuid, rate_limited * 60)
                    await asyncio.sleep(rate_limited * 60)
                    rate_limited += 1
```

**Comment by bmoscon** [comment]
thanks for the report. Sorry this one slipped by and thanks for raising the issue about the exception handling as well. All have been fixed - thanks!

**Comment by tristan-murfitt-elw** [comment]
Excellent, thank you for resolving so promptly!

**Comment by bmoscon** [comment]
Sure - I tested with your examples and some others of my own - hopefully I havent missed anything. If I have please re-open or create a new ticket.

**Comment by bmoscon** [comment]
@tristan-murfitt-elw - ngl, after I fixed this I found another one, which I also fixed yesterday. I put in a unit test around the binance address generation, so hopefully it never comes up again. Sorry for the churn :|
