### ISSUE TITLE
Authneticated Channels  support binance

### ISSUE THREAD

**Issue by walter211** [bmoscon/cryptofeed#468]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
add binance Authneticated Channels support

**Describe alternatives you've considered**
none

**Additional context**
https://binance-docs.github.io/apidocs/delivery/en/#user-data-streams

**Comment by Dynamikey** [comment]
I've actually got this working on a separate branch. I can raise a PR to merge this in.

**Comment by bmoscon** [comment]
@Dynamikey  - yes please

**Comment by Dynamikey** [comment]
This is done now! https://github.com/bmoscon/cryptofeed/pull/601
