### ISSUE TITLE
Binance Stream List Error

### ISSUE THREAD

**Issue by ziegi** [bmoscon/cryptofeed#470]
**Describe the bug**
This relates to exchange/binance.py
Version v1.8.2 0s working fine for me
The actual master version from April, 7, has a wrong concatenation syntax.
It produces: 
wss://stream.binance.com:9443/stream?streams=ltcbtc@ethbtc@bookTicker
instead of 
wss://stream.binance.com:9443/stream?streams=ltcbtc/ethbtc@bookTicker

**Comment by bmoscon** [comment]
this was reported by someone else yesterday and has been fixed: https://github.com/bmoscon/cryptofeed/issues/467

**Comment by bmoscon** [comment]
if you think this has been closed in error, please provide the commit hash you are using (multiple commits went in on April 7th) and a reproducible example
