### ISSUE TITLE
OKEx Liquidations channel bug

### ISSUE THREAD

**Issue by tristan-murfitt-elw** [bmoscon/cryptofeed#471]
**Describe the bug**
Just a quick one - noticed these errors in the OKEx liquidations channel.

```
Task exception was never retrieved
future: <Task finished coro=<OKEx._liquidations() done, defined at cryptofeed/cryptofeed/exchange/okex.py:34> exception=KeyError(0) created at python3.7/asyncio/tasks.py:351>
source_traceback: Object created at (most recent call last):
  File "market/services/fh_cryptofeed/_cf_perf.py", line 53, in main3
    fh.run()
  File "cryptofeed/cryptofeed/feedhandler.py", line 252, in run
    loop.run_forever()
  File "cryptofeed/cryptofeed/feedhandler.py", line 345, in _connect
    await subscribe(connection)
  File "cryptofeed/cryptofeed/exchange/okex.py", line 76, in subscribe
    asyncio.create_task(self._liquidations(pairs))  # TODO: use HTTPAsyncConn
  File "python3.7/asyncio/tasks.py", line 351, in create_task
    return loop.create_task(coro)
Traceback (most recent call last):
  File "cryptofeed/cryptofeed/exchange/okex.py", line 51, in _liquidations
    if len(data) == 0 or (len(data) > 0 and last_update.get(pair) == data[0]):
KeyError: 0
```

**To Reproduce**
This happens almost immediately when running something simple like:
```py
def main():
    """ Multi-feed no loop """
    fh = FeedHandler(retries=3)
    channels = [L2_BOOK, TICKER, TRADES]

    cbs = {TICKER: TickerCallback(ignore), TRADES: TradeCallback(trade), L2_BOOK: BookCallback(ignore), LIQUIDATIONS: LiquidationCallback(ignore)}

    fh.add_feed(Binance(symbols=['BTC-USDT', 'LTC-BTC', 'ETH-BTC', 'ADA-BTC'], cross_check=True, channels=channels, callbacks=cbs))
    fh.add_feed(OKEx(symbols=['LTC-USDT', 'ETH-USDT', 'BTC-USDT', 'ETH-BTC'], cross_check=True, channels=channels + [LIQUIDATIONS], callbacks=cbs))
    fh.run()
```

**Cryptofeed Version**
latest (master)

**Comment by tristan-murfitt-elw** [comment]
Unrelated, but I've set `cross_check=True` here because OKEx is also raising `BidAskOverlapping` error a lot for `ETH-USDT` (can be seen occasionally in the above reproducible example).

**Comment by tristan-murfitt-elw** [comment]
**OKEx bugs**
Apologies, found another bug during the OKEx processing.

Using the same reproducible code above, I occasionally see:
```
Traceback (most recent call last):
  File "cryptofeed/cryptofeed/feedhandler.py", line 346, in _connect
    await self._handler(connection, handler)
  File "cryptofeed/cryptofeed/feedhandler.py", line 397, in _handler
    await handler(message, connection, self.last_msg[connection.uuid])
  File "cryptofeed/cryptofeed/exchange/okcoin.py", line 247, in message_handler
    await self._book(msg, timestamp)
  File "cryptofeed/cryptofeed/exchange/okcoin.py", line 193, in _book
    if price in self.l2_book[pair][s]:
KeyError: 'BTC-USDT'
```

To summarise, we have:
1. Liquidations channel `KeyError`
2. OrderBook `BidAskOverlapping` error
3. OrderBook `KeyError`

**Comment by bmoscon** [comment]
I fixed the liquidations issues. there were some other problems there as well. In regards to 2 and 3, I never saw 3, but I did see 2. I turned on checksum validation and I can see that ever few hundred updates there is a missing message. Not sure there is anything the library can do other than what it does, which is reset the book and connection. I'd attribute the issue to the exchange. Its possible there is a bug in the orderbook processing, but I'd expect to see the issue every update if that were the case.

**Comment by bmoscon** [comment]
I will review the docs in regards to the book processing to confirm that nothing has changed and that the code looks good

**Comment by bmoscon** [comment]
I reviewed the docs, I dont see anything amiss. I re-ran the code with checksum validation enabled and didnt see any issues, so the issue (at least from what I can see) seems intermittent, which definitely seems like an exchange/connectivity issue

**Comment by tristan-murfitt-elw** [comment]
@bmoscon thank you for looking into this

Small request: is it possible to selectively apply the liquidations callback depending on the symbol, instead of raising an exception [here](https://github.com/bmoscon/cryptofeed/commit/2ff0c6a65f9837107be06f993b640540f4a6a4b0#diff-1fb586edd1f49508d984fc7d2852f440f54953f4f8ac81bbc48f0241e8823187R43)? I suspect a lot of users provide mixture of spot and derivatives symbols in a single subscription so would be great if the lib could manage this

**Comment by bmoscon** [comment]
There is a way to do that, use the subscription dictionary and specify channels with specific pairs applied to them.
