### ISSUE TITLE
Async I/O Pausing Feed

### ISSUE THREAD

**Issue by jamesmundy** [bmoscon/cryptofeed#48]
I'm currently working on some code to save Level 2 information to a local Postgres database. Each update to the order book comes with a lot of information so I definitely need to do some work on compressing this and speeding up the I/O operation but I have noticed that the feed is not accepting or queuing updates while the operation is being processed.

I've discovered this comment:
```
# Examples of some handlers for different updates. These currently don't do much.
# Handlers should conform to the patterns/signatures in callback.py
# Handlers can be normal methods/functions or async. The feedhandler is paused
# while the callbacks are being handled (unless they in turn await other functions or I/O)
# so they should be as lightweight as possible
```

https://github.com/bmoscon/cryptofeed/blob/master/examples/demo.py

I was wondering what is meant by: `(unless they in turn await other functions or I/O)`? My code is using `asyncpg`to write to the database. The feed and the method calling it are also async so am I right in thinking it should not be paused?

Apologies for what is most likely a basic question, I'm fairly new to Python and it seems Coinbase updates are multiple times a second so I might have to save a snapshot of the orderbook to the database at more feasible schedules.

**Comment by bmoscon** [comment]
yeah so asyncio in python is single threaded. There can be many coroutines/tasks "running" but really only one is running and it will run until you `await` something else. So the callbacks should either do something minimal or they should be async and in turn `await` something else. I'm not familiar with `asyncpg`, but if you have to `await` the write or insert command, that should be what you are looking for. The name also leads me to believe its async. I'll be implementing a postgres backend handler, which would handle all postgres updates. The backends let you limit orderbooks by depth, so you can save only the top N levels. You can also subscribe to the delta channel which will only send orderbook  delta updates (much less information). 


Does that answer all the questions?

**Comment by jamesmundy** [comment]
Yes, that helps Bryant, thanks a lot - the library has saved me a lot of time so thanks for the time you'be put into it!
