### ISSUE TITLE
Add testnet option

### ISSUE THREAD

**Issue by Pcsl** [bmoscon/cryptofeed#495]
Many exchanges have a testnet where you can try transactions and that becomes very handy when building a script or bot. However, as long as I am concerned Cryptofeed doesn't let you choose subscriptions to this kind of networks.

If possible it would be great to have this added. If not directly, it would be helpful also to "take out" the endpoints from the exchange in a specific class so we can inherit the class easily and just modify the endpoint URL. I tried doing it with the class Bitmex(Feed) but I would have to copy hundreds of line to my script and it's something I prefer not to do to make my code clearer to read.

Apart from that, thank you for your hard work you put into helping the community!

**Comment by bmoscon** [comment]
this is supported, see:

https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/feed.py#L66

and https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/exchange/gemini.py#L38


so, if an exchange is missing the url, you can open a PR to add it
