### ISSUE TITLE
Starting the feedhandler in another thread

### ISSUE THREAD

**Issue by mchangun** [bmoscon/cryptofeed#502]
I'm starting to learn how to use `cryptofeed` and wanted to start with a simple example.  I want to start a feedhandler in a new thread and have my current thread just print the best bid / best offer every two seconds:

```
from time import sleep
from threading import Thread

from cryptofeed import FeedHandler
from cryptofeed.exchanges import FTX
from cryptofeed.defines import L2_BOOK


class TestApp:
    def __init__(self, symbols: list):
        self.coin_book: dict = {}
        self.symbols = symbols

    async def book_update(self, feed, symbol, book, timestamp, receipt_timestamp):
        self.coin_book = book

    def start_feed(self):
        fh = FeedHandler()
        fh.add_feed(FTX(symbols=self.symbols, channels=[L2_BOOK], callbacks={L2_BOOK: self.book_update}))
        t = Thread(target=fh.run, daemon=True)
        t.start()

    def display(self):
        print('bid', self.coin_book['bid'].peekitem(-1))
        print('ask', self.coin_book['ask'].peekitem(0))

    def run(self):
        self.start_feed()

        while True:
            sleep(2)
            self.display()


if __name__ == '__main__':
    app = TestApp(['RAY-USD'])
    app.run()
```

But when I run this code, I get the following error:

```/Users/mc/.virtualenvs/crypto/bin/python "/Users/mc/Library/Application Support/JetBrains/PyCharmCE2021.1/scratches/scratch.py"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/mc/.pyenv/versions/3.9.1/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Users/mc/.pyenv/versions/3.9.1/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mc/.virtualenvs/crypto/lib/python3.9/site-packages/cryptofeed/feedhandler.py", line 145, in run
    loop = asyncio.get_event_loop()
  File "/Users/mc/.pyenv/versions/3.9.1/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.
```

What's the correct way to do this? Or am I approaching this task from the wrong angle?

Thanks.

BTW: this library is beautiful, thank you for sharing it.

**Comment by bmoscon** [comment]
asyncio and threading have to be done in a certain way. If you want to use asyncio and threads, I'd recommend reading up on: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor

You can use that method to run a function in a thread in an asyncio application.

**Comment by mchangun** [comment]
OK I'll give that a try.

Would you have any suggestions on a better / more natural way that I can structure my code to achieve the same thing?

**Comment by mchangun** [comment]
I gave that a try but I still have the same error:

```
import asyncio

from time import sleep
from concurrent.futures import ThreadPoolExecutor

from cryptofeed import FeedHandler
from cryptofeed.exchanges import FTX
from cryptofeed.defines import L2_BOOK


class TestApp:
    def __init__(self, symbols: list):
        self.coin_book: dict = {}
        self.symbols = symbols

    async def book_update(self, feed, symbol, book, timestamp, receipt_timestamp):
        self.coin_book = book

    async def start_feed(self):
        loop = asyncio.get_running_loop()

        fh = FeedHandler()
        fh.add_feed(FTX(symbols=self.symbols, channels=[L2_BOOK], callbacks={L2_BOOK: self.book_update}))

        with ThreadPoolExecutor() as pool:
            result = await loop.run_in_executor(pool, fh.run)

    def display(self):
        print('bid', self.coin_book['bid'].peekitem(-1))
        print('ask', self.coin_book['ask'].peekitem(0))

    async def run(self):
        await self.start_feed()

        while True:
            sleep(2)
            self.display()


if __name__ == '__main__':
    app = TestApp(['RAY-USD'])
    asyncio.run(app.run())
```

```
Traceback (most recent call last):
  File "/Users/mc/Library/Application Support/JetBrains/PyCharmCE2021.1/scratches/scratch.py", line 42, in <module>
    asyncio.run(app.run())
  File "/Users/mc/.pyenv/versions/3.9.1/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/mc/.pyenv/versions/3.9.1/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/mc/Library/Application Support/JetBrains/PyCharmCE2021.1/scratches/scratch.py", line 33, in run
    await self.start_feed()
  File "/Users/mc/Library/Application Support/JetBrains/PyCharmCE2021.1/scratches/scratch.py", line 26, in start_feed
    result = await loop.run_in_executor(pool, fh.run)
  File "/Users/mc/.pyenv/versions/3.9.1/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/mc/.virtualenvs/crypto/lib/python3.9/site-packages/cryptofeed/feedhandler.py", line 145, in run
    loop = asyncio.get_event_loop()
  File "/Users/mc/.pyenv/versions/3.9.1/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```

**Comment by bmoscon** [comment]
if you are trying to run from pycharm that may have something to do with it. I think it does something weird (like jupyter notebooks do) and not all asyncio functionality will work. I don't use it, so not sure.

**Comment by bmoscon** [comment]
also, i think you need to be using the thread pool in a running loop

**Comment by tudorelu** [comment]
> if you are trying to run from pycharm that may have something to do with it. I think it does something weird (like jupyter notebooks do) and not all asyncio functionality will work. I don't use it, so not sure.

Can confirm this is not due to pycharm, I ran it from terminal, it has the same output.

**Comment by mchangun** [comment]
> > if you are trying to run from pycharm that may have something to do with it. I think it does something weird (like jupyter notebooks do) and not all asyncio functionality will work. I don't use it, so not sure.
> 
> Can confirm this is not due to pycharm, I ran it from terminal, it has the same output.

Same here.  But I changed my code so that feedhandler runs in the main thread and display is run in the new thread.

**Comment by bmoscon** [comment]
sounds good, seems like you are all set

**Comment by nikolhaas65** [comment]
Hi, I encountered the same problem, but solved in different way (started from above example, but will modify).
The key is to install nest_asyncio

Cheers

# ========== cell1
import asyncio

from time import sleep
from concurrent.futures import ThreadPoolExecutor

from cryptofeed import FeedHandler
from cryptofeed.exchanges import Poloniex
from cryptofeed.defines import L2_BOOK 

import nest_asyncio
nest_asyncio.apply()
 
# =========== cell2
class TestApp:
    def __init__(self, symbols: list):
        self.coin_book: dict = {}
        self.symbols = symbols
        self.cnt = 0
        self.fh = FeedHandler()

    async def book_update(self, book, receipt_timestamp):
        if self.cnt<10:
            print(f'Book received at {receipt_timestamp} for {book.exchange} - {book.symbol}, with {len(book.book)} entries. Top of book prices: {book.book.asks.index(0)[0]} - {book.book.bids.index(0)[0]}')
            if book.delta:
                pass
            if book.sequence_number:
                assert isinstance(book.sequence_number, int)
        self.cnt+=1

    async def start_feed(self):
        print('start run')
        loop = asyncio.get_running_loop()

        self.fh.add_feed(Poloniex(symbols=self.symbols, channels=[L2_BOOK], callbacks={L2_BOOK: self.book_update}))

#============ cell3
app = TestApp(['BTC-USDT'])

loop = asyncio.get_event_loop()

asyncio.ensure_future(app.start_feed(), loop=loop)
asyncio.ensure_future(app.fh.run(), loop=loop)
