### ISSUE TITLE
is CANDLES interval only available as 1m?

### ISSUE THREAD

**Issue by gigitalz** [bmoscon/cryptofeed#505]
I tried binance futures candles but I see only 1m intervals passing by, is it possible to have like 5m or do we need to compose it ourselves?

**Comment by bmoscon** [comment]
its a kwarg to the constructor: https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/exchange/binance.py#L48

set `candle_interval` to the value you want, eg. `5m`

**Comment by gigitalz** [comment]
thanks.
no way to add multiple intervals in the same call?

for example:

add_feed(...
candle_interval='1m,5m,1h'

**Comment by bmoscon** [comment]
nope, you can create multiple Binance objects
