### ISSUE TITLE
OKEx error: Unexpected keyword argument 'status'

### ISSUE THREAD

**Issue by MikeMaxNow** [bmoscon/cryptofeed#507]
**Describe the bug**
I am using the sample script for liquidations with OKEx. After a couple of seconds, it ends with this error message:
```
File "[...]/lib/python3.9/site-packages/cryptofeed/feed.py", line 296, in callback await cb(**kwargs)
TypeError: __call__() got an unexpected keyword argument 'status'

```
**To Reproduce**
```
f.add_feed(OKEx(channels=[LIQUIDATIONS], symbols=['BTC-USD-SWAP'],
                  callbacks={LIQUIDATIONS: LiquidationCallback(liquidations)}), timeout=-1)
```

**Comment by bmoscon** [comment]
@MikeMaxNow I can't reproduce this - what version are you using?

**Comment by bmoscon** [comment]
I can't reproduce this - if you're able to provide more details please re-open this
