### ISSUE TITLE
Typos in examples in Adding a new exchange doc

### ISSUE THREAD

**Issue by evdoks** [bmoscon/cryptofeed#510]
**Describe the bug**
Typos in examples in [Adding a new exchange](https://github.com/bmoscon/cryptofeed/blob/master/docs/exchange.md) documentation section:
* in definition of [`subscribe()`](https://github.com/bmoscon/cryptofeed/blob/master/docs/exchange.md#subscribing), `self.subscriptions.items()` should be `self.subscription.items()`,
* in definition of [`message_handler()`](https://github.com/bmoscon/cryptofeed/blob/master/docs/exchange.md#message-handler), `conn.send()` should be `conn.write`.

**To Reproduce**
* Open [Adding new exchange](https://github.com/bmoscon/cryptofeed/blob/master/docs/exchange.md) doc and try running provided examples.

**Expected behavior**
Correct examples in the documentation.

**Cryptofeed Version**
- Source, commit ` e00b0f6z`.

**Comment by bmoscon** [comment]
fixed, thanks for raising the issue
