### ISSUE TITLE
KeyError: TickSize Binance

### ISSUE THREAD

**Issue by donfelipee** [bmoscon/cryptofeed#515]
**Describe the bug**
Seem like Binance changed their return values for the data
```
021-06-10 12:21:01,331 : ERROR : BINANCE: Failed to parse symbol information: 'tickSize'
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/env/lib/python3.8/site-packages/cryptofeed/feed.py", line 225, in symbol_mapping
    syms, info = cls._parse_symbol_data(data, symbol_separator)
  File "/Users/user/.pyenv/versions/env/lib/python3.8/site-packages/cryptofeed/exchange/binance.py", line 43, in _parse_symbol_data
    info['tick_size'][normalized] = symbol['filters'][0]['tickSize']
KeyError: 'tickSize'
```

**To Reproduce**

Set up a feed stream (sample without imports)

```
def main():
    f = FeedHandler()
    f.add_feed(
        Binance(
            max_depth=DEPTH,
            symbols=["BCH-EUR", "ETH-USDT"],
            channels=[L2_BOOK],
            callbacks={L2_BOOK: book},
        )
    )
```

**Operating System:**
 - macOS

**Cryptofeed Version**
lastest (1.9.0)

**Comment by donfelipee** [comment]
Hmm, not sure what happed exactly - maybe it was a problem with the data stream itself, but I can confirm that this issue does not occur right now. However, would there be a way to catch the KeyErrors so that the key errors don't cause crashing of applications?

**Comment by bmoscon** [comment]
@donfelipee this is very likely an issue with binance, probably they took the exchange down for maintenance or something like that. When you start up an exchange object it has to query the exchange to get a list of symbols for mapping purposes. Thats where this error came from.

You can catch the error, but it wouldnt really do much good - cryptofeed won't work without that symbol mapping information
