### ISSUE TITLE
when i run fh.run, but i want to add feed ,hao can i dou?

### ISSUE THREAD

**Issue by yfjelley** [bmoscon/cryptofeed#526]
def ticker():
    try:
        while True:
            time.sleep(1)
            obj = GridStrategy.objects.all()
            need_run = False
            for item in obj:
                time.sleep(1)
                log.info(item.symbol)
                feed = get_feed(item.platform, item.otype)
                if is_exist_in_redis(feed, item.symbol):
                    continue
                log.info("feed is %s %s %s %s" % (feed, item.platform, item.symbol, item.otype))
                try:
                    fh.add_feed(eval(feed)(symbols=[form_symbol(item.symbol)], channels=[L2_BOOK], callbacks=callbacks))
                    log.info("add feed success %s %s" % (feed, form_symbol(item.symbol)))
                    need_run = True
                except Exception as e:
                    log.info("add feed %s %s error %s" % (feed, form_symbol(item.symbol), str(e)))
            if need_run:
                fh.run()
    except Exception as e:
        log.info("subscribe error is %s " % str(e))

**Comment by bmoscon** [comment]
I don't understand the question. Can you elaborate?

**Comment by peedrr** [comment]
Have you seen the `add_feed_running` method?

'''
from cryptofeed import FeedHandler

 f = FeedHandler()
f.add_feed_running
'''

You can see an example at examples/demo_loop.py

Hope this helps

**Comment by bmoscon** [comment]
no response, so closing. If you mean how can you add a feed to a running instance of the feedhandler, then see the above comment and that example code
