### ISSUE TITLE
Gemini feedhandler fails when subscribing to BTC-GUSD and ETH-GUSD

### ISSUE THREAD

**Issue by kyle-downey** [bmoscon/cryptofeed#531]
**Describe the bug**
This code in the Gemini class:

```
    @classmethod
    def _parse_symbol_data(cls, data: dict, symbol_separator: str) -> Tuple[Dict, Dict]:
        ret = {}
        for symbol in data:
            std = f"{symbol[:-3]}{symbol_separator}{symbol[-3:]}"
            std = std.upper()
            ret[std] = symbol.upper()
        return ret, {}
```

assumes that symbols are three characters long. In the case of BTC-GUSD on Gemini, this does not hold true. It thus fails with the error: cryptofeed.exceptions.UnsupportedSymbol: BTC-GUSD is not supported on GEMINI.

**To Reproduce**

```
async def trade(feed, symbol, order_id, timestamp, side, amount, price, receipt_timestamp, order_type):
    print(f"Timestamp: {timestamp} Feed: {feed} Pair: {symbol} ID: {order_id} Side: {side} Amount: {amount} "
          f"Price: {price} Order Type {order_type}")


async def book(feed, symbol, book, timestamp, receipt_timestamp):
    print(f'Timestamp: {timestamp} Feed: {feed} Pair: {symbol} Book Bid Size is {len(book[BID])} '
          f'Ask Size is {len(book[ASK])}')

def main():
        f = FeedHandler()
       symbols = ['BTC-GUSD']
        f.add_feed(Gemini(subscription={TRADES: symbols, L2_BOOK: symbols}, callbacks={
            TRADES: TradeCallback(trade, include_order_type=True),
            L2_BOOK: BookCallback(book)
        }))

        f.run()
```

**Expected behavior**
I expect the trade prints and book updates to print to the console for this product.

**Screenshots**
Not applicable

**Operating System:**
 - tested on MacOS Big Sur, but should be platform-independent

**Cryptofeed Version**
- 1.9.1 (pip installed)

**Comment by bmoscon** [comment]
@kyle-downey - thanks for raising this - will fix this today

**Comment by bmoscon** [comment]
fixed. Note that before the symbols shown included symbols that were not valid for trading. This is no longer the case (BTC-GUSD is no longer valid for trading).

**Comment by kyle-downey** [comment]
Thanks! I will pick it up and try once it's pushed to pip. I am integrating cryptofeed to replace the hand-rolled feed handlers in my project and it is working well so far. I am seeing some issues with connection retry stalling but I haven't yet narrowed it down enough to make a clear problem report; I will open a separate issue if I get to the bottom of it.

**Comment by bmoscon** [comment]
@kyle-downey if you can elaborate on what you are seeing, I may be able to help. I've been using the software for a few years now, I've seen some things ;)

**Comment by kyle-downey** [comment]
A day ago I saw that the Gemini feed handler reported a 1006 error (websocket disconnect) with a message that it was retrying connection in one second, but after that I saw no more order book or trade print updates and nothing more on the console. What happens on retry? Does it bubble up an exception or just print an error and retry? If I see it again I will open an issue with the exact error message.

**Comment by bmoscon** [comment]
the 1006 was the exception, its from the websockets library, basically means the connection was closed, but in a non-graceful manner. That can happen for many reasons, network issues, exchange issues, exchange maintenance, downtime, etc. I've seem some exchange docs that basically say they just reset everyones connections after a day. So that exception is caught and then the connection is reestablished and the subscription re-sent. I'm not sure why you didnt get anything after that. Hard to know if the connection was established and then no data came (seems unlikely), or if the connection was still in progress/pending, etc. If the timeout has not been modified, if there is no data within 2 mins, it will close the connection and re-initiate it.

**Comment by kyle-downey** [comment]
I was finally able to reproduce the above error, Bryant, so I opened a bug report: https://github.com/bmoscon/cryptofeed/issues/545.
