### ISSUE TITLE
Timeout error even when receiving messages within the timeout period

### ISSUE THREAD

**Issue by rodenwild** [bmoscon/cryptofeed#536]
**Describe the bug**
`2021-06-24 05:56:01,255 : WARNING : BINANCE_FUTURES.ws.3: received no messages within timeout, restarting connection`

This error happens even when there is data being recieved within the timeout period. Disabling the timeout period with the following code also causes this error to occur. 

```
f = FeedHandler()

f.add_feed(BinanceFutures(symbols=symbols, channels=[LIQUIDATIONS],
               callbacks={LIQUIDATIONS: LiquidationCallback(liquidations)}), timeout=-1)

f.run()
```

This does not happen with other brokers such as FTX, only Binance.

**Operating System:**
 - macOS, Linus Ubuntu

**Cryptofeed Version**
- Version 1.9.0

**Comment by bmoscon** [comment]
I'll look into this and get back to you

**Comment by bmoscon** [comment]
this has been fixed on master - thanks for raising!
