### ISSUE TITLE
Whl missing new files? Potential bug

### ISSUE THREAD

**Issue by idclevxx** [bmoscon/cryptofeed#539]
**Describe the bug**
After upgrading to latest version of cryptofeed (without errors) I noticed dYdx was not working. Upon closer inspection of the environment folder, files related to dYdX were missing or not updated. [Are the files missing from the whl-file](https://www.wheelodex.org/projects/cryptofeed/)? I recognize this may be a bug related to my system but other packages are updating.

**Operating System:**
 - macOS 11.4

**Cryptofeed Version**
- 1.9.1 installed via pypi

**Comment by bmoscon** [comment]
it was added in 1.9.2, which has not been released yet. Use the version in github if you want to use it now

**Comment by idclevxx** [comment]
Will do, thanks @bmoscon.
