### ISSUE TITLE
How to disable timeout warning?

### ISSUE THREAD

**Issue by idclevxx** [bmoscon/cryptofeed#552]
Have been looking for an answer to this, using the code in demo_liquidations.py, how do we disable warning messages like: 

`WARNING : BITMEX.ws.5: received no messages within timeout, restarting connection`.

`timeout=-1` is used.

Thanks

**Comment by bmoscon** [comment]
this has been fixed, its on the master branch in github, but not deployed to pypi yet

**Comment by idclevxx** [comment]
Thank you @bmoscon
