### ISSUE TITLE
OKEx liquidations not working as expected

### ISSUE THREAD

**Issue by idclevxx** [bmoscon/cryptofeed#553]
**Describe the bug**
When initiating the OKEx liquidation feed using all symbols like this...

```
okex_symbols = []
okex_all = OKEx.info()
for k, v in okex_all['instrument_type'].items():
    if v == 'swap' or v == 'futures':
        okex_symbols.append(k)

f = FeedHandler()
f.add_feed(OKEx(channels=[LIQUIDATIONS], symbols=okex_symbols, callbacks={LIQUIDATIONS: LiquidationCallback(liquidations)}), timeout=-1)
```

...massive amounts of liquidations (perhaps old) are printed before the feed seems to start printing liquidations in real time.

**Screenshots**

**Operating System:**
 - macOS

**Cryptofeed Version**
pypi 1.9.1

**Comment by bmoscon** [comment]
this has been fixed, its on the master branch in github, but not deployed to pypi yet

**Comment by bmoscon** [comment]
its unclear what the bug is here

**Comment by idclevxx** [comment]
A large amount of liquidations are printed every time the feed is started; i've tried 6-7 times. Considering the slower volume after the initial batch is printed, they can't be current. I might be wrong and it's not a big issue, but still wanted to report. Feel free to close it if you're not experiencing the same avalanche when launching the okex liquidation feed.

**Comment by idclevxx** [comment]
Bryant, I'm closing this and opening it together with another issue.
