### ISSUE TITLE
What is -PINDEX ?

### ISSUE THREAD

**Issue by boskiv** [bmoscon/cryptofeed#564]
I noticed wierd simbol comes from Binance futures with suffix -PINDEX. What is it ? Can I filter it out from 
```
pairs = BinanceFutures.symbols()
```

**Comment by boskiv** [comment]
Answering myself on second question
```
symbols = [s for s in BinanceFutures.info()['symbols'] if 'PINDEX' not in s]
```

**Comment by bmoscon** [comment]
@boskiv - pindex are the premium index symbols
