### ISSUE TITLE
inconsistent symbol normalization

### ISSUE THREAD

**Issue by victorgendre** [bmoscon/cryptofeed#567]
First, thanks for the awesome work!

**Describe the bug**
Futures contract dates are not consistent from one exchange to the other. For instance ADA September future contract would be normalized as ADA-0924 in FTX and ADAUSD-210924 in BinanceDelivery. 

**To Reproduce**
```
from cryptofeed.exchanges import FTX, BinanceDelivery
FTX(config).info().normalized_symbol_mapping
BinanceDelivery(config).info().normalized_symbol_mapping
```

**Expected behavior**
Same contract date display across exchanges. eg: ADA-0924 or ADAUSD-0924 or ADAUSD-210924

**Operating System:**
 - Windows

**Cryptofeed Version**
- 1.91

Thanks!

**Comment by bmoscon** [comment]
I've been working on this for a while, I will hopefully have it done in the coming week. You can checkout the branch if you're interested, symbol-standardization

**Comment by victorgendre** [comment]
Brilliant! Thanks for the reply. Very keen to have a look.

**Comment by bmoscon** [comment]
his has been fixed in master
