### ISSUE TITLE
Question - extra fields for Coinbase

### ISSUE THREAD

**Issue by zwangz** [bmoscon/cryptofeed#570]
Hi Bryant,

Posting this on Github and Slack in case one is not monitored too often :)

I'm doing some analysis which requires order book data (L3 book and delta) and your project is very promising - so a massive thank you for this!

May I ask a question please: Is there an easy way to let the tool return extra fields available from the Coinbase websocket feed?  at the moment I appreciate all L3_book data will have the same schema.
Specifically I would like to
* know for each delta order what it actually represent which would require an extra field called `delta_type` which depends on the message - at the moment a cancellation with size `0` means the same as being filled to size `0`. (see `_done` and `_book_update` in `coinbase.py`
* know (when also subscribing to trades data) what the  `taker_order_id` and `maker_order_id` are which is something Coinbase provides..

I thought I'd also outline why I need them
* how often market orders arrive by looking at the trades - i.e. per `taker_order_id` instead of per trade
* how often cancellation orders arrive by looking at the deltas and extra field - this cannot be done currently as cancellation and being filled all have a 0 as its new size

If you do perhaps know an easier way of getting this extra info without changing the source / forking that would literally save my life!

Thank you in advance for any help!
Zhi

**Comment by zwangz** [comment]
Closing as question answered in [Slack chat](https://cryptofeed-dev.slack.com/ssb/redirect).

**Comment by pikeas** [comment]
> Closing as question answered in [Slack chat](https://cryptofeed-dev.slack.com/ssb/redirect).

Slack doesn't appear to be publicly accessible, could you paste the answer here?

**Comment by bmoscon** [comment]
@pikeas it is, see the readme

**Comment by pikeas** [comment]
You're right, thanks for that. I've searched Slack for "zwangz" and keywords from this issue and can't find the answer, could you please link or paste it here?

**Comment by zwangz** [comment]
@pikeas Hi - yeah sure with pleasure:

Bryant's response was "the only thing that will work with no code change is to enable the capture of the raw data"

My solution was to change a few functions in Cryptofeed to make it return the extra fields that Coinbase provides as a workaround. If this use case matches what you want I will be happy to open a github gist or something for the patches.
