### ISSUE TITLE
How to do graceful shutdown properly?

### ISSUE THREAD

**Issue by kevinheavey** [bmoscon/cryptofeed#581]
Hi,

I'm pretty sure cryptofeed supports this kind of thing but I can't quite tell how:

Say I have a cryptofeed process running and I want it to do some cleanup when I send SIGINT to it. For example, before shutting down I might want to call a function I wrote to cancel open orders.

How does one implement this?

**Comment by bmoscon** [comment]
it currently does clean up when it receives signals. You'd have to change the code to allow you to supply your own signal handler. If you look at the run method, it will by default set up signal handlers:

https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/feedhandler.py#L130


If you set that to false, and install your own signal handlers, you can cleanup what you want. Note all they do is raise systemExit, which is an exception the feedhandler will catch and use as a trigger to cleanly exit.

**Comment by kevinheavey** [comment]
Got it thanks. For anyone else reading, this works for me (imports and FeedHandler instantiation omittted)

```python

def setup_my_signal_handlers(loop: asyncio.AbstractEventLoop):
    """
    This must be run from the loop in the main thread
    """
    logging.info("Installing my signal handlers")

    def handle_stop_signals(*args):
        logging.info("Handling my stop signal")
        raise SystemExit

    for sig in SIGNALS:
        loop.add_signal_handler(sig, handle_stop_signals)

loop = asyncio.get_event_loop()
setup_my_signal_handlers(loop)
f.run(install_signal_handlers=False)
