### ISSUE TITLE
Update pip

### ISSUE THREAD

**Issue by ibmua** [bmoscon/cryptofeed#584]
Hi! Could you, please, update cryptofeed version that's default on pip? Right now it fails demo example, because it's older.

**Comment by victorgendre** [comment]
you can pip install master doing something like that `pip install https://github.com/bmoscon/cryptofeed/archive/master.zip` see this [link](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch)

**Comment by ibmua** [comment]
Interesting =)

**Comment by bmoscon** [comment]
I'll update the version in pypi when it is ready to be released. If you want to use the new features in master, then use the version of the code in master. Either clone it and install it or use the above mentioned option
