### ISSUE TITLE
Open Interest of BINANCE_DELIVERY not working

### ISSUE THREAD

**Issue by likso** [bmoscon/cryptofeed#600]
**Describe the bug**
Open Interest of BINANCE_DELIVERY not working.

BTC-USD-PERP

**Operating System:**
 - macOS

**Cryptofeed Version**
- 1.9.3

**Comment by bmoscon** [comment]
this has been fixed in 2.0

**Comment by bmoscon** [comment]
I'm going to close this, but let me know if you still have issues.

**Comment by likso** [comment]
Open interest is not working in both BINANCE_DELIVERY and BINANCE_FUTURE.

Cryptofeed Version

2.2.3
