### ISSUE TITLE
Support for Binance Futures Testnet

### ISSUE THREAD

**Issue by pesfahanian** [bmoscon/cryptofeed#605]
I'm trying to modify the source to add support for Binance Futures Testnet.  

I have made the following changes in `cryptofeed/exchanges/binance_futures.py`:
- Line 49: changed `self.ws_endpoint` from `'wss://fstream.binance.com'` to `'wss://stream.binancefuture.com'`.
- Line 50: changed `self.rest_endpoint` from `'https://fapi.binance.com/fapi/v1'` to `'https://testnet.binancefuture.com/fapi/v1'`.

But none of the pubic feeds (_e.g._ trades) work.

Can anyone help?

**Comment by bmoscon** [comment]
@pesfahanian let me take a look, that looks correct based on what I'm seeing in their docs. It should be easy to add support for this and make it toggleable via the sandbox kwarg to the exchange class.

**Comment by bmoscon** [comment]
done  -sorry this took me so long to get to!
