### ISSUE TITLE
feedhandler.log feedhandler.log.1 feedhandler.log.2 ... feedhandler.log.n

### ISSUE THREAD

**Issue by gigitalz** [bmoscon/cryptofeed#608]
This file is being create perpetually adding 1,2,3,4, is there a way to manage the cycling of it or to control at least how much space is taken on the hd? Any configuration we can set?

Thanks.

**Comment by bmoscon** [comment]
its not forever, its a limit of 10, see: https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/log.py#L22
