### ISSUE TITLE
Redirect output to file

### ISSUE THREAD

**Issue by DavideColdebellaMelanion** [bmoscon/cryptofeed#609]
Hi,

Currently using cryptofeed 1.9.0 on Jupyter Notebook, on Windows 10, python 3.8.11.

I was wondering if there were any way to redirect output such as:
- 2021-08-22 06:45:22,646 : WARNING : BITMEX.ws.510: Rate Limited - waiting 180 seconds to reconnect

to a file.

Thank you!

**Comment by victorgendre** [comment]
Hi, I think you will need to update the 'feedhandler' logger config and save to file.

**Comment by bmoscon** [comment]
by default it should log to feedhandler.log, but I can't confirm that behavior in jupyter (I have no reason to think it wouldnt do that, but I dont run in jupyter)
