### ISSUE TITLE
OKEx L2_BOOK channel struggles to start

### ISSUE THREAD

**Issue by doublesavonette** [bmoscon/cryptofeed#610]
Hi,

I am getting some unexpected (I think) behavior on OKEx. 

**Describe the bug**
OKEx struggles to start the feed on multiple symbols in one go. It has to restart multiple times before making a successful launch.

**To Reproduce**
Run OKEx L2_BOOK channel on a large sample of symbols. 

**Expected behavior**
Successful start without retries

**Screenshots**
![image](https://user-images.githubusercontent.com/79073160/130655389-bbbf185b-2c24-47a1-b9db-c7cf5673750d.png)

**Operating System:**
 - linux

**Cryptofeed Version**
- 1.9.3

Thanks!

**Comment by bmoscon** [comment]
@victorgendre - I found a bug actually in the okex code that I've fixed in my development branch. This will  resolve this issue, but you'll need to wait for it to be merged, probably towards the end of this week

**Comment by victorgendre** [comment]
@bmoscon, brilliant! Thanks a lot for the fix and heads up.

**Comment by bmoscon** [comment]
this was merged a while ago, so closing
