### ISSUE TITLE
429: Too Many Requests error on Binance spot feed

### ISSUE THREAD

**Issue by legendagain** [bmoscon/cryptofeed#613]
**Describe the bug**
Ran OrderBook and Trade feeds for Binance for all pairs with top 20 symbols (excluding stables), a total of about 125 symbols in total). After running for more than 24 hours, cryptofeed received "429: Too Many Requests" exception from Binance for each symbol and could not recover from it (i.e. data collection eventually stopped).

![image](https://user-images.githubusercontent.com/2020134/131284265-0da83652-8dec-40f5-88b9-fac973466f1b.png)

Two issues concern me here and I hope someone can help:

1. What are some possible reasons for 429 error triggering only on the 2nd day?
2. How can I gracefully recover from a 429 error? Should I use the `exception_handler` to pause cryptofeed, wait for the 429 exception to pass, and then restart the feed?

**Operating System:**
Windows

**Cryptofeed Version**
1.9.1 from pypi

**Comment by peedrr** [comment]
Hi @legendagain,

I can provide some info on why this is happening. From Binance's API docs: "[a single [websocket] stream is only valid for 24 hours; expect to get disconnect at the 24 hour mark](https://binance-docs.github.io/apidocs/spot/en/#websocket-market-streams)".

What's then happening is that the connections are re-established. With the way things work for Binance in particular, this means two things: firstly a request is made to subscribe to the websocket feeds again (which presents no problem) and secondly, an HTTP GET request is made _for each symbol_  to receive a snapshot of the book for these symbols. I believe it is this sudden splurge of HTTP requests which is tripping the 429.

The obvious question is, why doesn't this happen when you first start the feeds, as the process is the same? (i.e. websockets requested -> book snapshots requested by HTTP). One thing I have noticed is that the initial HTTP requests appear to be staggered, i.e. they don't all fire off at once, but I haven't yet found any code to suggest this is planned behaviour. 
@jinusean - I know you've done a fair bit of work on Binance recently. Do you have any knowledge around this?

And in terms of a fix for large numbers of simultaneous HTTP requests, if there isn't any coded-in request staggering then I guess it is required. And if there is, then it needs to be implemented on the 24 hour reconnects, which, it seems from the docs, are unavoidable.

**Comment by jinusean** [comment]
The process should be the same for both cases (initial snapshot, and refetch) so I'm not sure why there's a 429 in the latter. 

The staggered snapshots are because you have to set `concurrent_http=True` for a parallel fetch. I always use a `http_proxy` on conjunction with this option. 

I am not sure about any methods that can recover from a request timeout, and I did not experience them since I've been using a proxy. if we were to implement one, we ca use a field in the response headers that indicates the current api consumption rate.

**Comment by bmoscon** [comment]
@legendagain  - probably just need to add a small delay into the mix when querying the orderbooks. Shouldnt be too hard to add, I can do that later this week.

**Comment by legendagain** [comment]
Thank you very much @bmoscon! Please let me know if there's any way I can help..

**Comment by bmoscon** [comment]
should be fixed on 2.0.2, let me know if you have further issues

**Comment by mrajancsr** [comment]
@bmoscon , curious, what did you do to fix this issue? did you put a sleep for x amount of second for each message you receive from binance? thanks

**Comment by bmoscon** [comment]
@mrajancsr dont remember. not sure if it even applies still, that code has changed a lot since then.

**Comment by ccn1010** [comment]
is there any config for prevent 'websockets requested -> book snapshots requested by HTTP' so that avoid 'many requests' error
