### ISSUE TITLE
Binance Futures data falls behind other feeds

### ISSUE THREAD

**Issue by jshellen** [bmoscon/cryptofeed#617]
Hi,

We are experiencing a strange "bug" while recording Binance Futures TICKER, TRADES and L2_BOOK to MongoDB. Looking at the timestamps, the time difference between the latest entry in the DB and current time seems to get getting longer and longer. Currently, the delta is ~**20 minutes**. This behavior is observable in all the channels.

In the same feed, we have BitMEX futures TICKER, TRADES and L2_BOOK. However, BitMEX data does not have similar behavior. 

L2_BOOK is subscribed to 50 levels.

The python script which is recording the data is running on a Dell Desktop Workstation with the following specifications
**Processor:** Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz   2.50 GHz (utilization ~60%)
**RAM:** 8,00 GB
**OS:** Windows 10

The **cryptofeed** version is **1.9.3**

Any ideas what is going on and / or how to solve the issue?

**Comment by bmoscon** [comment]
likely you are getting more messages than you can process. You can do a few things 1) separate the symbols across multiple websocket connections (so call `add_feed` more than once for binance futures), 2) multiprocess (multiple FeedHandlers), 3) use a separate process to handle the writes to the DB to reduce latency

**Comment by bmoscon** [comment]
you didn't mention how many symbols you are subscribed to, but I'm guessing its more than 1 or 2. Also setting max_depth to a level that is unsupported by the exchange can lead to latency as well. Binance provides well over 50 levels and doesnt provide a way to limit what is sent, so the code has to manually truncate the book every update. this is slow. A change that is coming in the next week or so will dramatically increase the performance of this operation. If you really want to truncate to 50 levels, I'd recommend doing that on a second process that handles the mongodb writes. truncate and write there.

**Comment by jshellen** [comment]
Thanks for a quick response. 

I will try these and get back to you in case the issue persists.

**Comment by jshellen** [comment]
When you say multiple FeedHandlers, do you mean running multiple scripts each with their own FeedHandler or running FeedHandler.run using pythons multiprocessing.Proces, or something else? It seems that there is no example implementation for this.

**Comment by bmoscon** [comment]
running them in separate processes (so yes, separate scripts)

**Comment by jshellen** [comment]
My initial claim that it was Binance Futures which was lagging is not true. It is actually BitMEX.

I believe that this issue has two main causes:

The first one is related to performance and possibly to how the event loop processes the different connections. Logging writes shows that it favors the more active feeds with more frequent processing.

The second issue is more significant one. After reading the source code I noticed that BitMEX does not send timestamp with the L2_BOOK updates and therefore the timestamp == time_received. When there are lot of traffic the time_received starts to lag behind the real-but-not-provided timestamp causing the BitMEX data deviate from Binance. This becomes evident when one compares TICKER data with L2_BOOK.
