### ISSUE TITLE
Not Implemented Error

### ISSUE THREAD

**Issue by solsimp** [bmoscon/cryptofeed#619]
Hello,

I'm getting the following error:

This is the output I get : 
PS C:\python3.9\datafeed> & C:/python3.9/python.exe c:/python3.9/datafeed/datafeed.py
2021-08-25 22:20:24,121 : ERROR : Unhandled exception
Traceback (most recent call last):
  File "c:\python3.9\datafeed\cryptofeed\feedhandler.py", line 186, in run
    loop.add_signal_handler(signal, handle_stop_signals)
  File "C:\python3.9\lib\asyncio\events.py", line 539, in add_signal_handler
    raise NotImplementedError
NotImplementedError

Is there a method to troubleshoot this? TIA!

**Comment by bmoscon** [comment]
windows doesnt use signals, so there is no way to add a signal handler to the async loop in Windows. The code should handle this, I'm not sure what version you are on, so you might need to update cryptofeed. line 186 is a log line in the current version

**Comment by solsimp** [comment]
Cheers, Bryant!

**Comment by bmoscon** [comment]
no problem, going to close this, but let me know if you have more questions. also, feel free to join the slack, im usually more responsive to questions there
