### ISSUE TITLE
How to get historical candles data for a time period?

### ISSUE THREAD

**Issue by msounthar** [bmoscon/cryptofeed#623]
Hello

Thanks for your contribution to this project.

Is it possible to get the historical 1m candles data from Binance for a given start and end time? I can see the references to BinanceRestMixin but not sure how they should be added to the feed, an example would be great.

**Comment by bmoscon** [comment]
There is an example in the unit tests:

https://github.com/bmoscon/cryptofeed/blob/master/tests/integration/rest/test_binance.py#L56

This uses the synchronous candle endpoint, but you can just replace `candle_sync` with `candle` as long as you treat it like a coroutine and `await` it.

**Comment by msounthar** [comment]
Thanks!
