### ISSUE TITLE
[Funding rate] - How can i get funding rate from FTX

### ISSUE THREAD

**Issue by tong-zipmex** [bmoscon/cryptofeed#624]
Is Funding rate from FTX like BTC-PERP(%) are available in this library here?
I'm looking for something like Table is this website: https://ftxpremiums.com/

Please help.

**Comment by bmoscon** [comment]
the example code gets it:

https://github.com/bmoscon/cryptofeed/blob/ef6067b3aaa526e4d6ae57e9a37044e5cf19226b/examples/demo.py#L97

or you can get it from the rest endpoint. The unit test shows an example of that:

https://github.com/bmoscon/cryptofeed/blob/master/tests/integration/rest/test_ftx.py#L23
