### ISSUE TITLE
Bug with cross_check on book_callback: OrderBook is not subscriptable

### ISSUE THREAD

**Issue by villekuosmanen** [bmoscon/cryptofeed#629]
**Describe the bug**
In the most recent version, when setting the `cross_check` argument as `True` for an exchange, the function `check_bid_ask_overlapping` will run into a type error when trying to check that the book's best ask and bid don't overlap. I believe this happens because that particular function was not updated when the library switched from using a traditional dict to represent the orderbook into a custom type.

**To Reproduce**
Just run a feed (e.g. Deribit) with a L2_BOOK subscription and the argument `cross_check` set as `True`
```
config = {'log': {'filename': 'demo.log', 'level': 'INFO'}}
f.add_feed(Deribit(symbols=['BTC-60000-21U17-call'], channels=[TICKER, L2_BOOK], cross_check=True))
f.run()
```

This runs into the following error:
```
Traceback (most recent call last):
  File "/Users/<user>/cryptofeed/cryptofeed/connection_handler.py", line 68, in _create_connection
    await self._handler(connection, self.handler)
  File "/Users/<user>/cryptofeed/cryptofeed/connection_handler.py", line 117, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/Users/<user>/cryptofeed/cryptofeed/exchanges/deribit.py", line 349, in message_handler
    await self._book_snapshot(msg_dict, timestamp)
  File "/Users/<user>/cryptofeed/cryptofeed/exchanges/deribit.py", line 272, in _book_snapshot
    await self.book_callback(L2_BOOK, self._l2_book[pair], timestamp, timestamp=self.timestamp_normalize(ts), sequence_number=msg["params"]["data"]["change_id"], raw=msg)
  File "/Users/<user>/cryptofeed/cryptofeed/feed.py", line 175, in book_callback
    self.check_bid_ask_overlapping(book)
  File "/Users/<user>/cryptofeed/cryptofeed/feed.py", line 185, in check_bid_ask_overlapping
    bid, ask = book[BID], book[ASK]
TypeError: 'cryptofeed.types.OrderBook' object is not subscriptable
```

**Expected behavior**
It should not crash

**Operating System:**
 - macOS

**Cryptofeed Version**
- latest master, installed by cloning the repo, latest commit is:
```
Author: Bryant Moscon <bmoscon@gmail.com>
Date:   Tue Sep 14 17:14:37 2021 -0400

    fix websocket connection with okex
```

**Proposed fix**
This is a really easy one to fix, I can send out a PR if you can confirm this is a problem.

**Comment by bmoscon** [comment]
@villekuosmanen - thanks for the ticket - you are correct, this is a bug. I meant to add support for this in the OrderBook C module, but never got around to it. Since I don't think I'll get to it for some time, a PR would help. If you have time, I'd be glad to have it, if not, I'll be able to fix this some time later this week

**Comment by villekuosmanen** [comment]
@bmoscon no problem, the attached PR should fix the issue. Doing this check in the underlying C code would probably be more performant and a good idea, but until then it's good to have this fix in the repo.

**Comment by bmoscon** [comment]
fixed, thanks for the PR!
