### ISSUE TITLE
OHLCV - Candles come at an (apparently) ever increasing time difference. Skipping some candles?

### ISSUE THREAD

**Issue by PranavJoshi2** [bmoscon/cryptofeed#636]
**Describe the bug**
As described in the headline.
Following is the OHLCV data (showing only close value) collected for
1m timeframe - ETHUSDT perpetual futures for bybit exchange
Mark the time column.

<head>

</head>

<body link=blue vlink=purple>

Candle No | date | time | AM/PM | close
-- | -- | -- | -- | --
1 | 9/16/2021 | 6:30:08 | AM | 3581.95
2 | 9/16/2021 | 6:31:12 | AM | 3583.6
3 | 9/16/2021 | 6:32:20 | AM | 3588.9
4 | 9/16/2021 | 6:33:22 | AM | 3590.95
5 | 9/16/2021 | 6:34:25 | AM | 3590.95
6 | 9/16/2021 | 6:35:26 | AM | 3591.2
7 | 9/16/2021 | 6:36:32 | AM | 3594
8 | 9/16/2021 | 6:37:33 | AM | 3593.95
9 | 9/16/2021 | 6:38:51 | AM | 3594
10 | 9/16/2021 | 6:39:52 | AM | 3595.2
11 | 9/16/2021 | 6:40:53 | AM | 3597.7
12 | 9/16/2021 | 6:41:56 | AM | 3601.1
13 | 9/16/2021 | 6:43:01 | AM | 3601.05
14 | 9/16/2021 | 6:44:09 | AM | 3601.65
15 | 9/16/2021 | 6:45:10 | AM | 3603.4
16 | 9/16/2021 | 6:46:12 | AM | 3598.25
17 | 9/16/2021 | 6:47:12 | AM | 3603.15
18 | 9/16/2021 | 6:48:14 | AM | 3602.45
19 | 9/16/2021 | 6:49:15 | AM | 3600.15
20 | 9/16/2021 | 6:50:31 | AM | 3602.45
21 | 9/16/2021 | 6:51:36 | AM | 3600.15
22 | 9/16/2021 | 6:52:42 | AM | 3599.05
23 | 9/16/2021 | 6:53:43 | AM | 3595.4
24 | 9/16/2021 | 6:54:50 | AM | 3598.8
25 | 9/16/2021 | 6:55:51 | AM | 3598.1
26 | 9/16/2021 | 6:56:51 | AM | 3598.05
27 | 9/16/2021 | 6:58:04 | AM | 3596.4
28 | 9/16/2021 | 6:59:05 | AM | 3596.4
29 | 9/16/2021 | 7:00:07 | AM | 3594.05
30 | 9/16/2021 | 7:01:12 | AM | 3594.05
31 | 9/16/2021 | 7:02:30 | AM | 3594.05
32 | 9/16/2021 | 7:03:39 | AM | 3594.1
33 | 9/16/2021 | 7:04:40 | AM | 3591.35
34 | 9/16/2021 | 7:05:44 | AM | 3591.3
35 | 9/16/2021 | 7:06:46 | AM | 3591.3
36 | 9/16/2021 | 7:07:48 | AM | 3590.2
37 | 9/16/2021 | 7:08:58 | AM | 3591.95
38 | 9/16/2021 | 7:10:03 | AM | 3592
39 | 9/16/2021 | 7:11:06 | AM | 3592
40 | 9/16/2021 | 7:12:07 | AM | 3590
41 | 9/16/2021 | 7:13:11 | AM | 3588.5
42 | 9/16/2021 | 7:14:13 | AM | 3587.3
43 | 9/16/2021 | 7:15:13 | AM | 3585.6
44 | 9/16/2021 | 7:16:15 | AM | 3588
45 | 9/16/2021 | 7:17:17 | AM | 3588.05
46 | 9/16/2021 | 7:18:17 | AM | 3590
47 | 9/16/2021 | 7:19:20 | AM | 3589.95
48 | 9/16/2021 | 7:20:20 | AM | 3589.95
49 | 9/16/2021 | 7:21:22 | AM | 3587.4
50 | 9/16/2021 | 7:22:22 | AM | 3586.65
51 | 9/16/2021 | 7:23:54 | AM | 3586.75
52 | 9/16/2021 | 7:24:56 | AM | 3587.6
53 | 9/16/2021 | 7:26:09 | AM | 3589.95
54 | 9/16/2021 | 7:27:09 | AM | 3593.15
55 | 9/16/2021 | 7:28:14 | AM | 3594.7
56 | 9/16/2021 | 7:29:22 | AM | 3592.35
57 | 9/16/2021 | 7:30:31 | AM | 3592.4
58 | 9/16/2021 | 7:31:31 | AM | 3591.1
59 | 9/16/2021 | 7:32:32 | AM | 3591.25
60 | 9/16/2021 | 7:33:34 | AM | 3591.3
61 | 9/16/2021 | 7:34:35 | AM | 3590.55
62 | 9/16/2021 | 7:35:44 | AM | 3587.1
63 | 9/16/2021 | 7:36:45 | AM | 3587.1
64 | 9/16/2021 | 7:37:46 | AM | 3596.25
65 | 9/16/2021 | 7:38:47 | AM | 3599.2
66 | 9/16/2021 | 7:39:48 | AM | 3600.95
67 | 9/16/2021 | 7:41:01 | AM | 3604.95
68 | 9/16/2021 | 7:42:02 | AM | 3605.2
69 | 9/16/2021 | 7:43:05 | AM | 3602.55
70 | 9/16/2021 | 7:44:08 | AM | 3599.5
71 | 9/16/2021 | 7:45:15 | AM | 3599.45
72 | 9/16/2021 | 7:46:28 | AM | 3596.6
73 | 9/16/2021 | 7:47:43 | AM | 3597
74 | 9/16/2021 | 7:48:54 | AM | 3595.5
75 | 9/16/2021 | 7:50:06 | AM | 3593.4
76 | 9/16/2021 | 7:51:07 | AM | 3595.35
77 | 9/16/2021 | 7:52:14 | AM | 3595.65
78 | 9/16/2021 | 7:53:18 | AM | 3595.25
79 | 9/16/2021 | 7:54:20 | AM | 3596.55
80 | 9/16/2021 | 7:55:29 | AM | 3596.55
81 | 9/16/2021 | 7:56:34 | AM | 3595.2
82 | 9/16/2021 | 7:57:34 | AM | 3595.25
83 | 9/16/2021 | 7:58:36 | AM | 3595
84 | 9/16/2021 | 7:59:37 | AM | 3593.15
85 | 9/16/2021 | 8:00:39 | AM | 3593.1
86 | 9/16/2021 | 8:01:43 | AM | 3588.85
87 | 9/16/2021 | 8:02:46 | AM | 3589.95
88 | 9/16/2021 | 8:03:49 | AM | 3584.7
89 | 9/16/2021 | 8:04:52 | AM | 3583.55
90 | 9/16/2021 | 8:05:52 | AM | 3587.95
91 | 9/16/2021 | 8:06:55 | AM | 3587.8
92 | 9/16/2021 | 8:08:02 | AM | 3585
93 | 9/16/2021 | 8:09:04 | AM | 3585.55
94 | 9/16/2021 | 8:10:04 | AM | 3586.6
95 | 9/16/2021 | 8:11:05 | AM | 3586.55
96 | 9/16/2021 | 8:12:07 | AM | 3586.5
97 | 9/16/2021 | 8:13:10 | AM | 3584
98 | 9/16/2021 | 8:14:45 | AM | 3582.9
99 | 9/16/2021 | 8:15:51 | AM | 3583.4
100 | 9/16/2021 | 8:16:52 | AM | 3585.85
101 | 9/16/2021 | 8:17:53 | AM | 3585.8
102 | 9/16/2021 | 8:19:00 | AM | 3588.1
103 | 9/16/2021 | 8:20:06 | AM | 3584.45
104 | 9/16/2021 | 8:21:07 | AM | 3586
105 | 9/16/2021 | 8:22:15 | AM | 3588.4
106 | 9/16/2021 | 8:23:18 | AM | 3588.35
107 | 9/16/2021 | 8:24:25 | AM | 3588.4
108 | 9/16/2021 | 8:25:28 | AM | 3587.9
109 | 9/16/2021 | 8:26:50 | AM | 3588.55
110 | 9/16/2021 | 8:27:50 | AM | 3585.95
111 | 9/16/2021 | 8:28:50 | AM | 3585.25
112 | 9/16/2021 | 8:29:50 | AM | 3585
113 | 9/16/2021 | 8:31:00 | AM | 3585.05
114 | 9/16/2021 | 8:32:05 | AM | 3584
115 | 9/16/2021 | 8:33:15 | AM | 3580.4
116 | 9/16/2021 | 8:34:15 | AM | 3579.55
117 | 9/16/2021 | 8:35:31 | AM | 3582.1
118 | 9/16/2021 | 8:36:39 | AM | 3582.15
119 | 9/16/2021 | 8:38:00 | AM | 3581.15
120 | 9/16/2021 | 8:39:04 | AM | 3581.7
121 | 9/16/2021 | 8:40:06 | AM | 3583.2
122 | 9/16/2021 | 8:41:06 | AM | 3579.65
123 | 9/16/2021 | 8:42:08 | AM | 3579.55
124 | 9/16/2021 | 8:43:10 | AM | 3579.6
125 | 9/16/2021 | 8:44:23 | AM | 3578.65
126 | 9/16/2021 | 8:45:24 | AM | 3575.35
127 | 9/16/2021 | 8:46:25 | AM | 3566.9
128 | 9/16/2021 | 8:47:26 | AM | 3562.7
129 | 9/16/2021 | 8:48:26 | AM | 3554.75
130 | 9/16/2021 | 8:49:26 | AM | 3540.55
131 | 9/16/2021 | 8:50:28 | AM | 3545
132 | 9/16/2021 | 8:51:29 | AM | 3540.5
133 | 9/16/2021 | 8:52:29 | AM | 3529.05
134 | 9/16/2021 | 8:53:29 | AM | 3533.1
135 | 9/16/2021 | 8:54:29 | AM | 3528
136 | 9/16/2021 | 8:55:30 | AM | 3540.35
137 | 9/16/2021 | 8:56:31 | AM | 3531.5
138 | 9/16/2021 | 8:57:32 | AM | 3538.5
139 | 9/16/2021 | 8:58:32 | AM | 3531.15
140 | 9/16/2021 | 8:59:34 | AM | 3532.05
141 | 9/16/2021 | 9:00:34 | AM | 3543.35
142 | 9/16/2021 | 9:01:37 | AM | 3540.65
143 | 9/16/2021 | 9:02:39 | AM | 3543.85
144 | 9/16/2021 | 9:03:39 | AM | 3540.8
145 | 9/16/2021 | 9:04:41 | AM | 3542.15
146 | 9/16/2021 | 9:05:42 | AM | 3542.9
147 | 9/16/2021 | 9:06:44 | AM | 3547
148 | 9/16/2021 | 9:07:45 | AM | 3550
149 | 9/16/2021 | 9:08:45 | AM | 3548.65
150 | 9/16/2021 | 9:09:47 | AM | 3544.15
151 | 9/16/2021 | 9:10:49 | AM | 3548.2
152 | 9/16/2021 | 9:11:53 | AM | 3538.15
153 | 9/16/2021 | 9:12:56 | AM | 3545.45
154 | 9/16/2021 | 9:14:00 | AM | 3544.95
155 | 9/16/2021 | 9:15:00 | AM | 3540
156 | 9/16/2021 | 9:16:06 | AM | 3544
157 | 9/16/2021 | 9:17:06 | AM | 3547.3
158 | 9/16/2021 | 9:18:07 | AM | 3546.35
159 | 9/16/2021 | 9:19:09 | AM | 3542.75
160 | 9/16/2021 | 9:20:11 | AM | 3540.85
161 | 9/16/2021 | 9:21:11 | AM | 3541.7
162 | 9/16/2021 | 9:22:23 | AM | 3542.15
163 | 9/16/2021 | 9:23:31 | AM | 3541.1
164 | 9/16/2021 | 9:24:33 | AM | 3541
165 | 9/16/2021 | 9:25:34 | AM | 3538.6
166 | 9/16/2021 | 9:26:39 | AM | 3544.55
167 | 9/16/2021 | 9:27:42 | AM | 3545.05
168 | 9/16/2021 | 9:28:44 | AM | 3544
169 | 9/16/2021 | 9:29:44 | AM | 3544
170 | 9/16/2021 | 9:30:45 | AM | 3539.3
171 | 9/16/2021 | 9:31:47 | AM | 3544.9
172 | 9/16/2021 | 9:32:48 | AM | 3544.95
173 | 9/16/2021 | 9:33:51 | AM | 3544.95
174 | 9/16/2021 | 9:34:56 | AM | 3548.95
175 | 9/16/2021 | 9:35:58 | AM | 3550.3
176 | 9/16/2021 | 9:37:02 | AM | 3555
177 | 9/16/2021 | 9:38:03 | AM | 3562.9
178 | 9/16/2021 | 9:39:03 | AM | 3584.4
179 | 9/16/2021 | 9:40:04 | AM | 3594.55
180 | 9/16/2021 | 9:41:06 | AM | 3593.8
181 | 9/16/2021 | 9:42:07 | AM | 3591.35
182 | 9/16/2021 | 9:43:08 | AM | 3595
183 | 9/16/2021 | 9:44:08 | AM | 3595.3
184 | 9/16/2021 | 9:45:08 | AM | 3598.95
185 | 9/16/2021 | 9:46:09 | AM | 3595.2
186 | 9/16/2021 | 9:47:09 | AM | 3616.05
187 | 9/16/2021 | 9:48:09 | AM | 3627.25
188 | 9/16/2021 | 9:49:12 | AM | 3625.3
189 | 9/16/2021 | 9:50:12 | AM | 3646.85
190 | 9/16/2021 | 9:51:12 | AM | 3650.55
191 | 9/16/2021 | 9:52:12 | AM | 3657.35
192 | 9/16/2021 | 9:53:12 | AM | 3664.25
193 | 9/16/2021 | 9:54:15 | AM | 3665.45
194 | 9/16/2021 | 9:55:15 | AM | 3671.55
195 | 9/16/2021 | 9:56:18 | AM | 3664.1
196 | 9/16/2021 | 9:57:20 | AM | 3663.45
197 | 9/16/2021 | 9:58:20 | AM | 3657.6
198 | 9/16/2021 | 9:59:21 | AM | 3666.45
199 | 9/16/2021 | 10:00:21 | AM | 3663.65
200 | 9/16/2021 | 10:01:21 | AM | 3658.25

</body>

</html>

Note the time is showing an increment in seconds for every candle-data arrival.

**To Reproduce**
Add feed using the sample code with change of exchange name and symbol
Ref: https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_ohlcv.py

```
async def ohlcv(data=None):
    end_time_sec = dt.datetime.now()
    print(f'\n\nTime = {end_time_sec}\n{data}')
    append_to_csv(data)

f = FeedHandler()
f.add_feed(Bybit(symbols=['BTC-USDT-PERP'], channels=[TRADES], callbacks={TRADES: OHLCV(ohlcv, window=180)}))
f.add_feed(Bybit(symbols=['ETH-USDT-PERP'], channels=[TRADES], callbacks={TRADES: OHLCV(ohlcv, window=60)}))
f.run()
```

**Expected behavior**
if the first candle data arrives at 6:30:08, then the second and the following candles must come at exactly the same time with an max acceptable delay of (subjective) 3 sec.

Can we add tohlcv where,
t = candle open time ?

**Operating System:**
 - Win7

**Cryptofeed Version**
- cryptofeed==1.9.3 (pip installed)

**Comment by bmoscon** [comment]
if you look at the comment in the code, the OHLCV aggregator is just an example of how one could use the aggregator functionality, its far from perfect and it definitely isnt guaranteed to give you the exact candle intervals because it depends on data from the exchange coming in to trigger events. So, I'm going to close this because its working as expected - which is as example code. If you want candles, you should get them from the exchange directly. Bybit doesnt have candle support yet, but I can add it this week and I'll close this ticket when that has been completed

**Comment by PranavJoshi2** [comment]
tnx for your efforts. waiting for the update.

**Comment by bmoscon** [comment]
candle support added to bybit
