### ISSUE TITLE
Binance/BinanceUS using deprecated v1 API endpoints

### ISSUE THREAD

**Issue by nirvana-msu** [bmoscon/cryptofeed#639]
I've noticed that `Binance` exchange still uses deprecated [`v1` endpoints](https://github.com/bmoscon/cryptofeed/blob/8fe6fdd8abfb2407dfc273d293d2ff1769112473/cryptofeed/exchanges/binance.py#L88) which were [supposed to be removed](https://binance-docs.github.io/apidocs/spot/en/#change-log) in Q1 2020. Code should be updated to use `v3` endpoints.

Same for `BinanceUS`.

**Comment by bmoscon** [comment]
fixed
