### ISSUE TITLE
Funding symbol not normalized for Huobi Swap

### ISSUE THREAD

**Issue by agijsberts** [bmoscon/cryptofeed#642]
The symbol name for the `funding` channel of Huobi Swap is not normalized, in contrast to `l2_book` and `trade` channels. Given the recent re-organization and the consistent behavior of other exchanges, I think this is an omission rather than intentional.

Test code demonstrating the problem:
```python
from cryptofeed import FeedHandler
from cryptofeed.defines import FUNDING, TRADES
from cryptofeed.exchanges import HuobiSwap, BinanceFutures

async def trade(t, receipt_timestamp):
    print(f"Trade received for {t.symbol} at {t.exchange}")

async def funding(f, receipt_timestamp):
    print(f"Funding update received for {f.symbol} at {f.exchange}")

f = FeedHandler()
f.add_feed(HuobiSwap(symbols=['BTC-USD-PERP'], channels=[FUNDING, TRADES], callbacks={FUNDING: funding, TRADES: trade}))
f.run()
```

Corresponding output with latest git (71eb6cac7291ff98765f24edbb9fe4695a69c08b):
```
$ python3 huobi_swap_funding_norm.py 
Trade received for BTC-USD-PERP at HUOBI_SWAP
Funding update received for BTC-USD at HUOBI_SWAP
```

**Comment by agijsberts** [comment]
I believe the fix would be as easy as replacing
https://github.com/bmoscon/cryptofeed/blob/9e9143a70e8119cf5d030a3f095a925f8eddcc52/cryptofeed/exchanges/huobi_swap.py#L83 
with 
```python
self.exchange_symbol_to_std_symbol(pair),
```

Let me know though if you'd like me to prepare a PR.

**Comment by bmoscon** [comment]
@agijsberts sure, if you can create the change and test it and then raise a PR, that would help a ton!

**Comment by agijsberts** [comment]
Closed by https://github.com/bmoscon/cryptofeed/pull/643.
