### ISSUE TITLE
How do i run it with concurrent futures?

### ISSUE THREAD

**Issue by enthusiastics** [bmoscon/cryptofeed#652]
I'm trying to use crypto feed to download data concurrently. 

    f = FeedHandler()
    f.add_feed(Gateio(channels=[TRADES], symbols=list_tmp, callbacks={ TRADES: TradePostgresGateio(**postgres_cfg)}))
    f.run()

This code above can be run successfully. However, I am trying to run it in the background. So I am using concurrent futures to help.

    executor = concurrent.futures.ThreadPoolExecutor(16)
    job2 = executor.submit(f.run)

However, I got error:

    job2.result()

    ---------------------------------------------------------------------------
    RuntimeError                              Traceback (most recent call last)
    <ipython-input-54-f96e35ee3c66> in <module>
    ----> 1 job2.result()
    
    ~/anaconda3/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
        430                 raise CancelledError()
        431             elif self._state == FINISHED:
    --> 432                 return self.__get_result()
        433 
        434             self._condition.wait(timeout)
    
    ~/anaconda3/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
        386     def __get_result(self):
        387         if self._exception:
    --> 388             raise self._exception
        389         else:
        390             return self._result
    
    ~/anaconda3/lib/python3.8/concurrent/futures/thread.py in run(self)
         55 
         56         try:
    ---> 57             result = self.fn(*self.args, **self.kwargs)
         58         except BaseException as exc:
         59             self.future.set_exception(exc)
    
    ~/anaconda3/lib/python3.8/site-packages/cryptofeed/feedhandler.py in run(self, start_loop, install_signal_handlers, exception_handler)
        145             raise ValueError(txt)
        146 
    --> 147         loop = asyncio.get_event_loop()
        148         # Good to enable when debugging or without code change: export PYTHONASYNCIODEBUG=1)
        149         # loop.set_debug(True)
    
    ~/anaconda3/lib/python3.8/asyncio/events.py in get_event_loop(self)
        637 
        638         if self._local._loop is None:
    --> 639             raise RuntimeError('There is no current event loop in thread %r.'
        640                                % threading.current_thread().name)
        641 
    
    RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

Could anyone help me? Thanks so much!

**Comment by bmoscon** [comment]
you cant. You cant run asyncio loops in threads like that. You need to multiprocess if you want to parallelize it.
