### ISSUE TITLE
Do not raise an error when FeedHandler started without feeds

### ISSUE THREAD

**Issue by nirvana-msu** [bmoscon/cryptofeed#657]
**Describe the bug**
At the moment, `FeedHandler` raises `ValueError` when started without feeds.:
https://github.com/bmoscon/cryptofeed/blob/ed84b88d9e3fc4c74cda4a6bc0f5bd0122e5492d/cryptofeed/feedhandler.py#L142-L145

This should not be the case, since it is valid to add feeds after startup with `add_feed_running`.

Common use-case: dynamically subscribe to all new symbols. To do that you can first start feed handler (without any feeds), and then check and subscribe to new symbols in an infinite loop. There is no point to define feeds upfront as it would be handled by subsequent loop - it just keeps code simpler.

**To Reproduce**
```python
fh = FeedHandler()
fh.run(start_loop=False)
```

**Expected behavior**
No exception should be raised (and no error should be logged). You could log a warning if you prefer so, but I would personally set this message at an info level.

**Cryptofeed Version**
Latest, 2.0.1

P.S. while I write this, there is incorrect type annotation here - this returns `List[str]`, not `Dict`:
https://github.com/bmoscon/cryptofeed/blob/ed84b88d9e3fc4c74cda4a6bc0f5bd0122e5492d/cryptofeed/exchange.py#L73-L74

**Comment by bmoscon** [comment]
done
