### ISSUE TITLE
Allow users to configure logging themselves / avoid setting up log handlers/level

### ISSUE THREAD

**Issue by nirvana-msu** [bmoscon/cryptofeed#661]
**Is your feature request related to a problem? Please describe.**
At the moment cryptofeed forecefully configures log handlers. This is normally a task for the end-user application, not the library. I understand that cryptofeed may be used by some users as an end-user application (rather than a library) and the intentention was to make it more friendly for them, but it should at least provide an option to avoid setting up log handlers, which are messing with own log handler setup of more experienced users.

**Describe the solution you'd like**
`FeedHandler` config should have an option to avoid setting up log handlers/level. 

**Describe alternatives you've considered**
As a workaround I've had to monkey-patch `get_logger` to do nothing...
https://github.com/bmoscon/cryptofeed/blob/32f9ea252e17ac43e6b1566cee5ee012c5905f61/cryptofeed/log.py#L14

**Comment by bmoscon** [comment]
I added an option in the log section of the config. If you use this as a config:

```python
{'log': {'disabled': True}}
```

it will disable the logging. Let me know if this works for you

**Comment by bmoscon** [comment]
made the change based on the comment on the commit, closing this now
