### ISSUE TITLE
Open Interest write to Postgres

### ISSUE THREAD

**Issue by joshuaspear** [bmoscon/cryptofeed#692]
**Describe the bug**
In the write method of class OpenInterestPostgres in correct parameters are passed to the parent's write method i.e. only a dictionary should be provided.

**To Reproduce**

from cryptofeed import FeedHandler
from cryptofeed.backends.postgres import OpenInterestPostgres
from cryptofeed.defines import OPEN_INTEREST
from cryptofeed.exchanges import Binance

postgres_cfg = {'host': '127.0.0.1', 'user': 'postgres', 'db': 'postgres', 'pw': 'password'}

fh.add_feed(BinanceFutures(symbols=['BTC-USDT-PERP'], channels=[OPEN_INTEREST], 
callbacks={OPEN_INTEREST: OpenInterestPostgres(**postgres_cfg)}) 

**Expected behavior**

**Screenshots**
The data should be written to the supplied postgres db.

**Operating System:**
 macOS

**Cryptofeed Version**
- 2.0.1, pypi

### Discussed in https://github.com/bmoscon/cryptofeed/discussions/691

<div type='discussions-op-text'>

<sup>Originally posted by **joshuaspear** October 17, 2021</sup>
Hi, 

I'm having difficulty using the Postgres open interest backend. The class OpenInterestPostgres defines a write method which subsequently calls the write method defined in the parent class PostgresCallback however, I am not sure if it has been implemented correctly. The PostgresCallback write method excepts only parameter "data" however, the OpenInterestPostgres write method supplied several parameters to it which I believe is causing issues in the program I am writing. 

Please can I confirm whether this is a bug or whether I have miss understood the use of the class? If it is the latter, please could I have some guidance on how to use it. 

Thanks</div>

**Comment by aoulaa** [comment]
could you pls give more info on postgres example

**Comment by bmoscon** [comment]
its in the examples/ directory. I dont know what else to tell you since your question is extremely vague and generic.
