### ISSUE TITLE
Use trade timestamp instead of event timestamp in trade data from Binance

### ISSUE THREAD

**Issue by minglan01** [bmoscon/cryptofeed#714]
Hi,

I realize the following code in ```aync def _trade():``` for [```binance``` ](https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/exchanges/binance.py)exchange:
`self.timestamp_normalize(msg['E']),`. which "E" indicate "event timestamp". Is there a special reason to use event timestamp instead of "trade timstamp" (msg["T"])in this case?

Thanks,
Jueming

**Comment by minglan01** [comment]
To my understand, the ```trade time``` is the exact time when the trade happened. The ```event time``` is happened later when this websocket trade record being created. For a trades, the trade time is very important as we know the time sequence of trades. However the event time for those trades could have differerent order due to other factors. I agree it's hard to find the documentation for this, but I do find one [answer](https://stackoverflow.com/questions/50688471/binance-event-time-vs-trade-time) in stackoverflow which is aligned up with me.

**Comment by bmoscon** [comment]
i can post something on SO that say the opposite. I'm not saying that guy is write or wrong, but I'm not seeing anything to back up that claim. I can file a ticket with Bianace and see what they say

**Comment by minglan01** [comment]
sounds good. always good to double check to ensure. Thanks for the effort!

**Comment by minglan01** [comment]
Hi @bmoscon did you get any update? Actually, I find more relible info from binance developer forum by the moderator.  The topic is for "book update", but the terms should be applicable.
[Meaning of “event time”, “transaction time” fields](https://dev.binance.vision/t/meaning-of-event-time-transaction-time-fields/5449)

**Comment by bmoscon** [comment]
never heard back, but i made the change

**Comment by minglan01** [comment]
great!! thanks
