### ISSUE TITLE
Cant install Cryptofeed

### ISSUE THREAD

**Issue by classicalBit** [bmoscon/cryptofeed#720]
Hello,
I dont know why, but when I try to install cryptofeed (windows) I get this Error message:

ERROR: Could not build wheels for cryptofeed, which is required to install pyproject.toml-based projects

Happens when I try to install it with pip, also the cryptofeed[all] doesnt work...

Thanks in advance for the help!

**Comment by bmoscon** [comment]
wheels are not provided for windows, so you'll need to have cython installed, as well as a compiler, to use windows

**Comment by The1iAmNeo** [comment]
@bmoscon ... i have both a compiler and cython installed on my computer and i am still getting the error that it could not build wheels for cryptofeed ... is there any solution or work around to this problem?
