### ISSUE TITLE
dYdX exchange bid ask price error, bid price is greater than the ask price

### ISSUE THREAD

**Issue by trading9991** [bmoscon/cryptofeed#727]
**Describe the bug**
the bid price is greater than the ask price at dYdX exchange.

**To Reproduce**
print("receipt_timestamp: {}, computer_time: {}, feed: {}, symbol: {}, bid {}, ask :{}, bid size: {}, ask size:{}".format(receipt_timestamp,
                                                                                                                          time.time(),
                                                                                                                          book.exchange,
                                                                                                                          symbol,
                                                                                                                          book.book.bids.index(0)[0],
                                                                                                                          book.book.asks.index(0)[0],
                                                                                                                          book.book.bids.index(0)[1],
                                                                                                                          book.book.asks.index(0)[1]))
    
**Expected behavior**
the bid price should be less than ask price.

**Screenshots**
![Cryptofeed Bug](https://user-images.githubusercontent.com/94432822/144169286-3c2fec8f-c6ca-499f-9cef-54024123d1a5.PNG)

**Comment by bmoscon** [comment]
provide your version info and a working example please

**Comment by trading9991** [comment]
Verison of python:

Environment: Anaconda3
Verison of Python: 3.9
package of cryptofeed: 2.1.0

FULL CODE:

from decimal import Decimal
from datetime import datetime
from cryptofeed.defines import L2_BOOK, TRADES
from cryptofeed.exchanges import (BinanceFutures, FTX, HuobiSwap, OKEx)
from cryptofeed.exchanges.dydx import dYdX
from cryptofeed import FeedHandler

async def book(book, receipt_timestamp):

    print(
        "receipt_timestamp: {}, computer_time: {}, feed: {}, symbol: {}, bid {}, ask :{}, bid size: {}, ask size:{}".format(
            receipt_timestamp,
            time.time(),
            book.exchange,
            book.symbol,
            book.book.bids.index(0)[0],
            book.book.asks.index(0)[0],
            book.book.bids.index(0)[1],
            book.book.asks.index(0)[1]))

def main():

    feed = FeedHandler()
    feed.add_feed(dYdX(symbols = ["BTC-USD-PERP"], channels = [L2_BOOK], callbacks = {L2_BOOK: book}))
    feed.run()

if __name__ == '__main__':
    main()

**Comment by trading9991** [comment]
I found that at the very first time book.book.bids.index(0)[0] won't update, later book.book.bids.index(1)[0], won't update, and later and later book.book.bids.index(2)[0] won't update. 

![crptofeed](https://user-images.githubusercontent.com/94432822/144352111-6f096901-0f81-4e68-81c1-193f36e3a5be.PNG)

**Comment by bmoscon** [comment]
how long does it take for you to get crossed books? I ran this for 10 mins and I didn't see any crossed books. You can also enabled the `cross_check` flag on the exchange object - this will check for crossed books for you automatically.

**Comment by bmoscon** [comment]
I simplified the logic in the orderbook and fixed an issue in the book cross check code. I'm not seeing any crossed books

**Comment by bmoscon** [comment]
@trading9991 - let me know if these changes in master help your situation or not.

**Comment by trading9991** [comment]
> how long does it take for you to get crossed books? I ran this for 10 mins and I didn't see any crossed books. You can also enabled the `cross_check` flag on the exchange object - this will check for crossed books for you automatically.

probably take 10-30 mins, it is so randomly, our developers said they dont have the crossed book issue. Where can I find the `cross_check` flag on the exchange object

**Comment by bmoscon** [comment]
its in the Feed class, so its a kwarg option on every exchange object. I'm going to close this - the exchange docs indicate messages can be received out of order, so there isnt anything that can be done by cryptofeed, this is a limitation of the exchange.

**Comment by trading9991** [comment]
> its in the Feed class, so its a kwarg option on every exchange object. I'm going to close this - the exchange docs indicate messages can be received out of order, so there isnt anything that can be done by cryptofeed, this is a limitation of the exchange.

Yes, that's what our developers told me yesterday. Thank you for your help Bryant
