### ISSUE TITLE
KuCoin L2_BOOK, TypeError: 'AttrDict' object is not callable

### ISSUE THREAD

**Issue by trading8521** [bmoscon/cryptofeed#729]
**Describe the bug**

TypeError: 'AttrDict' object is not callable

**To Reproduce**
     from cryptofeed.exchanges import (KuCoin)
    
    async def book(book, receipt_timestamp):
        print(f'Book received at {receipt_timestamp} for {book.exchange} - {book.symbol}, with {len(book.book)} entries. Top of book prices: {book.book.asks.index(0)[0]} - {book.book.bids.index(0)[0]}')
    
    def main():
    
        feed = FeedHandler()
        feed.add_feed(KuCoin(symbols = ['BTC-USDT', 'ETH-USDT'], channels = [L2_BOOK], callbacks={L2_BOOK: book}))
        feed.run()
    
    if __name__ == '__main__':
        main()

**Expected behavior**
Expected can print the order book, since I believe the KuCoin L2_BOOK is applicable.

**Screenshots**
![Kucoin](https://user-images.githubusercontent.com/92103509/144699879-51069b6a-9eb2-4a04-b8fd-d9115f66bda6.png)

**Operating System:**
Windows

**Cryptofeed Version**
2.1.1

**Comment by bmoscon** [comment]
pretty sure that is coming from the config, so however you are specifying the keys and whatnot seems to be the issue. if you can provide an example (minus your keys of course) I can take a look

**Comment by bmoscon** [comment]
or the issue is that you are not specifying a key - kucoin requires an api key to get order books

**Comment by bmoscon** [comment]
an error is now properly raised if this is tried without an API key
