### ISSUE TITLE
Support new channels for different data feed types (swap, futures, etc)

### ISSUE THREAD

**Issue by bmoscon** [bmoscon/cryptofeed#73]
OkEx supports swaps, futures, and margin

**Comment by bmoscon** [comment]
@rendonghai what exchanges support these other channel types?

**Comment by rendonghai** [comment]
okex first, kraken and huobi also have futures

**Comment by bmoscon** [comment]
@rendonghai swaps now supported on OkEX

**Comment by rendonghai** [comment]
@bmoscon good news

**Comment by bmoscon** [comment]
marking this as closed since there are other feeds now that support these that have been added. new tickets can be opened for individual exchanges/types
