### ISSUE TITLE
There is a simple error in this line, need to put Decimal() into the left side of the / .

### ISSUE THREAD

**Issue by badosanjos** [bmoscon/cryptofeed#740]
https://github.com/bmoscon/cryptofeed/blob/6bb55d30a46f50ff9d28e6297e1c0f97f4040825/cryptofeed/exchanges/binance.py#L498

**Comment by badosanjos** [comment]
I need to learn Git to can contribute better :)

**Comment by bmoscon** [comment]
fixed
