### ISSUE TITLE
crypto.com 1w and 1M not working

### ISSUE THREAD

**Issue by p0nt** [bmoscon/cryptofeed#755]
It seems that the 1w and 1M options on crypto.com candle feed is not working, while in the docs it states that these candles should be available.

I tried:

- 1w
- 1W
- 7d
- 7D

```2021-12-31 14:22:42,100 : WARNING : CRYPTO.COM: Error received from exchange {'id': -1, 'method': 'subscribe', 'code': 40003, 'message': 'Invalid timeframe - [candlestick.7D.XLMUSD-PERP]'}```

```valid_candle_intervals = {'1m', '5m', '15m', '30m', '1h', '4h', '6h', '12h', '1d', '1w', '2w', '1M'}```

**Comment by bmoscon** [comment]
Please provide a working code sample that reproduces this - I can't reproduce this

**Comment by bmoscon** [comment]
also provide the version of the library and the OS you are using

**Comment by bmoscon** [comment]
i cant reproduce this, and no response from submitter. closing.
