### ISSUE TITLE
Deribit raw feeds are no longer allowed on unauthenticated connections

### ISSUE THREAD

**Issue by wanx4910** [bmoscon/cryptofeed#768]
**Describe the bug**
The current deribit.py in cryptofeed/exchanges appear to use the raw feeds for market data. This appears to be no longer allowed by Deribit, please refer to: https://www.deribit.com/kb/15-january-release . 
The issue seems to be able to be fixed by using the 100ms aggregated channel instead of raw channel.

https://github.com/bmoscon/cryptofeed/blob/9fa6e4f94a7746d48fb9043a6cd522d4ad861c79/cryptofeed/exchanges/deribit.py#L229

**To Reproduce**
None, just subscribing to Deribit using the current version of cryptofeed seems to be able to reproduce this issue.

**Expected behavior**
Raise an exception or notify upon unsuccessful subscription.

**Screenshots**
When I used my own websocket script to test the issue.
{"jsonrpc":"2.0","id":"cryptofeed","error":{"message":"raw_subscriptions_not_available_for_unauthorized","code":13778},"usIn":1642494034550822,"usOut":1642494034551046,"usDiff":224,"testnet":false}

**Operating System:**
 - macOS

**Cryptofeed Version**
- please list the version you are using, and how it was installed (from source, pypi, etc).

**Comment by bmoscon** [comment]
fixed on master

**Comment by bmoscon** [comment]
to be clear, the fix was to require authentication
