### ISSUE TITLE
Writing Candle Data to influxdb (and maybe others) fails due to wrong line protocol formatting

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [bmoscon/cryptofeed#771]
**Describe the bug**
When using the InfluxDB backend it is not possible to write candle data as the line protocol string that is generated and posted via the HTTP Backend is not valid:

Example:
`ERROR : POST to http://192.168.1.x:8086/api/v2/write?org=myorg&bucket=crypto&precision=us failed: 400 - {"code":"invalid","message":"unable to parse 'candles-CRYPTO.COM,symbol=ANY-USDT start=1642700100.0,stop=1642700159.0,interval=\"1m\",trades=None,open=25.543,close=25.607,high=25.607,low=25.535,volume=0.235,closed=False,timestamp=1642700168.3890743,receipt_timestamp=1642700168.3890743 1642700168389074': invalid number"}`

This string puts non-numeric values into the fields section of the line protocol string, which is defined as such:
`|measurement|,tag_set| |field_set| |timestamp|`

In the above example the trades=None, the interval="1m" and the closed=False are not valid fields.

**To Reproduce**
`f = FeedHandler()
    f.add_feed(CryptoDotCom(symbols=["ANY-USDT"], channels=[CANDLES], callbacks={CANDLES: CandlesInflux(INFLUX_ADDR, ORG, BUCKET, TOKEN)}))`

**Expected behavior**
proper storage for candles data in influxdb measurement

**Operating System:**
 - any

**Cryptofeed Version**
- pypi/latest

**Notes**
IMO it would make sense to use the excellent influxdb-client python library instead of a generic http backend for influxDB. This would provide a lot more resilience for writing to influxDB.

**Comment by bmoscon** [comment]
@reinhard-brandstaedter  the python library you refer to does not support asyncio, so it cannot be used

**Comment by bmoscon** [comment]
fixed on master
