### ISSUE TITLE
How to get a list of crypto pairs that an exchange supports ? 

### ISSUE THREAD

**Issue by YuriyTigiev** [bmoscon/cryptofeed#775]
How to get a list of crypto pairs that an exchange supports ? 
Are there any restrictions on the number of subscriptions on one exchange?

**Comment by peedrr** [comment]
1. `Binance.symbols()` (or whichever exchange you're interested in)
2. Not set by Cryptofeed, no. Individual exchanges may set some limits and obviously your computer's processing power might become a limitation at some point, in which case you may need to look at multiprocessing

**Comment by YuriyTigiev** [comment]
Thank you!  Great library !

As I understand I should use multiple IP  as a solution for the case below - "Kucoin has a limit of 300 symbols per connection."
It's looks like the solution should use dockers with different public IP or  configure ha proxy with multiple public IP.

**Comment by bmoscon** [comment]
or just create multiple connections with the same IP. There are all sorts of limits that each exchange might have. symbols per connection is not the same as an IP limit - it just means you need multiple connections if you need to subscribe to more than 300 symbols

**Comment by peedrr** [comment]
Your docker solution would get around any CPU issues. If you're processing order books, for example, you'll likely hit CPU probs well before 300 pairs

**Comment by YuriyTigiev** [comment]
Is it possible to use this library to download historical OHLCV data and trades?

**Comment by bmoscon** [comment]
for some exchanges, yes

**Comment by peedrr** [comment]
Search is your friend. E.g.
https://github.com/bmoscon/cryptofeed/issues/623

**Comment by YuriyTigiev** [comment]
> for some exchanges, yes

For example bybit and kucoin have not a method trade_sync. Is there because the development of library in the progress?

**Comment by bmoscon** [comment]
I'm not currently working on them. if you need them your options are 1) file a github issue and someone might do it at some point, or 2) add support and open a PR
