### ISSUE TITLE
yapic.json breaks PyPy

### ISSUE THREAD

**Issue by oberstet** [bmoscon/cryptofeed#777]
**Describe the bug**

This library depends on yapic.json, which breaks PyPy https://gist.github.com/oberstet/27ae1df176aee25271ffb0023cd8008f

PyPy https://www.pypy.org/ is a tracing JIT compiler for Python with an incremental garbage collector.

JSON is very likely the fastest with plain Python JSON included with PyPy. Here are some hard numbers https://crossbario.com/docs/benchmarks/serialization/index.html

**To Reproduce**

`pip install -e .` on the master branch using pypy

```
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty/cryptofeed$ pypy -V
Python 3.8.12 (9ef55f6fc369, Oct 24 2021, 20:11:54)
[PyPy 7.3.7 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

**Expected behavior**

The fastest JSON depends on and differs by the Python _implementation_. Most important: CPython vs PyPy

One way to solve that is make the setup.py auto select the right one, eg here is a lib that does that:

https://github.com/crossbario/autobahn-python/blob/7becdaae12db7abee390dd86d4e247f5071b91ab/setup.py#L69

**Comment by bmoscon** [comment]
I don't support PyPy. If that library doesn't work with PyPy, seems like this bug belongs there?

**Comment by bmoscon** [comment]
I can also tell you its unlikely that the orderbooks library will work with pypy either

**Comment by bmoscon** [comment]
all that being said, if you remove the yapic.json req, and replace all the imports with just json, and it works, and its faster, I'll accept a PR

**Comment by oberstet** [comment]
so the orderbook thing seems to work .. I can run the test with no output (which means good?):

```
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty$ git clone https://github.com/bmoscon/orderbook.git
Klone nach 'orderbook' ...
remote: Enumerating objects: 707, done.
remote: Counting objects: 100% (371/371), done.
remote: Compressing objects: 100% (275/275), done.
remote: Total 707 (delta 228), reused 190 (delta 90), pack-reused 336
Empfange Objekte: 100% (707/707), 152.38 KiB | 5.25 MiB/s, fertig.
Löse Unterschiede auf: 100% (412/412), fertig.
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty$ cd orderbook/
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty/orderbook$ pip install -e .
Obtaining file:///home/oberstet/scm/3rdparty/orderbook
Installing collected packages: order-book
  Attempting uninstall: order-book
    Found existing installation: order-book 0.4.1
    Uninstalling order-book-0.4.1:
      Successfully uninstalled order-book-0.4.1
  Running setup.py develop for order-book
Successfully installed order-book-0.4.2
WARNING: You are using pip version 21.1.1; however, version 22.0.3 is available.
You should consider upgrading via the '/home/oberstet/pypy38_1/bin/python -m pip install --upgrade pip' command.
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty/orderbook$ pypy tests/test_orderbook.py 
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty/orderbook$ pypy -c "from order_book import OrderBook"
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty/orderbook$ pypy -V
Python 3.8.12 (9ef55f6fc369, Oct 24 2021, 20:11:54)
[PyPy 7.3.7 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty/orderbook$ 
```

----

fwiw, PyPy supports Cython, but it doesn't support the full CPython internal and unstandardized extension C API (called "cpyext")

if you explicitly do not want to discuss/aim for pypy, then by adding selectively these tags to the setup.py would communicate this:

```
                 "Programming Language :: Python :: Implementation :: CPython",
                 "Programming Language :: Python :: Implementation :: PyPy",
```

----

> and replace all the imports with just json, and it works, and its faster, I'll accept a PR

Ok, awesome! that's sth I can work from:)

yes, my itch is: receiving from 10 exchanges 30 pairs each will saturate a single threaded CPython.

the way I solve that usually is: just use pypy;)

anyways, I see what I can come up with .. thanks!!

**Comment by oberstet** [comment]
@bmoscon alright, it works on pypy, but it is slower, pls see https://github.com/bmoscon/cryptofeed/pull/778

so I close this issue (you might want to add the tag for CPython .. or not)
