### ISSUE TITLE
Support bybit candles -> is closed

### ISSUE THREAD

**Issue by regonw** [bmoscon/cryptofeed#782]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I would like to store only confirmed data from bybit.

**Describe alternatives you've considered**
Add following to bybit.py

    def __init__(self, candle_closed_only=False, **kwargs):
        super().__init__(**kwargs)
        self.candle_closed_only = candle_closed_only
        self.ws_defaults['compression'] = None

Edit following in bybit.py

    async def _candle(self, msg: dict, timestamp: float):
        '''
        {
            "topic": "klineV2.1.BTCUSD",                //topic name
            "data": [{
                "start": 1572425640,                    //start time of the candle
                "end": 1572425700,                      //end time of the candle
                "open": 9200,                           //open price
                "close": 9202.5,                        //close price
                "high": 9202.5,                         //max price
                "low": 9196,                            //min price
                "volume": 81790,                        //volume
                "turnover": 8.889247899999999,          //turnover
                "confirm": False,                       //snapshot flag
                "cross_seq": 297503466,
                "timestamp": 1572425676958323           //cross time
            }],
            "timestamp_e6": 1572425677047994            //server time
        }
        '''
        symbol = self.exchange_symbol_to_std_symbol(msg['topic'].split(".")[-1])
        ts = msg['timestamp_e6'] / 1_000_000

        for entry in msg['data']:

>             if self.candle_closed_only and entry['confirm']:

                c = Candle(self.id,
                    symbol,
                    entry['start'],
                    entry['end'],
                    self.candle_interval,
                    None,
                    Decimal(entry['open']),
                    Decimal(entry['close']),
                    Decimal(entry['high']),
                    Decimal(entry['low']),
                    Decimal(entry['volume']),
                    

> entry['confirm'],

                    ts,
                    raw=entry)
                await self.callback(CANDLES, c, timestamp)

Can you please add this. Thank you and best regards.

**Comment by bmoscon** [comment]
I'm not sure what you are asking for. Seems like you can open a PR if you know specifically what you want?

**Comment by bmoscon** [comment]
done
