### ISSUE TITLE
Elastic backend got double index name

### ISSUE THREAD

**Issue by huanweisu** [bmoscon/cryptofeed#794]
Here is my example code, feedhander BTC-USD from Coinbase then input to elastic, got 400 bad request response. Looks it have double "trade" index when inputing?

from cryptofeed import FeedHandler
from cryptofeed.backends.elastic import TradeElastic
from cryptofeed.defines import TRADES
from cryptofeed.exchanges import Coinbase

eshost = "http://172.30.1.12:9200"

def main():
    f = FeedHandler()
    f.add_feed(Coinbase(channels=[TRADES], symbols=['BTC-USD'], callbacks={ TRADES: TradeElastic(eshost, numeric_type=float)}))
    f.run()

if __name__ == '__main__':
    main()

![截圖 2022-02-24 下午6 00 16](https://user-images.githubusercontent.com/29561837/155503128-a5adfb19-8949-45be-8e43-61ad6642cf81.png)

**Comment by bmoscon** [comment]
elasticsearch is going away in the next release, so I'm going to close this. Sorry it is no longer supported.
