### ISSUE TITLE
Approaches to detect gaps for candles and ohlcv data

### ISSUE THREAD

**Issue by YuriyTigiev** [bmoscon/cryptofeed#797]
What are approaches to detect gaps for candels and ohlcv data for case when using WebSocket ?

**Comment by bmoscon** [comment]
since you are specifying the interval you would know if you dont get any data after that amount of time. you can also sync with the rest api after the fact to check for missing data

**Comment by YuriyTigiev** [comment]
> since you are specifying the interval you would know if you dont get any data after that amount of time. you can also sync with the rest api after the fact to check for missing data

This approach will work for candles.  What about trades? Some exchanges don't have incremental integer like a "trade_id".

**Comment by bmoscon** [comment]
assuming there are no other questions, so closing this since i havent heard anything in a few weeks
