### ISSUE TITLE
dydx l2 orderbook error.

### ISSUE THREAD

**Issue by wsg011** [bmoscon/cryptofeed#799]
dydx exchange orderbook data some time error, please check bid and ask price.

suggest:

```
def _checkbook(self, pair: str):
        bid0_price = self._l2_book[pair].book["bids"].keys()[0]
        ask0_price = self._l2_book[pair].book["asks"].keys()[0]

        if bid0_price > ask0_price:
            self.__reset()
            raise KeyError("bid price > ask price")
```

**Comment by bmoscon** [comment]
sorry, this is a known issue with the exchange. They've indicated they dont have the resources to fix their data channels, so nothing I can do about it. See https://github.com/bmoscon/cryptofeed/issues/727 or many other tickets opened with similar issues

**Comment by wsg011** [comment]
ok, thank you bmoscon

**Comment by LucCADORET** [comment]
Looking at their frontend queries, they have an undocumented "batched" boolean when subscribing. 
e.g.:
```
{
batched: true
channel: "v3_orderbook"
id: "ETH-USD"
type: "subscribe"
}
```
Doing so will result in getting the data in "batches", that you can sort by offsets to get the data in the right order much much more easily than without the batches. It still seems that you can get unordered offsets between two batches though, but it should be less frequent. You can do additional digging in their frontend to see how they handle it when this happens.

**Comment by wsg011** [comment]
> Looking at their frontend queries, they have an undocumented "batched" boolean when subscribing. e.g.:
> 
> ```
> {
> batched: true
> channel: "v3_orderbook"
> id: "ETH-USD"
> type: "subscribe"
> }
> ```
> 
> Doing so will result in getting the data in "batches", that you can sort by offsets to get the data in the right order much much more easily than without the batches. It still seems that you can get unordered offsets between two batches though, but it should be less frequent. You can do additional digging in their frontend to see how they handle it when this happens.

thx

**Comment by 9cat** [comment]
> > Looking at their frontend queries, they have an undocumented "batched" boolean when subscribing. e.g.:
> > ```
> > {
> > batched: true
> > channel: "v3_orderbook"
> > id: "ETH-USD"
> > type: "subscribe"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Doing so will result in getting the data in "batches", that you can sort by offsets to get the data in the right order much much more easily than without the batches. It still seems that you can get unordered offsets between two batches though, but it should be less frequent. You can do additional digging in their frontend to see how they handle it when this happens.
> 
> thx

have you finally solve this problem?  any share?
