### ISSUE TITLE
Is there a way to avoid installing GCC to install?

### ISSUE THREAD

**Issue by ideoma** [bmoscon/cryptofeed#801]
I'm trying to install it on EC2 instance on Amazon Linux 2 and it is trying to compile using GCC. Is there  a way to avoid it?

[scratch_12.txt](https://github.com/bmoscon/cryptofeed/files/8199539/scratch_12.txt)

pip 22.0.4 
python 3.7.10

**Comment by bmoscon** [comment]
upgrade to python 3.8+ - 3.7 is no supported and wheels are not build for 3.7. The wheels that are built are listed here: https://pypi.org/project/cryptofeed/2.2.1/#files

**Comment by bmoscon** [comment]
if you have more questions let me know, but closing this for now
