### ISSUE TITLE
possible bug: check with capital "U" guards access with lowercase

### ISSUE THREAD

**Issue by shaunc** [bmoscon/cryptofeed#822]
This seems like a bug, though I haven't hit it: note `msg['U']` vs `msg['u']`.

https://github.com/bmoscon/cryptofeed/blob/097bdabd071d4998448eb7f45a01b1d2b6b3e7c2/cryptofeed/exchanges/binance.py#L266-L267

**Comment by bmoscon** [comment]
the code follows the docs: https://binance-docs.github.io/apidocs/spot/en/#how-to-manage-a-local-order-book-correctly

Feel free to verify and raise an issue if you find a bug

**Comment by shaunc** [comment]
Right -- sorry about that!
