### ISSUE TITLE
import cython file error

### ISSUE THREAD

**Issue by IMTAIHUN** [bmoscon/cryptofeed#825]
I got an error with `import cryptofeed.`
Error caused by `feed.py` file line 20.
`from cryptofeed.types import OrderBook
`
`types.pyx` is a `cython` file, there is an import error.
so I think adding some lines before importing `types.pyx` would be a solution.

in feed.py file, edit line 20 with 

```
import pyximport 
pyximport.install() 
from cryptofeed.types import OrderBook
```

with this code, the problem is solved. 

I'm using mac OS with apple silicon.

**Comment by bmoscon** [comment]
if using the code from source you have to build/install it first. yopu dont need to do what you have described here, you need to run something like `python setup.py develop` or `python setup.py install`
