### ISSUE TITLE
No closed candles with Kraken exchange

### ISSUE THREAD

**Issue by Franky1** [bmoscon/cryptofeed#827]
**Describe the bug**
I never see any closed candles with Kraken exchange, `closed` is always `False`.

**To Reproduce**

```python
from cryptofeed import FeedHandler
from cryptofeed.defines import CANDLES
from cryptofeed.exchanges import Kraken

async def candle_callback(c, receipt_timestamp):
    if c.closed == True:
        print(f"Candle received at {receipt_timestamp}: {c}")

def main():
    fh = FeedHandler()
    fh.add_feed(Kraken(symbols=['BTC-USD'], candle_interval='1m', candle_closed_only=True, channels=[CANDLES], callbacks={CANDLES: candle_callback}))
    fh.run()

if __name__ == '__main__':
    main()
```

**Operating System:**
 - win10x64

**Cryptofeed Version**
- pypi, version 2.2.2

**Comment by bmoscon** [comment]
not every exchange provides a marker when its the last candle. you can tell on your end by checking for the change in the start/stop interval. The last candle on an interval is the closed candle
