### ISSUE TITLE
Does redis backend offer simple in memory key:value?

### ISSUE THREAD

**Issue by grepsuzette** [bmoscon/cryptofeed#830]
What I'm after is something very simple (holding last price per pair, or maybe better, last bid and last ask) like this in memory, so Redis can be queried by other parties:
```python
import redis                                                                  
                                                                                       
async def redis_it(t, receipt_timestamp):                                              
    redis.Redis().set(f"lastprice:{t.exchange}:{t.symbol}", '{0:f}'.format(t.price))

...
f.add_feed(Binance(symbols=Binance.symbols()[0:199], channels=[TRADES], callbacks={TRADES: redis_it})) 
```
While this work (after a `pip install redis`), I am wanting to use `cryptostore` right now to use with docker.
If not possible, I may prepare a PR but I will need direction regarding the names to use as I'm fairly new to this.

(Thanks for cryptofeed btw, it rocks!)

**Comment by bmoscon** [comment]
no, though the redis backend should be easily modifiable to do something like this.
