### ISSUE TITLE
exchange_channel_to_std doesn't support one-to-many mapping

### ISSUE THREAD

**Issue by dirtyValera** [bmoscon/cryptofeed#843]
Current implementation of `exchange_channel_to_std` in `exchange.py` assumes 1-to-1 mapping of exchnage<->std channels, which is not always true. 

Example: for Bybit, `INDEX`, `OPEN_INTEREST` and `FUNDING` channels use `'instrument_info.100ms'` websocket channel. If I subscribe to all those channels, some/all callbacks will refer to `'index'` data_type/channel (as first found, according to current logic), which may cause inconsistencies (e.g. wrong field on data model/wrong callback triggered).

**Comment by bmoscon** [comment]
@dirtyValera can you provided an example of a mapping for bybit that is not one to one?

**Comment by bmoscon** [comment]
no more info provided - closing
