### ISSUE TITLE
Race condition in L2 book subscription for Bybit and some other exchanges

### ISSUE THREAD

**Issue by agijsberts** [bmoscon/cryptofeed#848]
**Describe the bug**
Intermittently on one VPS I noticed a `KeyError` for Bybit:
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/cryptofeed/connection_handler.py", line 69, in _create_connection
    await self._handler(connection, self.handler)
  File "/home/user/.local/lib/python3.9/site-packages/cryptofeed/connection_handler.py", line 119, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/home/user/.local/lib/python3.9/site-packages/cryptofeed/exchanges/bybit.py", line 170, in message_handler
    await self._book(msg, timestamp)
  File "/home/arjanuser/.local/lib/python3.9/site-packages/cryptofeed/exchanges/bybit.py", line 378, in _book
    del self._l2_book[pair].book[side][price]
KeyError: 'BTC-USD-PERP'
```
I've debugged the problem and it is due to a race condition when the channel subscription is split in multiple calls to the `subscribe` method of the exchange. Each call to `subscribe` will reset the entire `_l2_book` attribute, which is problematic if it already received the initial l2 order book snapshot from a previous call to `subscribe`. A subsequent delta update will then cause this `KeyError`, since all received data was just wiped. 

The channel subscription may end up being split in multiple calls to `subscribe` if there are distinct endpoints for certain currencies (Bybit) or if there is a limit on how many symbols can be requested in a single channel subscription message (Phemex, Kraken, Bitfinex).

**To Reproduce**
Since the problem only occurs if an order book snapshot is received before the second `subscribe` call clears out `_l2_book`, in the following example code I manipulate the timings of the calls to ensure we reliably reproduce the problem. However, the problem also occurs "in the wild" provided that the RTT to the exchange is short enough. The commented line shows the same problem with the Kraken exchange.

```python
from asyncio import sleep

from cryptofeed import FeedHandler
from cryptofeed.defines import L2_BOOK
from cryptofeed.exchanges import Bybit, Kraken


import logging
LOG = logging.getLogger('feedhandler')

def delayfrom2nd():
    def wrapper(func):
        state = {'delay': 0}
        async def wrapped(*args, **kwargs):
            LOG.info('sleeping %s seconds', state['delay'])
            await sleep(state['delay'])
            state['delay'] = 2
            return await func(*args, **kwargs)
        return wrapped
    return wrapper

Bybit.subscribe = delayfrom2nd()(Bybit.subscribe)
Kraken.subscribe = delayfrom2nd()(Kraken.subscribe)

async def book(book, receipt_timestamp):
    pass

def main():
    config = {'log': {'filename': 'demo.log', 'level': 'DEBUG', 'disabled': False}}
    f = FeedHandler(config=config)

    f.add_feed(Bybit(checksum_validation=True, symbols=["BTC-USD-PERP", "BTC-USDT-PERP"], channels=[L2_BOOK], callbacks={L2_BOOK: book}))
#    f.add_feed(Kraken(checksum_validation=True, symbols=['1INCH-EUR', '1INCH-USD', 'AAVE-AUD', 'AAVE-ETH', 'AAVE-EUR', 'AAVE-GBP', 'AAVE-USD', 'AAVE-BTC', 'ACA-EUR', 'ACA-USD', 'ADA-AUD', 'ADA-ETH', 'ADA-EUR', 'ADA-GBP', 'ADA-USD', 'ADA-USDT', 'ADA-BTC', 'AGLD-EUR', 'AGLD-USD', 'AIR-EUR', 'AIR-USD'], channels=[L2_BOOK], callbacks={L2_BOOK: book}))
    f.run()


if __name__ == '__main__':
    main()
```

**Cryptofeed Version**
Latest git.

**Comment by agijsberts** [comment]
I'm looking into resolving this issue and I see two approaches. The most obvious is to add an argument to `__reset` to pass a list of channels that need to be cleared from the `_l2_book` attribute. If this argument is not passed, then we maintain the current behavior of resetting the entire attribute.

A more radical approach would be to avoid resetting the order book data. This is based on the assumption that a subscription will start with a snapshot, which will overwrite previous order book data for that symbol anyways. Looking at the implementation of Bybit I believe this would work, but I'm not sure if I'm overlooking maybe some side effects in case of the implementation of other exchanges.

Any suggestions are welcome.

**Comment by bmoscon** [comment]
@agijsberts when the connection is reset the orderbook needs to be cleared out. thats why its called in subscribe. probably need to pass a list of symbols to reset

**Comment by agijsberts** [comment]
Ok, I'll have a closer look at the various exchanges and I volunteer to prepare a PR in the coming days.

**Comment by bmoscon** [comment]
merged
