### ISSUE TITLE
pip version of cryptofeed not updated

### ISSUE THREAD

**Issue by JKOK005** [bmoscon/cryptofeed#850]
**Describe the bug**
Current latest version of cryptofeed is `2.2.3` with the most recent changes made to okx order book. 

However, `pip install cryptofeed` installs the version `2.2.2`. Also, I'm noticing that the version of cryptofeed installed by cryptostore docker image build is `2.2.1`.

**To Reproduce**

`pip install --upgrade --no-cache-dir cryptofeed==`

Output:
`ERROR: Could not find a version that satisfies the requirement cryptofeed== (from versions: 0.0.1.linux-x86_64, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.22.0, 0.22.1, 0.22.2, 0.23.0, 0.24.0, 0.25.0, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)`

shows that the latest version registered in pypi is 2.2.2

In addition, the latest version recorded in Pypi is `2.2.2` (https://pypi.org/project/cryptofeed/#history)

Would it be possible to update pip with the latest version? Thanks

**Comment by bmoscon** [comment]
thats not a bug, im not doing to do a release for every change. if you want the latest code, use what is in github.
