### ISSUE TITLE
Open interest is not working in both BINANCE_FUTURES and BINANCE_DELIVERY

### ISSUE THREAD

**Issue by likso** [bmoscon/cryptofeed#869]
**Describe the bug**
Open interest is not working in both BINANCE_FUTURES and BINANCE_DELIVERY

**Cryptofeed Version**
2.2.3

**Comment by TnzGit** [comment]
Can confirm, error msg as below:

> aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://fapi.binance.com/fapi/v1//openInterest?symbol=BTCUSDT')

**Comment by agijsberts** [comment]
@TnzGit Thanks for spotting the problem. I've taken the liberty to prepare a PR that includes this fix.
