### ISSUE TITLE
how to get snapshot data in okx

### ISSUE THREAD

**Issue by xubinlaile** [bmoscon/cryptofeed#888]
![image](https://user-images.githubusercontent.com/43530705/181509158-1894f53e-b3de-4ef5-b947-550de3a6e4b3.png)

**Comment by bmoscon** [comment]
not sure how highlighting some stuff from the docs is a question. What is your question? If you want the book data snapshot, thats the same as subscribing to the L2 book data feed in cryptofeed.

**Comment by xubinlaile** [comment]
thanks for your attention. I test one demo success in linux, I get the log such as 'Delta from last book contains 155 entries',  what is the releationship between delta data and snapshot data, how can I get the snapshot data?

**Comment by xubinlaile** [comment]
as the picture shows below, i guess the delta data may be incremental data,  does the frame support merging incremental data into full data?

**Comment by xubinlaile** [comment]
how can I get the csv data of snapshot? thanks for your reply.

**Comment by xubinlaile** [comment]
> not sure how highlighting some stuff from the docs is a question. What is your question? If you want the book data snapshot, thats the same as subscribing to the L2 book data feed in cryptofeed.

base on the doc, when subscribe book default, incremental data will be pushed every 100 ms when there is change in order book, how can i subscribe the different channel 'books50-l2-tbt' in which the incremental data will be pushed every 10 ms
![image](https://user-images.githubusercontent.com/43530705/181697837-5570a3ad-93b1-4c06-bbfc-25689f7467b8.png)

**Comment by bmoscon** [comment]
cryptofeed uses books - the 400 depth book that is updated every 100 ms. to have it use anything else youd have to change the code yourself.
