### ISSUE TITLE
Poloniex L2, L3 books support

### ISSUE THREAD

**Issue by greenclaw** [bmoscon/cryptofeed#90]
Trying to receive data from Poloniex exchange, my code:
`f.add_feed(Poloniex(channels=[L2_BOOK], callbacks={L2_BOOK: BookCallback(book)}))
`

But always have this error:
`cryptofeed.exceptions.UnsupportedDataFeed: l2_book is not supported on POLONIEX`

The same for l3_book. 
Does anybody have the same error or Poloniex doesn't support l2/l3?

**Comment by bmoscon** [comment]
@greenclaw See the first Q in the FAQ:

https://github.com/bmoscon/cryptofeed/blob/master/FAQ.md


Its not ideal to do it that way, but I'm open to suggestions if you feel there is another way it could be done. I suppose I could allow the user to specify information channels and just ignore them - i guess it wouldnt hurt?

**Comment by bmoscon** [comment]
also see `examples/demo.py`

this is a subscription for poloniex, L2 book data (and tickers). Book data will be returned for BTC-USDT and BTC-USDC

`f.add_feed(Poloniex(channels=[TICKER, 'BTC-USDT', 'BTC-USDC'], callbacks={L2_BOOK: BookCallback(book), TICKER: TickerCallback(ticker)}))`

**Comment by bmoscon** [comment]
@greenclaw you raised a good issue, so I tweaked poloniex to behave like the others in terms of subscribing to the pairs/channels. Its on mater now, will release to pypi later this week

**Comment by greenclaw** [comment]
Oh, thank you indeed!, that was not clear is the problem in library or just in parameters I passed.
