### ISSUE TITLE
BTCAUCTION-USD messed with BTC-USD in Coinbase

### ISSUE THREAD

**Issue by xc5211** [bmoscon/cryptofeed#928]
During data feed init for ticker BTC-USD at Coinbase, instead of streaming data feed of BTC-USD, it sometimes receives feed of BTCAUCTION-USD. Whether the program chooses to receive BTC-USD or BTCAUCTION-USD is pretty random. 

After some shallow dig, seems the issue is around the symbol conversion back from normalized version (https://github.com/bmoscon/cryptofeed/blob/00e30db6ecbcd2b34a130bd61f7f903160b586d8/cryptofeed/feed.py#L202).

**Comment by bmoscon** [comment]
fixed
