### ISSUE TITLE
How to correctly read Bitmex L3 from influxdb

### ISSUE THREAD

**Issue by tomastoth** [bmoscon/cryptofeed#93]
Hello,

I am trying to read a XBTUSD L3 orderbook that I am saving to influxdb database. I am using influxdb python library and using this code:

`class DbReader(Thread):

    def __init__(self):
        Thread.__init__(self)

    def run(self):
        client = InfluxDBClient('localhost', 8086, 'root', 'root', 'xbtusd2')
        result = client.query('SELECT * FROM BITMEX')
        rs = (result.get_points(measurement='BITMEX'))
        old_ts = 0
        asks = SortedDict()
        bids = SortedDict()
        ob_handler = oh.ObHandler()

        for ts in rs:
            new_ts = ts['time']
            if old_ts == 0:
                old_ts = new_ts
            if new_ts == old_ts:
                if ts['side'] == 'ask':
                    asks[ts['price']] = ts['amount']
                else:
                    bids[ts['price']] = ts['amount']
            else:
                # if len(bids) > 0 and len(asks) > 0:
                #     ob_handler.handle_ob([bids, asks])
                # else:
                #     print(f'len asks: {len(asks)}, len bids: {len(bids)}')
                old_ts = new_ts
                best_ask = asks.iloc[0]
                best_bid = bids.iloc[-1]
                spread = best_ask - best_bid
                # if spread > 4:
                print(f'spread: {spread}')
                asks.clear()
                bids.clear()`

It seems that the spread between the best bid and ask is usually 1 or 0.5 which is great. But many times the spread reaches values like:
spread: 15
spread: 11.5
spread: 10.5
spread: 7.5
spread: 6.5
spread: 6.5
spread: 6.0

Which might be normal if someone was doing a lot of market buys, but I wanted to ask if there might be something wrong with my code which could be causing this to happen.

Thanks

**Comment by tomastoth** [comment]
By the way I tried separating the updates by timestamp too, even worse results.

**Comment by bmoscon** [comment]
I'm looking into this, first i'm just running a test to verify that the data coming from the book updates looks correct (raw) to make sure its not an issue with that, then I'll make sure nothing is amiss with the writing for influx. 

So far its looking like an issue with  the influx backend. Can you tell me how long you ran your test before you saw the unreasonable spreads?

**Comment by tomastoth** [comment]
This was just after few minutes of saving.

**Comment by tomastoth** [comment]
@bmoscon BTW, what is the appropriate way to group the orderbook updates? I mean if I wanna group by updates. So when I am recreating the orderbook I can get full orderbook at the time of update.

Thanks

**Comment by bmoscon** [comment]
@tomastoth there is an issue with the tagging in influx. I'm not an influxdb expert, I dont use it much, but I do know that if you write data with the same timestamp, and the same tag, they basically overwrite eachother. The tag + timestamp is the "key" for the data. So the book is storing the data with a tag that is not unique enough, so data is being overwritten. I'm working on a fix. Should be out tonight or tomorrow, and if not then, definitely before next week. Thanks for raising the issue

**Comment by tomastoth** [comment]
> @tomastoth there is an issue with the tagging in influx. I'm not an influxdb expert, I dont use it much, but I do know that if you write data with the same timestamp, and the same tag, they basically overwrite eachother. The tag + timestamp is the "key" for the data. So the book is storing the data with a tag that is not unique enough, so data is being overwritten. I'm working on a fix. Should be out tonight or tomorrow, and if not then, definitely before next week. Thanks for raising the issue

you are a boss :)

**Comment by bmoscon** [comment]
issue should be fixed now. For book update you need to group them by "timestamp". Entries with the same timestamp are part of the same book.
