### ISSUE TITLE
Not working on tcp or udp socket

### ISSUE THREAD

**Issue by dantesholiday** [bmoscon/cryptofeed#959]
**Describe the bug**
In your sample with demo_udp.py, demo_tcp.py.. It doesn't make any message return.

**Operating System:**
 - linux, silicon macOS, but not tried with windows.

**Cryptofeed Version**
latest version with pip installation. I could find the bug

**Comment by DSmyungjin** [comment]
this demo works at 2.2.1 version 
since 2.2.2 version it doesn't work

**Comment by bmoscon** [comment]
this has been fixed - thanks to @DSmyungjin
