### ISSUE TITLE
Custom license?

### ISSUE THREAD

**Issue by ideoma** [bmoscon/cryptofeed#962]
Would you be able to clarify if the license for the source code is any well-known licenses like Apache, BSD, or MIT?
Or is it a custom license that combines clauses from a few well-known ones?

This is the version I'm talking about, it's the master branch at the moment.
https://github.com/bmoscon/cryptofeed/blob/51cb948cd41185ae1d27107d26bfa1a1599bfb40/LICENSE

Thanks

**Comment by ideoma** [comment]
I found this issue

https://github.com/bmoscon/cryptofeed/issues/314


Would be good as a suggestion to include the name XFree86 1.1 either in the readme or the license code itself.

**Comment by bmoscon** [comment]
the license is specified in setup.py and is visible under the license section in pypi.
